### ISSUE TITLE
Incompatible with sodium version 0.5.8 for minecraft version 1.20.1

### ISSUE THREAD

**Issue by GwenBlanketKnight** [Fabricators-of-Create/Create#1339] opened 2024-02-25 15:35 UTC
### Describe the Bug

Incompatible mods found!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with:
		 - sodium 0.5.8+mc1.20.1
More details:
	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.8+mc1.20.1!

### Reproduction Steps

1. install sodium 0.5.8 for minecraft version 1.20.1
2. install create
3.run the game
...

### Expected Result

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with:
		 - sodium 0.5.8+mc1.20.1
More details:
	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.8+mc1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

sodium version 0.5.8 on mincreaft 1.20.1

**Comment by drwoops** [comment] 2024-02-25 15:36
currently create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 and indium 1.0.21 are the precise versions you want.

a fix is in the works

**Comment by IThundxr** [comment] 2024-02-25 15:36
Dupe of #1039

**Closed as completed** 2024-02-25 15:36 UTC
Labels: type: bug

**Comment by pauliesnug** [comment] 2024-02-27 03:48
is there a planned release date, any communication is helpeful, sorry if im being pushy, i understand this is a large project

**Comment by TropheusJ** [comment] 2024-02-27 04:27
there is not
