### ISSUE TITLE
Starlight, Fabric Lifecycle Events, Create and Flywheel - Windmill instacrashes

### ISSUE THREAD

**Issue by LunarHackett003** [Fabricators-of-Create/Create#1070] opened 2023-08-26 00:23 UTC
### Describe the Bug

I attempted to create a windmill to learn the features of Create.
I was met with a rather fat crash.
Appears to say that IllegalStateExceptions are the issue.

### Reproduction Steps

1. Create new world
2. Add exactly 8 windmill sails to a windmill.
3. Right click windmill block to attach structure
4. Witness the game crash.

### Expected Result

A windmill would be created (Whatever that does, start turning?) but instead, game crashes.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/61294652/7b82cd9a-7bc4-44fb-a8fb-65b61d61cde1)

### Crash Report or Log

https://crashy.net/2d7edf35-cc47-4d62-8f4a-eac6ec44595f

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

## Full mod list
aabilites: Armor Abilities 0.1.7
		additionalstructures: Additional Structures 4.2.0
		advancementplaques: Advancement Plaques 1.4.11
		allarrowsinfinityfix: All Arrows Infinity Fix 1.4
		amethyst_core: Amethyst Core 1.2.2+1.20.1
			common-protection-api: Common Protection API 1.0.0
		amethyst_imbuement: Amethyst Imbuement 1.20.1-10
			conditional-mixin: conditional mixin 0.3.2
			fzzy_config: Fzzy Config 0.1.2+1.20.1
			playerabilitylib: Pal 1.8.0
			structurized-reborn: Structurized Reborn 1.20.1-01
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.12
		attributefix: AttributeFix 21.0.2
		autoconfig1u: Auto Config v1 Updated 3.4.0
		awesomedungeon: Awesome dungeon 3.2.0
		awesomedungeonend: Awesome dungeon the end 3.1.1
		awesomedungeonnether: Awesome dungeon nether 3.1.1
		awesomedungeonocean: Awesome dungeon edition ocean 3.3.0
		balm-fabric: Balm 7.0.7
		betteradvancements: Better Advancements 0.3.2.161
		bettercombat: Better Combat 1.7.3+1.20.1
		bookshelf: Bookshelf 20.0.3
		botarium: Botarium 2.2.0
			team_reborn_energy: Energy 3.0.0
		bowinfinityfix: Bow Infinity Fix 2.6.0
		bridgingmod: Bridging Mod 1.20.1-v2.1.0
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		carryon: Carry On 2.1.1.3
		catalogue: Catalogue 1.7.1
		cenchants: Combat Enchants 2.14.9
		charmofundying: Charm of Undying 6.4.2+1.20.1
			spectrelib: SpectreLib 0.13.13+1.20.1
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.65
		controlling: Controlling For Fabric 12.0.2
		create: Create 0.5.1-d-build.1161+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.9-1
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
			porting_lib_base: Porting Lib Base 2.1.1127+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
			porting_lib_models: Porting Lib Models 2.1.1127+1.20
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
				porting_lib_common: Porting Lib Common 2.1.1127+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
		create_new_age: Create: New Age 1.0.1
		createutilities: Create Utilities 0.1.3+1.20.1
		creeperoverhaul: Creeper Overhaul 3.0.1
			resourcefullib: Resourceful Lib 2.0.6
				com_teamresourceful_yabn: yabn 1.0.3
		cristellib: Cristel Lib 1.1.1
		ctov: ChoiceTheorem's Overhauled Village 3.3.3
		cupboard: cupboard 1.20.1-1.8
		darkutils: DarkUtilities 17.0.2
		dungeon_difficulty: Dungeon Difficulty 2.0.5+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		dungeons_arise: When Dungeons Arise 2.1.56.1
		easymagic: Easy Magic 8.0.1
		enchdesc: EnchantmentDescriptions 17.0.4
		entity_model_features: Entity Model Features 0.2.13
		entity_texture_features: Entity Texture Features 4.5.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		experienced_crops: Experienced Crops 1.20.1-1.1.0
		explorify: Explorify v1.3.0-mc1.20u1.20.1
		extra-enchantments-and-curses: Extra Enchantments and Curses 1.6.4
		fabric-api: Fabric API 0.87.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.2+6bdb2ed077
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.2+6bdb2ed077
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.9+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.22
		fallingtree: FallingTree 4.3.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		forgeconfigscreens: Forge Config Screens 8.0.2
		fzzy_core: Fzzy Core 0.2.7+1.20.1
		geckolib: Geckolib 4.2.2
			com_eliotlash_mclib_mclib: mclib 20
		guardvillagers: GuardVillagers 2.0.7-1.20.1
		harvestwithease: Harvest with ease 7.0.0.2
		health_levels: Health Levels 1.0.6
		healthindicatortxf: Health Indicator TXF 1.20.1-1.0.0-fabric
		iceberg: Iceberg 1.1.15
		incendium: Incendium 5.3.1
		infinitybuttons: Infinity Buttons 4.0.1-mc1.20.1
		infwithmend: Infinity with Mending 1.0.2
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.27
		lambdynlights: LambDynamicLights 2.3.1+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		legendarytooltips: Legendary Tooltips 1.4.4
		libraryferret: Library ferret 4.0.0
		magistuarmory: Epic Knights Mod 7.11
		maxhealthfix: MaxHealthFix 12.0.2
		mcda: MC Dungeons Armors 5.0.1
		mcdar: MC Dungeons Artifacts 3.0.0
		mcdw: MC Dungeons Weapons 8.0.3
		menulogue: Menulogue 1.20.1-1.0.4
		mes: Moog's End Structures 1.2-1.20-fabric
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		modelfix: Model Gap Fix 1.14
		modernfix: ModernFix 5.7.1+mc1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
		modmenu: Mod Menu 7.2.1
		moonlight: Moonlight 1.20-2.8.7
		morestructuresmod: More Structures Mod 1.20.1-1.1.1
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v2.1.4
		mr_reds_morestructures: Red’s More Structures 1.0.8
		mvs: Moog's Voyager Structures 4.0-1.20-fabric
		my_first_mod: My First Mod 1.0.0
		mythicmobs: Mythic Mobs 1.3.9
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		notenoughcrashes: Not Enough Crashes 4.4.6+1.20.1
		owo: oωo 0.11.1+1.20
			blue_endless_jankson: jankson 1.2.2
		paladins: Paladins & Priests 0.9.9+1.20.1
		patchouli: Patchouli 1.20.1-81-FABRIC
			fiber: fiber 0.23.0-2
		pigpen: PigPen 15.0.2
		player-animator: Player Animator 1.0.2-rc1+1.20
		polymorph: Polymorph 0.49.0+1.20.1
		porting_lib: Porting Lib 2.1.1125+1.20-entity-refactor
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			mm: Manningham Mills 2.3
			porting_lib_asm: Porting Lib ASM 2.1.1125+1.20-entity-refactor
			porting_lib_chunk_loading: Porting Lib Chunk Loading 2.1.1125+1.20-entity-refactor
			porting_lib_config: Porting Lib Config 2.1.1125+1.20-entity-refactor
			porting_lib_data: Porting Lib Data 2.1.1125+1.20-entity-refactor
			porting_lib_fluids: Porting Lib Fluids 2.1.1125+1.20-entity-refactor
			porting_lib_item: Porting Lib Item 2.1.1125+1.20-entity-refactor
			porting_lib_loot: Porting Lib Loot 2.1.1125+1.20-entity-refactor
			porting_lib_model_builders: Porting Lib Model Builders 2.1.1125+1.20-entity-refactor
			porting_lib_model_generators: Porting Lib Model Generators 2.1.1125+1.20-entity-refactor
			porting_lib_model_materials: Porting Lib Model Materials 2.1.1125+1.20-entity-refactor
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.1.1125+1.20-entity-refactor
			porting_lib_registries: Porting Lib Registries 2.1.1125+1.20-entity-refactor
		prism: Prism 1.0.5
		projectile_damage: Projectile Damage Attribute 3.2.2+1.20.1
		puffish_skills: Pufferfish's Skills 0.8.0
		puzzleslib: Puzzles Lib 8.0.24
		regenerativesleep: RegenerativeSleep 1.0.0
		resourcefulconfig: Resourcefulconfig 2.1.0
		runelic: Runelic 18.0.2
		runes: Runes 0.9.10+1.20.1
		scriptor: Scriptor 0.6.6-1.21.1
		searchables: Searchables 1.0.1
		simplemodconfig: Simple Mod Config 0.0.3
		simplyskills: SimplySkills 0.18.1+1.20.1
		simplyswords: Simply Swords 1.51.1-1.20.1
		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
		skyvillages: Sky Villages 1.0.2.1-1.20.1
		soaringstructures2: Soaring Structures 2 1.20.1 - 2.5.1
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.1.2
		spell_engine: Spell Engine 0.9.29+1.20.1
		spell_power: Spell Power Attribute 0.9.15+1.20.1
		starlight: Starlight 1.1.2+fabric.dbc156f
		starterkit: Starter Kit 5.2
		structory_towers: Structory: Towers 1.0.3
		structureessentials: Structure Essentials Mod 1.20.1-3.0
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		t_and_t: Towns and Towers 1.10.2
		taxfreelevels: Tax Free Levels 1.3.3
		terralith: Terralith 2.4.4
		things: Things 0.3.1+1.20
			lavender: Lavender 0.1.0-pre.6+1.20
				lavender-md: lavender-md 0.1.0-pre.3+1.20
				lavender-md-owo-ui: lavender-md-owo-ui 0.1.0-pre.3+1.20
		tipsmod: Tips 12.0.2
		toolstats: ToolStats 16.0.3
		tooltipfix: ToolTip Fix 1.1.1-1.20
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.2
		trinkets: Trinkets 3.7.1
		villagernames: Villager Names 5.2
		villagersplus: Villagers Plus 2.1
		visualworkbench: Visual Workbench 8.0.0
		walljump: Wall Jump 1.3.6
			org_aeonbits_owner_owner: owner 1.0.12
		waystones: Waystones 14.0.1
		wizards: Wizards 0.9.20+1.20.1
		xaerominimap: Xaero's Minimap 23.6.3
		xaeroworldmap: Xaero's World Map 1.33.1
		yeetusexperimentus: Yeetus Experimentus 2.3.1-build.6+mc1.20.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.0+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
		zoomify: Zoomify 2.11.0
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Flywheel Backend: GL33 Instanced Arrays

**Comment by LunarHackett003** [comment] 2023-08-26 00:26
Update on this - apparently deleting Starlight in Curseforge did nothing so I've manually deleted it.

**Comment by LunarHackett003** [comment] 2023-08-26 00:28
Update 2: the Starlight mod is what caused the issues. Seems its just hard incompatibility with Create.

**Comment by TropheusJ** [comment] 2023-08-26 01:24
duplicate of #1041

**Closed as completed by TropheusJ** 2023-08-26 01:24 UTC
Labels: type: bug
