### ISSUE TITLE
Server Crash, Description: Ticking Block Entity

### ISSUE THREAD

**Issue by tofu-7** [Fabricators-of-Create/Create#540] opened 2022-09-01 22:14 UTC
### Describe the Bug

Loading chuck with a deployer in it causes server to crash. I do not understand why. Seemingly similar to issue #513

### Reproduction Steps

1. Load Chunck with deployer placed in it running on fabric server.

### Expected Result

Not crashing server.

### Crash Report or Log

https://pastebin.com/TdDARScW , https://pastebin.com/YsMLCyCU

### Operating System

Server: Linux (amd64) version 5.15.0-46-generic

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

List of mods from the crash report: [https://pastebin.com/3mmWeUFp](https://pastebin.com/3mmWeUFp)

### Additional Context

Some other mods are being run client side, notably Sodium/Iris and Xaeros World Map, notably missing Indium from Sodium.

**Comment by TropheusJ** [comment] 2022-09-01 22:23
duplicate of #503

**Closed as completed by TropheusJ** 2022-09-01 22:23 UTC
Labels: type: bug
