### ISSUE TITLE
Game crashes with latest build

### ISSUE THREAD

**Issue by Papaturts** [Fabricators-of-Create/Create#234] opened 2022-04-06 02:10 UTC
### Describe the Bug

The game crashes with the latest build in

### Reproduction Steps

1. extract the latest build-basins fixed
2. add to mods folder
3. Run game
...

### Expected Result

Game to run with the mods installed

### Screenshots and Videos

![ice_screenshot_20220405-210613](https://user-images.githubusercontent.com/97408568/161881330-2454babc-2cf6-43f3-b616-5f84fc61293e.png)

### Crash Report or Log

https://pastebin.com/26VvdmaV

### Operating System

Windows 10

### Mod Version

0.4.0f

### Minecraft Version

1.18.1

### Additional Context

Doesnt seem like the proper version isnt selectable above
Using the latest build i believe
create-mc1.18.2_v0.4.1+486.jar
create-mc1.18.2_v0.4.1+486-sources.jar
with the latest fabric
Thank you for the work your doing, love the mod an love that your trying your best to get it to fabric

**Comment by TropheusJ** [comment] 2022-04-06 02:18
duplicate of #231

**Closed as completed by TropheusJ** 2022-04-06 02:18 UTC
Labels: type: bug
