### ISSUE TITLE
Broken chunk lighting phosphor eliminated as possibility (I think)

### ISSUE THREAD

**Issue by RaMcHiPTech** [Fabricators-of-Create/Create#432] opened 2022-07-13 17:40 UTC
### Describe the Bug

I have to optimize my worlds every time before entering the world or whole chunks of lighting go dark.  I have disabled phosphor and optmized the world and it still happens.  Was suggested that this would be a phosphor issue.  Have attached logs and screenshots..  Another note, this is the fabric version not sure if I am in the right place.

### Reproduction Steps

1.
2.
3.
...
1: exit world
2: enter world
3: chunk lighting broken (dark areas)
4: exit world
5: edit world then optimize, deleting cache.
6: enter world (shadows gone)
7: rinse and repeat :)

### Expected Result

Expect the lighting to maintain between exiting and entering the world.

### Screenshots and Videos

![2022-07-13_12 31 19](https://user-images.githubusercontent.com/63215362/178796295-5aee3be3-033f-4ab4-bb62-4351d2e17acd.png)
![2022-07-13_12 23 57](https://user-images.githubusercontent.com/63215362/178796299-e0ef846d-5f2f-4a96-82d7-050ae8678b84.png)
![2022-07-12_18 17 36](https://user-images.githubusercontent.com/63215362/178796301-5b99c326-b546-473c-9b36-ab1d3ffdd9e0.png)

### Crash Report or Log

https://pastebin.com/aEDpZttn

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

I am using fabulously optimized as my base minus colorwheel.  Also added distant horizons plus quality of life thing like REI and Journeymap.

**Comment by RaMcHiPTech** [comment] 2022-07-13 17:54
NM it was phosphor!!! Thanks Tropheus!

**Comment by TropheusJ** [comment] 2022-07-13 17:58
Resolved on discord, duplicate of #318

**Closed as completed by TropheusJ** 2022-07-13 17:58 UTC
Labels: type: bug
