### ISSUE TITLE
Incompatibility between create and origins

### ISSUE THREAD

**Issue by Tomzor** [Fabricators-of-Create/Create#194] opened 2022-03-11 07:12 UTC
### Describe the Bug

Disconnects from a single player world log calls out errors with origins and assossciated addons.

### Reproduction Steps

1. Have Create, Flywheel, and Origins Installed
2. Lauch Minecraft
3. Create World

### Expected Result

Joining a world.

### Crash Report or Log

https://gist.github.com/Tomzor/8af7c7d3fa89acf5927e2e7ac2a2c1ad

### Operating System

Windows 11

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Flywheel-Fabric-1.18-0.6.1.24
Origins-1.18-1.3.1

### Additional Context

Probably not super relevant before it being released but ran across it and thought I might as well report it.

**Comment by AlphaMode** [comment] 2022-03-11 07:26
Have you tested this without create as the log you gave doesn't mention create at all

**Comment by Tomzor** [comment] 2022-03-11 07:29
Oh I did but I felt pretty sure this was a log with create. Looks like it's there line 13.

**Comment by JieningYu** [comment] 2022-03-11 11:01
Does it crash without Create or without origins?

**Comment by Alkiasan** [comment] 2022-03-11 18:13
Having same issue, removing Create fixes the problem, seems to be an issue present on newer builds as I didn't run into this issue until I updated to the latest build

**Comment by Alkiasan** [comment] 2022-03-11 20:37
Isolated error here:
https://www.toptal.com/developers/hastebin/awumuzuqet.sql

Create or load a world, and get instantly kicked back to multiplayer screen, meaning internal server is crashing on start somehow.
Seems relating to attribute names, does Create modify them?

**Comment by Alkiasan** [comment] 2022-03-11 20:49
And here's a new log with exclusively Create and Origins installed:
https://www.toptal.com/developers/hastebin/devuqutika.sql

**Comment by mrsterner** [comment] 2022-03-11 22:08
I too have this issue with origin and create, Neither can live while the other survives

**Comment by TropheusJ** [comment] 2022-03-13 19:36
[potential_fix.zip](https://github.com/Fabricators-of-Create/Create/files/8240445/potential_fix.zip)
This jar has a modified port lib jar. Add this to your mods and test. This will be broken in many other ways, I removed some possibly problematic code, so don't use it on anything important. Provide log after.

**Comment by Alkiasan** [comment] 2022-03-13 19:59
Tested, issue persists, but here's the log as requested:
https://www.toptal.com/developers/hastebin/bisohodefe.sql

Also been talking on the origins discord about this, this is what I've got, seems to be from the guy who worked on porting Apoli to forge:

> Right, I would like to start saying that I'm not really familiar with fabric. With that out of the way, this looks like a packet wasn't cut at the right position.
> What this means is basically: There's too much data going through the login pipeline, and it can't perform normal operations.
> There are fixes for this, but the main one is moving some of the synchronization code out of the login pipeline and into the play pipeline. (Which isn't easy because there are several injection spots needed for that).
> 
> If I'm right on my assumptions, this isn't an issue that should be addressed by Origins or Create, but by the Fabric team.
> See: https://github.com/MinecraftForge/MinecraftForge/pull/7485 for the issue I believe fabric currently has.
>

**Comment by TropheusJ** [comment] 2022-03-13 21:41
[jars.zip](https://github.com/Fabricators-of-Create/Create/files/8240663/jars.zip)
Please test with these two jars. I've disabled all syncing on connection. Stuff will break!

**Comment by mrsterner** [comment] 2022-03-13 22:30
Issue still persist even after the jars.zip.
Seems like Porting lib alone is causing the issue

**Comment by Alkiasan** [comment] 2022-03-13 23:43
Alright, give me a second and i'll get a log

**Comment by Alkiasan** [comment] 2022-03-13 23:45
Issue persists, here's the Log:
https://www.toptal.com/developers/hastebin/ibofusezow.sql

**Comment by TropheusJ** [comment] 2022-03-14 01:23
I've set up origins in dev and I can reproduce. will look into it more.

**Comment by AlphaMode** [comment] 2022-04-14 16:34
Is this still persistent on the lastest build?

**Comment by Alkiasan** [comment] 2022-04-14 22:22
Latest build is on 1.18.2 by the looks of it, will have to wait until origins updates to 1.18.2, which should be soon-ish according to Apace on the Origins discord (Said either today or tomorrow)

**Comment by AlphaMode** [comment] 2022-04-15 18:51
This appears to be fixed in 1.18.2

**Closed as completed by AlphaMode** 2022-04-15 18:51 UTC
Labels: type: bug
