### ISSUE TITLE
Train sometimes get stuttery after moving through portal to the nether

### ISSUE THREAD

**Issue by misigno** [Fabricators-of-Create/Create#1368] opened 2024-03-11 12:39 UTC
### Describe the Bug

Sometimes going through a nether portal while on a train makes the train stuttery, only happens in the nether, train can still be controlled and is fixed either by going back to overworld or dismounting the train.

When train is moving in that state console gets spammed with : `[Render thread/WARN]:
 Received passengers for unknown entity`
When dismounting train in that state console gets : 
`[Render thread/ERROR]: Error executing task on Client`
`java.lang.ArrayIndexOutOfBoundsException: null`

Suspecting networking issue and desync between client and local server.

### Reproduction Steps

1.Build train and nether portal
2.Go back and forth between dimensions
3.Sometimes in the nether train controls get weird and train stutters

### Expected Result

Train no go wonky

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/5872835/196c2c03-d2de-4b22-92ba-2acf7f0e8bd2

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Fabric API 0.92.0

### Additional Context

Cannot reproduce on forge version

**Comment by misigno** [comment] 2024-03-11 13:01
Dismiss error `[Render thread/WARN]: Received passengers for unknown entity` as it is not produced by create.
However manually moving a train with a seated entity through a portal makes the seated entity stuttery on the other side

**Comment by TropheusJ** [comment] 2024-03-31 05:58
can't reproduce on the latest commit.

**Comment by TropheusJ** [comment] 2024-03-31 18:13
nevermind, got it to happen

**Comment by TropheusJ** [comment] 2024-04-07 03:32
fixed by [this](https://github.com/Fabricators-of-Create/Create/commit/9e3e686e0ef3cf3e63c47e13659b7760da039452) and [this](https://github.com/Fabricators-of-Create/Create/commit/f7d9f0e7cd99c3e697266ce47a8c64d24d53d5d1)

**Closed as completed by TropheusJ** 2024-04-07 03:32 UTC
Labels: type: bug
