### ISSUE TITLE
Crash with enderchests-fabric

### ISSUE THREAD

**Issue by cold233** [Fabricators-of-Create/Create#472] opened 2022-07-31 12:35 UTC
### Describe the Bug

the game crash with enderchests-fabric (https://www.curseforge.com/minecraft/mc-mods/enderchests-fabric)
list of mod installed:
create-1.18.2-0.5.0c-703
enderchests-fabric-1.18-1.0.10
fabric-api-0.58.0+1.18.2
shetiphiancore-fabric-1.18-1.2.13(support library for enderchests)
fabric version:0.14.8
minecraft version: 1.18.2
operating system: Windows 10 19044.1826
Java Version: 17.0.1, Azul Systems, Inc.
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
latest.log of game: https://drive.google.com/file/d/1jDoGEhV8waTK6QvjiTAuF3h3EV7Z26Mg/view?usp=sharing

### Reproduction Steps

1.install listed mods
2.launch game
3.the game will crash.
...

### Expected Result

the game should run normally as previous version ( v0.4.1+637 )

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment] 2022-07-31 23:24
duplicate of #452

**Closed as completed by TropheusJ** 2022-07-31 23:24 UTC
Labels: type: bug
