### ISSUE TITLE
Server crashed when placed down a deployer block

### ISSUE THREAD

**Issue by blufish1234** [Fabricators-of-Create/Create#749] opened 2023-01-09 08:13 UTC
### Describe the Bug

Server crashed when placed down a deployer block. The server can still start. When a player near that block joins, however, the server crashes immediately. 

### Reproduction Steps

1. Enter a fabric 1.19.2 minecraft server with create installed
2. place down a deployer block
3. Server crashed

### Expected Result

The deployer should be placed down as normal and the server shouldn't crash

### Crash Report or Log

https://pastebin.com/FkU9Hi6G

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Server: Environmental creepers, phosphor, tabtps

**Comment by TropheusJ** [comment] 2023-01-09 14:21
Duplicate of #503, fixed in next update

**Closed as completed by TropheusJ** 2023-01-09 14:21 UTC
Labels: type: bug
