### ISSUE TITLE
Portable storage interface not retracting

### ISSUE THREAD

**Issue by vsxgsonic** [Fabricators-of-Create/Create#580] opened 2022-11-05 16:49 UTC
### Describe the Bug

so unless I'm going crazy, the AOF5 pack as a weird interaction with it or something changed .when the Portable storage interface has finished unloading it should retract and the build should then continue on its way.

### Reproduction Steps

1.build contraption and give it and inventory with items
2.let it move up to and let the 2 Portable storage interface's connect 
3.watch the items empty and them not retract
...

### Expected Result

my contraptions after emptying their inventory using Portable storage interface they should retract and allow it to go on its way 

### Operating System

Windows 11

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

### Other Mods

ALL of Fabric 5  .mod pack

**Comment by WhyKickAmooCow** [comment] 2022-11-06 09:44
We have also run into this issue on our server, the temporary solution was to use a chute instead of a hopper.

**Comment by TropheusJ** [comment] 2022-11-20 10:10
This was fixed on 1.19 with a rework to transfer. For 1.18, the issue is limited to hoppers, and fixing it would take a lot of work.

**Closed as completed by TropheusJ** 2022-11-20 10:10 UTC
Labels: type: bug
