### ISSUE TITLE
Incorrect shapeless recipes with 1 item create mod mixer in EMI

### ISSUE THREAD

**Issue by ghost** [Fabricators-of-Create/Create#1304] opened 2024-02-08 13:30 UTC
### Describe the Bug

Every shapeless recipe with 1 ingredient is also shown in EMI as Create automated shapeless crafting recipe.

### Reproduction Steps

1. Open Inventory
2. Look for a crafting recipe with 1 ingredient like Planks to Button or Gearbox to Vertical Gearbox
3. On the top there's also a tab for Automated shapeless crafting with the 1 ingredient recipe.
...

### Expected Result

recipe doesn't appear in Automated shapeless crafting

### Screenshots and Videos

![grafik](https://github.com/Fabricators-of-Create/Create/assets/159393991/022e9205-7647-402a-8ce0-a4f03fd6272e)
![grafik](https://github.com/Fabricators-of-Create/Create/assets/159393991/1f395d6d-daee-4544-be60-b26d85975a3b)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

EMI 1.1.0+1.20.1+fabric
Fabric API 0.91.0+1.20.1

**Comment by TropheusJ** [comment] 2024-02-08 19:27
duplicate of #1148

**Closed as completed by TropheusJ** 2024-02-08 19:27 UTC
Labels: type: bug
