### ISSUE TITLE
Invalid Locale causes crash

### ISSUE THREAD

**Issue by AyMarte** [Fabricators-of-Create/Create#1189] opened 2023-11-10 16:46 UTC
### Describe the Bug

When this bug occurred, the Mojang loading screen popped up and before it finished loading, it reset the progress on the bar and opened another one like nothing had happened. Not that long after, about 2 seconds it instantly disappears to the main screen and shows a popup containing an exclamation point and "_Resource reload failed_".

### Reproduction Steps

Happens every time the game gets loaded up.

### Expected Result

No error.

### Screenshots and Videos

[Drive Video Of This Experience](https://drive.google.com/file/d/1qpUJTM2_q4N1qPdZ0zcyizkLlptbuEjM/preview)

### Crash Report or Log

[/Main/ Developer Console](https://pastebin.com/6Vqg1E9j), [Crash Report](https://pastebin.com/zXj4jPzk)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

MineFortress, as stated above.

**Comment by TropheusJ** [comment] 2023-11-20 20:38
Try switching your game's language to something else and then change it back. Sometimes it gets in a weird broken state.

**Comment by TropheusJ** [comment] 2024-02-14 07:57
duplicate of #1120

**Closed by TropheusJ** 2024-02-14 07:57 UTC
Labels: bug, blocking
