### ISSUE TITLE
Redstone Links Corrupts Chunks on Fabric

### ISSUE THREAD

**Issue by LicitLettuce** [Fabricators-of-Create/Create#421] opened 2022-07-09 23:16 UTC
### Describe the Bug

When using redstone links and redstone lamps together on the fabric port of create, the chunk becomes completely corrupt by making the chunk completely dark no matter the time of day. I've tried to undo the corruption but I have not discovered a way to undo it. This can be very problematic and ruin worlds

### Reproduction Steps

1. use redstone lamps and links together
2. exit the world
3. reload the world

### Expected Result

I expected the lamps to activate when given a signal, but they ruin chunks

### Screenshots and Videos

![2022-07-09_19 13 51](https://user-images.githubusercontent.com/108856029/178125470-84ae51a1-ed77-4587-b244-1dd2a2051d58.png)

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment] 2022-07-10 00:37
Duplicate of #318

**Closed as completed by TropheusJ** 2022-07-10 00:37 UTC
Labels: type: bug
