### ISSUE TITLE
Incompatible with sodium

### ISSUE THREAD

**Issue by Gifarues** [Fabricators-of-Create/Create#1200] opened 2023-11-23 20:47 UTC
### Describe the Bug

I get an incompatibility message when I try to load the Create Fabric and Sodium mods together

### Reproduction Steps

1.Open the launcher in Fabric version 1.20.1
2.Place in the mods folder: Create Fabric, Sodium and Fabric API (the mods in the same version of the launcher)
3.Load the launcher
...

### Expected Result

I was hoping minecraft would run with both mods

### Screenshots and Videos

![Captura de pantalla 2023-11-23 212650](https://github.com/Fabricators-of-Create/Create/assets/151877445/91407c81-1552-43d3-b383-8024358b25a3)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Sodium 0.5.3
Fabric API 0.90.7+1.20.1

### Additional Context

I hope they fix this crash

**Comment by Tymonoman** [comment] 2023-11-23 21:11
Either downgrade to sodium 0.4.x or wait a couple of weeks for the fix for this 
Edit: also this has been brought up a lot so you can close this issue

**Comment by Alex134831** [comment] 2023-11-27 11:41
It's been an issue for months because Flywheel wasn't updated I think
fix fork: https://modrinth.com/mod/create-fabric-sodium-fix (they forked flywheel too)
#1039 is locked so we can't add this info so it is good that this issue was made

**Comment by TropheusJ** [comment] 2023-12-18 04:17
duplicate of #1039

**Closed as completed by TropheusJ** 2023-12-18 04:17 UTC
Labels: type: bug
