### ISSUE TITLE
Funnels cause immense lag, causing servers to crash

### ISSUE THREAD

**Issue by JXSnack** [Fabricators-of-Create/Create#1366] opened 2024-03-10 14:53 UTC
### Describe the Bug

Funnels use tons of performance, even more than chickens and we've got lots of those.
https://o.tas.sh/#9B97L

### Reproduction Steps

1. Craft funnels
2. Place funnels
3. Watch

### Expected Result

That it does not use so much performance

### Screenshots and Videos

![Bildschirmfoto 2024-03-10 um 15 51 21](https://github.com/Fabricators-of-Create/Create/assets/72796341/af69bd38-220f-4fce-a292-2bd565a17056)
![Bildschirmfoto 2024-03-10 um 15 51 38](https://github.com/Fabricators-of-Create/Create/assets/72796341/b33ddd03-bb97-4902-8460-a85bfe60750d)

### Operating System

Linux Ubuntu

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Observable
Replay Mod

**Comment by Dinobaby312** [comment] 2024-03-11 17:07
What is the visual aid that you're using to see the tick health, is it Carpet or an add on?

**Comment by JXSnack** [comment] 2024-03-11 19:03
It's Observable and Spark for TPS viewing

**Comment by TropheusJ** [comment] 2024-03-24 16:46
duplicate of #1364

**Closed as completed by TropheusJ** 2024-03-24 16:46 UTC
Labels: type: bug
