### ISSUE TITLE
Deployers crash Dedicated Servers when placed

### ISSUE THREAD

**Issue by Alkiasan** [Fabricators-of-Create/Create#150] opened 2022-02-17 21:08 UTC
### Describe the Bug

Whenever a Deployer is placed, it crashes the dedicated server

### Reproduction Steps

1.Place Deployer
2.Server Crashes

### Expected Result

Server runs normally

### Crash Report or Log

https://www.toptal.com/developers/hastebin/zelohanubo.yaml

### Operating System

Windows 11

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment] 2022-02-17 21:12
duplicate of #117

**Closed as completed by TropheusJ** 2022-02-17 21:12 UTC
Labels: type: bug
