### ISSUE TITLE
Crash on startup if create-client.toml is already present

### ISSUE THREAD

**Issue by WastelandOasis** [Fabricators-of-Create/Create#878] opened 2023-04-06 06:35 UTC
### Describe the Bug

The game is crashing on startup with the latest version 0.5.0.i-989+1.19.2. This is occuring only if the create-client.toml has been generated. If I remove this from config before launching the game it will work completely fine until launching this game again. Have been able to recreate this on existing modpack with no mods but create enabled and a fresh install of minecraft with only create installed. Tried with both Fabric 0.14.18 and 0.14.19. 

### Reproduction Steps

1. Launch game
2. have create-client.toml present in config folder
3. Crash at startup

### Expected Result

Game launches as intended

### Crash Report or Log

https://pastebin.com/1nQzR0Yi

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Can recreate with no other mods installed

**Comment by NetunooOG** [comment] 2023-04-06 13:22
Mine is still crashing after removing that file also tried common one after, conflicting with twilight forest now as well.

**Comment by WastelandOasis** [comment] 2023-04-06 16:21
Sounds like an unrelated issues to my bug report.

**Comment by TropheusJ** [comment] 2023-04-06 19:08
duplicate of #845

**Closed as completed by TropheusJ** 2023-04-06 19:08 UTC
Labels: type: bug
