### ISSUE TITLE
Crash when pumping water into fluid tank - Ticking block entity with Twilight Forest

### ISSUE THREAD

**Issue by Aviator2276** [Fabricators-of-Create/Create#709] opened 2022-12-26 22:19 UTC
### Describe the Bug

When creating a simple fluid tank with a mechanical pump and crank, Minecraft crashes when the water gets into the fluid tank. It doesn't crash while in transit of the pipes, only when it hits the tank. The server had 56 mods but I found the conflicting mod to be Twilight Forest. Without it, everything runs fine. Only the Twilight Forest, Fabric API, and Create, it crashes.

Versions:
 - Fabric Loader: 0.14.11
 - Fabric Minecraft: 1.18.2
 - Twilight Forest: twilightforest-fabric-1.18.2-4.1.313
 - Create: create-fabric-0.5.0g-792+1.18.2
 - Fabric API: fabric-api-0.67.0+1.18.2

### Reproduction Steps

1. Load Fabric 1.18.2 with the 3 mods: Create, Twilight Forest, and Fabric API
2. Create a new world
3. Create a simple 2-by-2 Fluid Tank
4. Attach Mechanical Pump on the side with pipes leading to the water
5. Attach Cogwheel and Creative Motor
6. Pump water so it can reaches the Tank

### Expected Result

No hard crash and water to fill the Fluid Tank

### Screenshots and Videos

https://user-images.githubusercontent.com/91645065/209585627-bfaa6745-c0ab-4e92-a142-ede8fd91f438.mp4

### Crash Report or Log

https://gist.github.com/Aviator2276/7860546d5410440bfe2661747bce5ad8

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

Fabric API - fabric-api-0.67.0+1.18.2
Twilight Forest - twilightforest-fabric-1.18.2-4.1.313

### Additional Context

I did reproduce this on my laptop and got the same issue
Crash Report from Laptop:
https://gist.github.com/Aviator2276/c7f7598172fa6f8e26e1318c2ea6ef37

**Comment by TropheusJ** [comment] 2022-12-26 23:03
duplicate of #701

**Closed as completed by TropheusJ** 2022-12-26 23:03 UTC
Labels: type: bug
