### ISSUE TITLE
Invisible wheel

### ISSUE THREAD

**Issue by Noplace0** [Fabricators-of-Create/Create#83] opened 2022-01-09 10:57 UTC
### Describe the Bug

![image](https://user-images.githubusercontent.com/30548562/148683522-5633da9a-7d85-4d9b-84f5-b758c9bc51a0.png)
---------------My machine ---------------------

![image](https://user-images.githubusercontent.com/30548562/148679130-fa63f8d7-6821-4267-887e-7690c0fabfba.png)
---------------When I get back to my machine! Rejoin my world then it happened--------------------------
From the above image, you can see the water wheel still exists in the world but I can see it.
The water wheel and shaft turn invisible when I saved my single-player world and rejoin my single-player world.

### Reproduction Steps

1. put down a water wheel, shaft,set up your machine (mechanical press)
2. save and quit (back to Minecraft main menu)
3. rejoin the single-player world
4.  water wheel and all the shaft is now invisible, I can only see mechanical press 

...

### Expected Result

I expected all the thing is visible when I get back to my single-player world.

### Crash Report or Log

no, don't know what log I can provide

### Operating System

Win 10

### Mod Version

0.4.0b

### Minecraft Version

1.18.1

### Other Mods

Better Minecraft without iris mod

**Comment by TropheusJ** [comment] 2022-01-09 14:58
Duplicate of #54

**Closed as completed by TropheusJ** 2022-01-09 14:58 UTC
Labels: type: bug
