### ISSUE TITLE
Starlight for Fabric crashes the game when trying to make a new windmill.

### ISSUE THREAD

**Issue by Ny-won** [Fabricators-of-Create/Create#1228] opened 2023-12-18 22:29 UTC
### Describe the Bug

On 1.20.1, using Feather Client which had the mod "Starlight" installed, I tried to make a new windmill and attach sails to it, when right clicking to attach, the game crashed and every attempt to re-join the world ended in a game crash.

### Reproduction Steps

1. Place windmill bearing.
2. Attach sails to the bearing somehow.
3. Right click on bearing.

### Expected Result

Windmill to be created and begin to spin.

### Crash Report or Log

[message.txt](https://github.com/Fabricators-of-Create/Create/files/13709112/message.txt)

### Operating System

Windows 10.

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment] 2023-12-18 22:53
duplicate of #1041

**Closed as completed by TropheusJ** 2023-12-18 22:53 UTC
Labels: type: bug
