### ISSUE TITLE
Crash when placing down honey bucket

### ISSUE THREAD

**Issue by Justsnoopy30** [Fabricators-of-Create/Create#282] opened 2022-05-09 02:47 UTC
### Describe the Bug

You crash when you place down a honey bucket.

### Reproduction Steps

1. Place down a honey bucket from Create
2. Observe crash

### Expected Result

Not crash

### Crash Report or Log

https://paste.gg/p/anonymous/456a05ea2a294f70a13a6d26c297b9d5

### Operating System

Ubuntu 22.04

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

[20:53:49] [main/INFO]: Loading 245 mods:
	- advanced_runtime_resource_pack 0.5.7 via phonos
	- animatica 0.4+1.18
	- appleskin 2.4.0+mc1.18.2
	- architectury 4.4.54
	- automobility 0.0.9+1.18.2
	- badpackets 0.1.2
	- badstdout 1.1.1-1.18
	- bclib 1.4.5
	- betterdungeons 1.18.2-Fabric-2.1.0
	- betterend 1.1.0
	- bettermineshafts 1.18.2-Fabric-2.1.1
	- betternether 6.1.1
	- betterstrongholds 1.18.2-Fabric-2.1.1
	- bitsandchisels 2.6.8
	- blue_endless_jankson 1.2.1 via jankson
	- borderlessmining 1.1.2+1.18.2
	- byg 1.4
	- campanion 3.0.4
	- cardinal-components-base 4.1.3 via trinkets
	- cardinal-components-entity 4.1.3 via trinkets
	- carpet 1.4.69
	- cem 0.7.1
	- citresewn 1.0.1+1.18.2
	- citresewn-defaults 1.0.1+1.18.2 via citresewn
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- colormatic 3.1.1+mc.1.18.2
	- com_electronwill_night-config_core 3.6.4 via terrablender
	- com_electronwill_night-config_toml 3.6.4 via terrablender
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_github_llamalad7_mixinextras 0.0.9 via porting_lib
	- com_github_meteordevelopment_starscript 0.1.9 via respackopts
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- com_typesafe_config 1.4.1 via croptopia
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- completeconfig 1.4.0
	- continuity 1.1.0+1.18.2
	- cosmetica 1.1.1
	- craftpresence 1.8.8
	- create mc1.18.2_v0.4.1+548
	- croptopia 2.0.0
	- dcch 1.0
	- dml-refabricated 1.18.2
	- dml-refabricated-base 1.18.2 via dml-refabricated
	- dml-refabricated-events 1.18.2 via dml-refabricated
	- dml-refabricated-modular-armor 1.18.2 via dml-refabricated
	- dml-refabricated-rei 1.18.2 via dml-refabricated
	- dripstone_fluid_lib 1.2.0 via milk
	- dynamicfps 2.1.0
	- ecologics 1.5.4
	- entity_texture_features 2.6.0
	- fabric 0.51.1+1.18.2
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-data-generation-api-v1 2.0.7+6d3e563660 via registrate-fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.7.2+kotlin.1.6.20
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 2.0.0+1.18.2-SNAPSHOT via inspecio
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via cosmetica
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.14.4+local
	- fabricskyboxes 0.5.5
	- fake-player-api 0.3.0 via create
	- farmersdelight 1.18.2-0.2.1
	- fastopenlinksandfolders 1.1.0
	- feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via patchouli
	- flywheel 1.18-0.6.2.25 via create
	- forcecloseloadingscreen 1.1.0
	- forge_tags 2.1 via registrate-fabric
	- forgeconfigapiport 3.2.0 via create
	- forgetmechunk 1.18.X-1.0.3
	- gateofbabylon 1.7.0-1.18.2
	- geckolib3 3.0.36
	- illuminations 1.10.3
	- incendium 5.0.3
	- indium 1.0.3+mc1.18.2
	- indrev 1.14.0-BETA
	- inmis 2.5.3-1.18.2
	- inspecio 1.3.0+1.18
	- io_gitlab_jfronny_gson 2.9.0.2022.4.2.19.45.43 via respackopts
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- iris 1.2.4-build.38
	- itemmodelfix 1.0.3+1.18
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- jsonem 0.1.2 via automobility
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- kibe 1.9.7-BETA+1.18
	- krypton 0.1.9
	- ktdatataglib 1.6.5+1.18.2 via dml-refabricated
	- kubejs 1802.5.1-build.395
	- lambdabettergrass 1.2.3+1.18
	- lambdynlights 2.1.0+1.17
	- lazydfu 0.1.2
	- libblockattributes_core 0.10.0 via indrev
	- libblockattributes_fluids 0.10.0 via indrev
	- libblockattributes_items 0.10.0 via indrev
	- libgui 5.3.1+1.18 via mocolors
	- libjf-base 2.7.0 via respackopts
	- libjf-data-manipulation-v0 2.7.0 via respackopts
	- libjf-unsafe-v0 2.8.0-1650931054 via respackopts
	- libninepatch 1.1.0 via libgui
	- libzoomer 0.4.0+1.18.2 via okzoomer
	- lithium 0.7.9-SNAPSHOT
	- magna 1.7.0-1.18-pre1 via indrev
	- malilib 0.12.1
	- mcwbridges 2.0.2
	- mcwpaintings 1.0.3
	- megane 7.5.1
	- megane-api 7.1.0 via megane
	- megane-fabric-transfer 7.1.0 via megane
	- megane-industrial-revolution 7.1.0 via megane
	- megane-kibe 7.1.0 via megane
	- megane-lib-block-attributes 7.1.0 via megane
	- megane-reborn-energy 7.0.0 via megane
	- megane-runtime 7.2.0 via megane
	- megane-vanilla 7.1.1 via megane
	- midnightlib 0.4.0 via puzzle
	- milk 0.3.0 via create
	- minecraft 1.18.2
	- mixintrace 1.1.1+1.18.1
	- mm 2.3 via porting_lib
	- mocolors 1.4.0
	- modmenu 3.1.0
	- morechathistory 1.1.0
	- mostructures 1.4.2+1.18.2
	- mtr 1.18.2-3.0.0
	- myron 1.6.3+1.18.1 via shetiphiancore
	- noindium 1.0.1+1.18.2 via create
	- not-that-cc 1.0
	- okzoomer 5.0.0-beta.5+1.18.2
	- omega-config 1.2.3-1.18.1 via inmis
	- org_anarres_jcpp 1.4.14 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_quiltmc_quilt-json5 1.0.0 via okzoomer
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- packet_tweaker 0.2.0+1.18-pre1 via polymer
	- patchouli 1.18.2-67-FABRIC
	- pehkui 3.3.0+1.14.4-1.19
	- phonos 0.3+1.18.2
	- platforms 1.2.4
	- playerabilitylib 1.5.0 via kibe
	- polymer 0.2.0-beta.40+1.18.2 via polymer-all
	- polymer-all 0.2.0-beta.40+1.18.2
	- polymer-blocks-ext 0.1.0-alpha.7+1.18.2 via polymer-all
	- polymer-legacy 0.1.9+0.2.0-beta.40+1.18.2 via polymer
	- porting_lib 0.2.0+1.18.2.7714a8d via create
	- pride 1.1.0+1.17 via lambdynlights
	- puzzle 1.2.1
	- puzzle-base 1.2.1 via puzzle
	- puzzle-gui 1.2.1 via puzzle
	- puzzle-models 1.2.1 via puzzle
	- puzzle-splashscreen 1.2.1 via puzzle
	- quilt_base 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-api-base
	- quilt_client_command 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-command-api-v1
	- quilt_command 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-command-api-v1
	- quilt_lifecycle_events 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-lifecycle-events-v1
	- quilt_resource_loader 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-resource-loader-v0
	- quilt_tags 1.0.0+1.18.2-SNAPSHOT via inspecio
	- quilt_tooltip 1.0.0+1.18.2-SNAPSHOT via fabric-rendering-v1
	- quilted-fabric-api-base 1.0.0+1.18.2-SNAPSHOT via inspecio
	- quilted-fabric-command-api-v1 2.0.0+1.18.2-SNAPSHOT via inspecio
	- quilted-fabric-lifecycle-events-v1 2.0.1+1.18.2-SNAPSHOT via inspecio
	- quilted-fabric-resource-loader-v0 1.0.0+1.18.2-SNAPSHOT via inspecio
	- reach-entity-attributes 2.1.1 via campanion
	- registrate-fabric MC1.18.2-1.0.x via create
	- replaymod 1.18.2-2.6.4
	- repurposed_structures 4.1.6+1.18.2
	- respackopts 2.10.1
	- rhino 1801.1.9-build.135
	- roughlyenoughitems 8.1.9999
	- seedfix 1.0.2
	- servertick 1.6
	- shetiphiancore 1.2.10
	- skinlayers 1.4.3-mc1.18.2
	- sodium 0.4.1+replaymod-rev.9fa8b28
	- spark 1.9.1
	- spectater 2.0.1
	- spruceui 3.3.3+1.18 via lambdabettergrass
	- stacc 1.2.3 via bitsandchisels
	- starlight 1.0.2+fabric.a920f5a
	- step-height-entity-attribute 1.0.0 via indrev
	- sulphate 1.0.2 via cosmetica
	- tcc 1.0.1
	- team_reborn_energy 2.0.0-beta1 via indrev
	- terrablender 1.1.0.99
	- terralith 2.2.1
	- tooltipfix 1.0.4-1.18
	- trinkets 3.3.0
	- waystones 2.5.0
	- worldedit 7.2.10-SNAPSHOT+6109-1734dc7
	- wthit 4.10.1
	- xaerominimapfair 22.6.1
	- xaeroworldmap 1.21.1
	- yellowstone-panorama 1.0
	- yosbr 0.1.1
	- yungsapi 1.18.2-Fabric-2.0.8
	- yungsbridges 1.18.2-Fabric-2.1.0

**Comment by Cart3r1234** [comment] 2022-05-09 02:53
This is an incompatibility with colormatic

**Comment by TropheusJ** [comment] 2022-05-09 02:53
duplicate of #255

**Closed as completed by TropheusJ** 2022-05-09 02:53 UTC
Labels: type: bug

**Comment by Justsnoopy30** [comment] 2022-05-09 23:31
Ah sorry I didn't see it since it was closed.
