### ISSUE TITLE
Glue Particles Appear even when the Block Placement does not happen.

### ISSUE THREAD

**Issue by surprisedpika** [Fabricators-of-Create/Create#280] opened 2022-05-07 14:55 UTC
### Describe the Bug

When a block is placed onto the glue entity, glue particles are spawned. Sometimes, a glue is invalid and the block does not place. In this case, the particles should not spawn. However, in Fabric Create, glue particles do spawn. In Forge Create, the particles are not spawned.

### Reproduction Steps

1. Place down a block such as a Brass Funnel
2. Place glue on the side using the Super Glue item
3. Attempt to place a mechanical harvester on the super glue
4. Glue Particles will appear, but the block will not place

### Expected Result

Because the block does not place, the glue particles should not appear.

### Screenshots and Videos

https://user-images.githubusercontent.com/82579156/167259671-29cee066-fa75-47d1-a78e-f6d6e9ab0c02.mp4

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Architectury
Bad Packets
Cloth Config v6
Indium
Iris
Lithium
QSL
REI
Soidum
WTHIT

### Additional Context

I was playing with the Quilt Loader on Create Build #548

**Comment by TropheusJ** [comment] 2022-05-07 19:02
Duplicate of #67, would take a *lot* of work to fix a very insignificant visual issue

**Closed as completed by TropheusJ** 2022-05-07 19:02 UTC
Labels: type: bug
