### ISSUE TITLE
BYG (Oh The Biomes You'll Go) compat recipes out of date

### ISSUE THREAD

**Issue by briansemrau** [Fabricators-of-Create/Create#688] opened 2022-12-17 22:32 UTC
### Describe the Bug

Logs are showing an error for a recipe used for compatibility with BYG.

```java
[20:51:35] [Render thread/ERROR]: Parsing error loading recipe create:cutting/compat/byg/mangrove_log
com.google.gson.JsonSyntaxException: Unknown item 'byg:mangrove_log'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:579) ~[client-intermediary.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.0g-7961.19.2.jar.i0:0/:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.0g-7961.19.2.jar.i0:0/:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.0g-7961.19.2.jar.i0:0/:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[client-intermediary.jar:?]
```

It appears that there is an outdated compat recipe:
https://github.com/Fabricators-of-Create/Create/blob/88afd924f068cef53eb438dec648daf360969204/src/generated/resources/data/create/recipes/cutting/compat/byg/mangrove_log.json#L13-L19

It looks like BYG renamed `mangrove` to `white_mangrove`:
https://github.com/AOCAWOL/BYG/blob/90ecd7f76738f24b89e86900c23d598fd8ab7e2c/Common/src/main/java/potionstudios/byg/common/block/BYGWoodTypes.java#L88-L91

https://github.com/AOCAWOL/BYG/commit/8785c8a3bbdad746036f289b39d2d702ef787e1b

### Reproduction Steps

N/A

### Expected Result

Recipes should work.

### Crash Report or Log

https://gist.github.com/briansemrau/59d776520d6588a27d50012881bf2fe7

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Oh The Biomes You'll Go

### Additional Context

Issue appears to be fixed by modifying the .jar

find: `mangrove`
replace with: `white_mangrove`
in folders: `recipes/**/compat/byg`

**Comment by ChristopherHaws** [comment] 2022-12-22 06:04
I am getting the same, plus a few extra recipe errors:
```shell
[06:05:00] [main/ERROR]: Parsing error loading recipe create:cutting/compat/byg/mangrove_log
com.google.gson.JsonSyntaxException: Unknown item 'byg:mangrove_log'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:579) ~[server-intermediary.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:958) [server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:946) [server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:156) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.12-launcher.0.11.1.jar:0.11.1]
[06:05:00] [main/ERROR]: Parsing error loading recipe create:cutting/compat/byg/stripped_mangrove_log
com.google.gson.JsonSyntaxException: Unknown item 'byg:stripped_mangrove_log'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:579) ~[server-intermediary.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:958) [server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:946) [server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:156) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.12-launcher.0.11.1.jar:0.11.1]
[06:05:00] [main/ERROR]: Parsing error loading recipe create:cutting/compat/byg/mangrove_wood
com.google.gson.JsonSyntaxException: Unknown item 'byg:mangrove_wood'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:579) ~[server-intermediary.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:958) [server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:946) [server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:156) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.12-launcher.0.11.1.jar:0.11.1]
[06:05:00] [main/ERROR]: Parsing error loading recipe create:cutting/compat/byg/stripped_mangrove_wood
com.google.gson.JsonSyntaxException: Unknown item 'byg:stripped_mangrove_wood'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:579) ~[server-intermediary.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:958) [server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:946) [server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:156) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.12-launcher.0.11.1.jar:0.11.1]
```

**Comment by TropheusJ** [comment] 2022-12-24 07:36
this should be fixed on the forge version too

**Comment by suerion** [comment] 2023-05-31 19:49
Would this be fixed? it is a long time, since the issue is here?

**Comment by suerion** [comment] 2023-06-04 11:41
i had only added the 4 files
https://github.com/Fabricators-of-Create/Create/pull/953 , don't know if it would work for you @TropheusJ (oonly for 1.19)

Should be Pushed to the forge project also?

**Comment by IThundxr** [comment] 2024-02-16 01:57
Doesnt occur anymore, 0.5.1f 1.19.2 fabric

**Closed as completed by IThundxr** 2024-02-16 01:57 UTC
Labels: type: bug, area: compatibility, type: upstream
