### ISSUE TITLE
Fluid Tanks

### ISSUE THREAD

**Issue by SchneckenFurz** [Fabricators-of-Create/Create#766] opened 2023-01-21 20:47 UTC
### Describe the Bug

When i try to fill fluid tanks wit fluid the game crashes

### Reproduction Steps

1. Build Fluid tank
2. Hook up pipes and pumps
3.  aktivate pumps

### Expected Result

Game freezes and crashes shortly after that

### Crash Report or Log

https://pastebin.com/4965UN8p

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

The Twilight Forest (by Benimatic)
Extra Classes - Origins (by proman468)
Item Borders [Fabric] (by Grend_G)
Indium (by comp500)
Trinkets (Fabric) (by EmilyPloszaj)
PokeBall (by Mirkiri)
Better Animals Plus (by cybercat5555)
PolyLib (by Official_CreeperHost)
Not Enough Crashes (Fabric) (by NatanFudge)
Create Fabric (by tropheusj)
Enchantment Descriptions (by DarkhaxDev)
Croptopia (by thethonk)
Iceberg [Fabric] (by Grend_G)
Roughly Enough Trades (by GrigLog)
Better Combat [Fabric & Forge] (by daedelus_dev)
CreatePlus (by Yjn024)
Spirit (by CodexAdrian)
Entity Culling Fabric/Forge (by tr9zw)
Tax Free Levels (Fabric/Forge) (by Fourmisain)
AppleSkin (by squeek502)
Continuity (by Pepper_Bell)
Clumps (by Jaredlll08)
Extra Origins (by MoriyaShiine)
WTHIT (by badasintended)
Farmer's Knives [Fabric] (by ianm1647)
When Dungeons Arise - Fabric! (by Aureljz)
Elytra Slot (Fabric) (by TheIllusiveC4)
Skilled Enchanting [Fabric] (by glitchifyed)
Connectivity[Forge/Fabric] (by someaddon)
Mouse Tweaks (by YaLTeR)
Sodium Extra (by FlashyReese)
Galosphere (by orcinus73)
Flytre Lib (FlytreLib) (by Flytre7)
Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)
Origins Extra Keybinds (by thatrobin3001)
Mod Menu (by ProspectorDev)
Feature NBT Deadlock Be Gone (by telepathicgrunt)
Roughly Enough Items Fabric/Forge (REI) (by shedaniel)
Create Crafts & Additions (by MRHminer)
Chunky (Fabric) (by pop4959)
Farmer's Delight [Fabric] (by NewHoryzon)
Roughly Enough Loot Tables (by GrigLog)
Controlling (by Jaredlll08)
Vein Mining (Fabric 1.16.4 - 1.19.2) (by TheIllusiveC4)
MegaParrot (by SkylorBeck)
Smooth Swapping (Fabric) (by Schauweg)
playerAnimator (by KosmX)
DashLoader (by notequalalpha)
Dark Utilities (by DarkhaxDev)
Visuality (by PinkGoosik)
Reese's Sodium Options (by FlashyReese)
Show Me What You Got (by Apace100)
Equipment Compare [Fabric] (by Grend_G)
CleanCut (by Rongmario)
Sodium (by jellysquid3_)
Locksmith (by moonflowerteam)
Effective 💦 (by doctor4t)
Immersive Armors [Fabric/Forge] (by Conczin)
AttributeFix (by DarkhaxDev)
Botany Pots (by DarkhaxDev)
Traveler's Backpack [Fabric] (by Tiviacz1337)
Fabric Language Kotlin (by modmuss50)
Zoomify (by XanderIsDev)
Macaw's Bridges (by sketch_macaw)
Xaero's World Map (by xaero96)
Smooth Boot (Fabric) (by UltimateBoomer)
Better Compatibility Checker (by Gaz_)
Fabric API (by modmuss50)
Runelic (by DarkhaxDev)
Neat (Fabric/Quilt) (by williewillus)
BetterF3 (by cominixo)
bad packets (by badasintended)
Item Highlighter [Fabric] (by Grend_G)
Ecologics (by SameDifferent)
Illuminations 🔥 (by doctor4t)
RPG Origins (by DaBananaCat)
Mythic Mounts (by chirpycricket__)
BCLib (by Quiqueck)
Enchantment Preservation (by TrueHooorse)
Biome Makeover (by Lemonszz)
Ring Of Teleport [FABRIC] (by kwpugh)
Skin Layers 3D (Fabric/Forge) (by tr9zw)
FerriteCore (Fabric) (by malte0811)
BetterNether (by Quiqueck)
Architectury API (Fabric/Forge) (by shedaniel)
GeckoLib (by ThanosGecko)
Iron Chests (Fabric) (by cyberanner)
Small Ships [Fabric & Forge] (by talhanation)
BetterEnd (by Quiqueck)
Pollen (by moonflowerteam)
Roughly Enough Professions (REP) (by Mrbysco)
The Bumblezone (Quilt/Fabric) (by telepathicgrunt)
Origins (Fabric) (by Apace100)
Modern Industrialization (by thetechnici4n)
Creeper Overhaul (by joosh_7889)
Cardinal Components (by UpcraftLP)
Artifacts (Fabric) (by florensie)
Iris Shaders (by coderbot)
UPC (by foopyfoopyfoopy)
MC Dungeons Weapons (by chronos_sacaria)
Better Third Person (by Socolio)
Bookshelf (by DarkhaxDev)
Incendium (by Starmute)
Industrial Revolution (by GabrielHOlv)
Cloth Config API (UNUSED) (by shedaniel)
Inventory Sorting (by Kyrptonaught)
Xaero's Minimap (by xaero96)
Structory (by botanydev)
SlotLock (by D4rkness_King)
Mob Origins (by UltrusBot)
Pig Pen Cipher (by DarkhaxDev)
MixinTrace (by comp500)
Patchouli (Fabric/Quilt) (by williewillus)
Mining Dimensions [FABRIC] (by kwpugh)
Lithium (Fabric) (by jellysquid3_)
CreativeCore (by CreativeMD)
Starlight (Fabric) (by Spottedstar)
Pipe (by Flytre7)
Reroll (by Draylar1)
Pehkui (by Virtuoel)
Roughly Enough Resources (by theorbagain)
Cloth Config API (Fabric/Forge) (by shedaniel)
Origins: Classes (by Apace100)

**Comment by TropheusJ** [comment] 2023-01-21 21:07
Duplicate of #759

**Closed as completed by TropheusJ** 2023-01-21 21:07 UTC
Labels: type: bug

**Comment by SchneckenFurz** [comment] 2023-01-22 09:48
> Duplicate of #759

Pipes and Pumps work for me when i try to fill up fluid tanks the Game crashes

**Comment by TropheusJ** [comment] 2023-01-22 09:49
It’s the same cause
