### ISSUE TITLE
Server crash when pumping lava into fluid tank

### ISSUE THREAD

**Issue by TygreWolf** [Fabricators-of-Create/Create#735] opened 2023-01-03 00:22 UTC
Set up a dripstone lava gen to start pumping lava into a fluid tank.  The server crashed as soon as it started pumping, and crashes each time I try to log back in.  Null Pointer Exception on ticking entity validating fluid type.

[crash-2023-01-02_19.13.10-server.txt](https://github.com/Fabricators-of-Create/Create/files/10333850/crash-2023-01-02_19.13.10-server.txt)

**Comment by TropheusJ** [comment] 2023-01-03 00:26
duplicate of #696, fixed in next update

**Closed as completed by TropheusJ** 2023-01-03 00:26 UTC
