### ISSUE TITLE
Improper rendering when using First-Person Model

### ISSUE THREAD

**Issue by Truemudkip** [Fabricators-of-Create/Create#1206] opened 2023-11-30 18:37 UTC
### Describe the Bug

Extendo Grip, Creative Worldshaper and Potato Cannon have their GUI model/view model rendering while using the First-Person Model mod, causing them to appear twice. Engineer's Goggles render while using First-Person Model, causing them to appear from first-person while using the first person model in certain contexts (most notably, looking down. There may be other situations i haven't observed where this happens)

### Reproduction Steps

1. Use Create and First Person Model together
2. Hold a Potato Cannon, Creative Worldshaper or Extendo Grip or equip a pair of Engineer's Goggles
3. Look downwards (or in other directions, haven't tried looking in other ways) for the Engineer's Goggles bug to occur; as mentioned before, the handheld items simply render as normal without disappearing when first-person model is active

### Expected Result

The expected result was no rendering of aforementioned elements while using First-Person Model

### Screenshots and Videos

![2023-11-30_17 26 14](https://github.com/Fabricators-of-Create/Create/assets/150826815/d142688c-12ba-4194-8b1f-0f36e9c9f6cf)
![2023-11-30_17 26 30](https://github.com/Fabricators-of-Create/Create/assets/150826815/ae01726a-4077-4c44-bbcf-52a67320c412)
![2023-11-30_17 26 50](https://github.com/Fabricators-of-Create/Create/assets/150826815/0d8c52ca-9a2f-4e08-9d7b-f898c70e2939)
![2023-11-30_17 26 51](https://github.com/Fabricators-of-Create/Create/assets/150826815/0bc2fb44-3687-497a-bd63-106dfa21a67d)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

First-Person Model, Create

**Comment by SUSmaster274329** [comment] 2023-12-28 13:47
Same issue here

**Comment by TropheusJ** [comment] 2024-02-03 04:31
duplicate of #905

**Closed as completed by TropheusJ** 2024-02-03 04:31 UTC
Labels: type: bug
