### ISSUE TITLE
Unloading chunks near rope pulley bugs lighting

### ISSUE THREAD

**Issue by FoxMaster198** [Fabricators-of-Create/Create#355] opened 2022-06-07 15:04 UTC
I have an elevator in my base on a server I host, and whenever the chunk with the elevator is unloaded, an almost 110-15 block radius from the rope pulley has all light removed. This area has the biggest torch spam in my history of playing Minecraft ever, and every time the elevator is unloaded, mobs start spawning due to a lack of light in that area. I don't know if this happens with any other create block, but I have not had this happen with other create blocks.

![2022-06-07_09 52 32](https://user-images.githubusercontent.com/99449334/172414666-171df67e-4a28-4b7d-bcb2-4140c3c31e0a.png)
![2022-06-07_09 52 38](https://user-images.githubusercontent.com/99449334/172414669-1af07d81-d392-43a4-928f-ab1db8ed0d4b.png)
![2022-06-07_09 53 30](https://user-images.githubusercontent.com/99449334/172414670-b41c0d81-9180-4a15-b781-02599b4f6379.png)
![2022-06-07_09 54 30](https://user-images.githubusercontent.com/99449334/172414671-1d2d992a-90ef-4477-b324-0732b247e731.png)
![2022-06-07_09 59 09](https://user-images.githubusercontent.com/99449334/172414675-04c329be-f735-4eff-8752-55e904a7d97b.png)

**Comment by FoxMaster198** [comment] 2022-06-07 15:26
I could have sworn there were more torches, just looking at my statistics... funny thing is I'm not even close to mob-proofing the full area around the base.

If you wanna message me, do so on Discord: FoxMaster198#5119
Also, I would absolutely LOVE to talk with one of the create mod devs and learn a bit about how they created this. Currently starting my career as a Software Developer and anything Code get me excited, especially if it has something to do with Minecraft. Thank you for making this awesome mod!

P.S. Potato Launcher + Chorus Fruit = OP

![2022-06-07_10 15 17](https://user-images.githubusercontent.com/99449334/172418375-a821ab02-b27f-420d-ac9e-b19a50e083c4.png)

**Comment by TropheusJ** [comment] 2022-06-07 15:46
Do you have redstone links there? Likely duplicate of #318

**Comment by FoxMaster198** [comment] 2022-06-07 18:13
I'm using redstone links in other contraptions, but they don't have the same effect on lighting on my server

**Comment by ardissaps** [comment] 2022-06-20 05:06
Same with me
https://github.com/Fabricators-of-Create/Create/issues/392

**Comment by ardissaps** [comment] 2022-06-20 05:08
> Same with me #392

I change and Phospor to Starlight and all fixed idk if it is actually the fix or not.

**Comment by TropheusJ** [comment] 2023-02-02 04:38
I haven't seen any other cases of this, it might've been an incompatibility of some kind. Closing, let's hope it doesn't come back.

**Closed as completed by TropheusJ** 2023-02-02 04:38 UTC
Labels: type: bug
