### ISSUE TITLE
REI+Create Fabric fluid issue

### ISSUE THREAD

**Issue by JieningYu** [Fabricators-of-Create/Create#279] opened 2022-05-07 06:58 UTC
### Describe the Bug

When using REI to check fluid's usage/recipe using "R" or "U", the recipe types from Create won't show. Other mods such as techreborn or modern industrialization will show so it can't be a REI issue.

### Reproduction Steps

1. Press 'R' on chocolate fluid on the REI panel.
2. Only spout filling has shown.

### Expected Result

Mixing Recipe of Chocolate should show properly.

### Operating System

macOS 12.2 Beta (21D5039d)

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

sodium
indium
REI
architectury
cloth config api
qsl

### Additional Context

Only Create mod has this issue. Fabric&Quilt all have this issue.

**Comment by AlphaMode** [comment] 2022-05-07 15:04
Duplicate of #121 this is a issue with REI I believe and has to be looked into by shedaniel

**Closed as completed by AlphaMode** 2022-05-07 15:04 UTC
Labels: type: bug
