### ISSUE TITLE
Crashing and mods fail to work correctly after changing language to Russian

### ISSUE THREAD

**Issue by riPepperonis** [Fabricators-of-Create/Create#901] opened 2023-04-26 00:34 UTC
### Describe the Bug

Hi. After changing the language in Minecraft from English to Russian, the game crashes with the error message. Additionally, after restarting the game in Russian, mods such as EMI and REI stop working correctly, with EMI giving a critical error ([link to error with EMI on clean minecraft with Create and EMI only](https://pastebin.com/2deaVGv9)) that prevents recipe display and REI's search function failing to work entirely.

### Reproduction Steps

1. Launch Minecraft and open the settings menu.
2. Change the language setting from English to Russian.
3. The game crashes with the error message.
4. Restart the game in Russian with the world loaded and try to use mods such as EMI and REI.
5. [EMI gives a critical error](https://pastebin.com/2deaVGv9) that prevents recipe display, and REI's search function fails to work entirely.

### Expected Result

After changing the language setting to Russian, the game should continue to run without crashing, and mods such as EMI and REI should continue to work correctly with no errors.

### Crash Report or Log

https://pastebin.com/4bbfB9pv

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

appliedenergistics2-fabric-12.9.3.jar
architectury-6.5.77-fabric.jar
badpackets-fabric-0.2.1.jar
balm-fabric-1.19.2-4.5.7.jar
bclib-2.1.6.jar
betteranimalsplus-1.19.2-11.0.10-fabric.jar
better-end-2.1.4.jar
botarium-fabric-1.19.2-1.8.2.jar
carrier-1.11.0.jar
cem-0.7.3-1.19.jar
chunksfadein-v3.0.11-1.19.jar
CITResewn-1.1.2+1.19.2.jar
collective-1.19.2-6.53.jar
continuity-2.0.2+1.19.jar
core-2.0.2+kt.1.8.20+flk.1.9.3.jar
create_crystal_clear-1.0+1.19.2.jar
createaddition-fabric+1.19.2-20230211a.jar
create-fabric-0.5.0.i-991+1.19.2.jar
CreaturesFromTheSnow-4.1.0+1.19.2.jar
creeperoverhaul-2.0.9-fabric.jar
doggo-mod-overhauled-1.0.2-1.19.2.jar
doubledoors-1.19.2-4.5.jar
dynamiccrosshair-5.3.1+1.19.2-fabric.jar
dynamiccrosshair-compat-3.3.1+1.19.2.jar
dynamic-fps-2.2.0.jar
DynamicSurroundings-RemasteredFabric-1.19-0.1.1.jar
EasyMagic-v4.3.3-1.19.2-Fabric.jar
effective-1.6+1.19.2.jar
emi_loot-0.6.1+1.19.jar
emi-0.7.3+1.19.2.jar
emicompat-2.0.3.jar
emiffect-0.1.5+mc1.19.2.jar
EMITrades-fabric-1.0.2+mc1.19.2.jar
enhancedblockentities-0.7.2+1.19.2.jar
entity_texture_features_fabric_1.19.2-4.3.3.jar
entityculling-fabric-1.6.1-mc1.19.2.jar
exordium-fabric-1.0.2-mc1.19.2.jar
expanded-armor-enchanting-1.0.3.jar
expanded-axe-enchanting-1.0.4.jar
expandedstorage-8.2.0-beta.3+1.19.2-quilt.jar
expanded-trident-enchanting-1.0.4.jar
expanded-weapon-enchanting-1.0.3.jar
extractinator-fabric-1.19.2-2.0.1.jar
FallingTree-1.19.2-3.10.0.jar
ferritecore-5.0.3-fabric.jar
ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar
forgetmechunk-1.0.4-1.18.X-1.19.X.jar
forgottengraves-1.19.2-3.0.5.jar
frame-0.26.1+1.19-fabric.jar
geckolib-fabric-1.19-3.1.40.jar
Highlighter-1.19.1-fabric-1.1.4.jar
Iceberg-1.19.1-fabric-1.0.46.jar
ijo-pona-poki-1.0.4.jar
ImmediatelyFast-1.1.12+1.19.jar
impaled-1.1.4.jar
indium-1.0.9+mc1.19.2.jar
InventoryProfilesNext-fabric-1.19-1.9.6.jar
iris-mc1.19.2-1.6.1.jar
item-model-fix-1.0.3+1.19.jar
krypton-0.2.1.jar
lambdynamiclights-2.2.0+1.19.2.jar
language-reload-1.5.6+1.19.2.jar.disabled
lazydfu-0.1.3.jar
letmedespawn-1.18.x-1.19.x-fabric-1.0.2.jar
libIPN-fabric-1.19-2.0.5.jar
lithium-fabric-mc1.19.2-0.11.1.jar
Log-Begone-Fabric-1.19.x-1.0.5.jar
lootr-1.19-0.4.25.64.jar
mcpitanlibarch-1.6.3-1.19.2-fabric.jar
megane-8.4.0.jar
memoryleakfix-fabric-1.17+-1.0.0.jar
midnightlib-quilt-1.0.0-patch1.jar
mixintrace-1.1.1+1.17.jar
modmenu-4.2.0-beta.2.jar
moreculling-1.19.1-0.17.0.jar
MouseTweaks-fabric-mc1.19-2.22.jar
naturalist-fabric-3.0.2-1.19.2.jar
netherportalfix-fabric-1.19-10.0.1.jar
notenoughanimations-fabric-1.6.2-mc1.19.2.jar
numeralping-1.1.0.jar
ok_zoomer-5.0.0-beta.9+1.19.jar
Patchouli-1.19.2-77-FABRIC.jar
PuzzlesLib-v4.4.0-1.19.2-Fabric.jar
qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar
quiltgoslightlyfasterlol-0.0.3.jar
quilt-kotlin-libraries-2.0.2+kt.1.8.20+flk.1.9.3.jar
RebornCore-5.4.0.jar
reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
resourcefulconfig-fabric-1.19.2-1.0.20.jar
resourcefullib-fabric-1.19.2-1.1.24.jar
rottencreatures-fabric-1.19.2-1.0.1.jar
RoughlyEnoughItems-9.1.595.jar.disabled
satin-1.9.0.jar
shulkerboxtooltip-fabric-3.2.2+1.19.2.jar
simply-no-shading-6.0.6+1.19.2.jar
Smooth Swapping 0.6 (1.19.2)-0.6.jar
smoothboot-fabric-1.19-1.7.1.jar
sodium-extra-0.4.16+mc1.19.2-build.90.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
sodium-shadowy-path-blocks-3.1.0.jar
soundphysics-fabric-1.19.2-1.0.18.jar
starlight-1.1.1+fabric.ae22326.jar
TechReborn-5.4.0.jar
TerraBlender-fabric-1.19.2-2.0.1.136.jar
tr-patchouli-2.1.1.jar
twigs-2.0.0-beta.9+1.19-fabric.jar
villagernames-1.19.2-5.2.jar
wthit-quilt-5.15.2.jar
wwoo-3.1.7+FABRIC+1.19.2.jar
YetAnotherConfigLib-2.2.0-for-1.19.2.jar
ad_astra-fabric-1.19.2-1.12.6.jar
AdvancedReborn-1.19.2-1.1.9.jar
AE2WTLib-12.8.5.jar
animatica-0.5+1.19.jar
antighost-1.19.1-fabric0.58.5-1.1.5.jar
appleskin-fabric-mc1.19-2.4.1.jar

**Comment by TropheusJ** [comment] 2023-04-26 00:56
duplicate of #851

**Closed as completed by TropheusJ** 2023-04-26 00:56 UTC
Labels: type: bug
