### ISSUE TITLE
Unexpected error crash when entering Overworld from the Nether

### ISSUE THREAD

**Issue by y2k04** [Fabricators-of-Create/Create#124] opened 2022-02-02 02:12 UTC
### Describe the Bug

By entering the nether portal to enter the Overworld, there are rendering issues with the overworld.

### Reproduction Steps

Unknown

### Expected Result

Expected to not crash lmao

### Crash Report or Log

https://pastebin.com/caTuBZVj

### Operating System

Windows 11

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

actuallyunbreaking: Actually Unbreaking 1.18-0.1.0
		amecsapi: Amecs API 1.3.3+mc1.18-pre1
		architectury: Architectury 3.0.39
		armorchroma: Armor Chroma 1.2.0
		automated_crafting: Automated Crafting 1.4.1+MC1.18-1.18.1
		beaconoverhaul: Beacon Overhaul 1.5.0+1.18
		betterbeds: Better Beds 1.2.0
		betterdroppeditems: Better Dropped Items 1.3.1-21w37a
		betterpingdisplay: Better Ping Display 1.1.1
		bettersafebed: BetterSafeBed 1.18-fabric-a
		blue_endless_jankson: jankson 1.2.1
		bowinfinityfix: Bow Infinity Fix rv11
		chesttracker: Chest Tracker 1.1.9
		cloth-api: Cloth API 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		coat: Coat 1.0.0-beta.15
		com_electronwill_night-config_core: core 3.6.5
		connected-doors: Connected Doors 1.1+1.18
		craftpresence: CraftPresence 1.8.8
		crawl: Crawl 0.10.0
		create: Create mc1.18.1_v0.4c
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cullleaves: Cull Leaves 2.3.2
		customwindowtitle: Custom Window Title 1.1.1
		damagetilt: Damage Tilt 1.18-fabric-0.1.2
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		discerning_furnace: Discerning Furnace 1.0.5+MC1.18-1.18.1
		drippyloadingscreen: Drippy Loading Screen 1.4.1
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		dsurround: §6Dynamic Surroundings§r: §eFabric Edition 0.0.4
		eatinganimationid: Eating Animation 1.2
		enchdesc: EnchantmentDescriptions 9.0.1
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.46.2+1.18
		fabricloader: Fabric Loader 0.12.12
		fabrictailor: Fabric Tailor 1.7.2
		fake-player-api: Fake Player API 0.3.0
		flywheel: Flywheel 1.18-0.6.0.16
		forge_tags: Forge Tags 1.5
		forgeconfigapiport: Forge Config API Port 3.1.0
		grindenchantments: Grind Enchantments 1.5.0+1.18
		here-be-no-dragons: Here be no Dragons! 1.0.0
		iris: Iris 1.2.0-pre
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kirin: Kirin UI 1.10.0-beta.2
		konkrete: Konkrete 1.3.0
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.3.0+1.17.1
		litematica: Litematica 0.0.0-dev.20211203.013300
		lithium: Lithium 0.7.6
		malilib: MaLiLib 0.10.0-dev.26
		mcf-easyfeed: Easy Feed and Breed 1.3.0
		midnightlib: MidnightLib 0.2.9
		milk: Milk Lib 0.1.6
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		modget: Modget 0.4.0+1.17
		modget-core: Modget Core 0.4.0
		modmenu: Mod Menu 3.0.0
		mousewheelie: Mouse Wheelie 1.8.0+mc1.18-pre5
		noexpensive: NoExpensive 1.18-Fabric-1.2.0
		notenoughanimations: NotEnoughAnimations 1.4.0
		notes: Notes 1.0.9
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		omega-config: OmegaConfig 1.0.8
		presencefootsteps: Presence Footsteps 1.4.0
		pride: Pride Lib 1.1.0+1.17
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		registrate-fabric: Registrate for Fabric MC1.18.1-1.0.7
		repurposed_structures: Repurposed Structures 3.1.3+1.18.0
		roughlyenoughitems: Roughly Enough Items 7.2.405
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5-beta.1+1.18-pre5
		shulkerutils: shulkerutils 1.0.4-1.18
		sit: Sit 1.18-14
		skinlayers: 3d Skin Layers 1.3.1
		sodium: Sodium 0.4.0-alpha6+build.14
		spruceui: SpruceUI 3.3.0+1.17
		tooltipfix: ToolTip Fix 1.0.4-1.18
		trampledisablerfabric: Trample Disabler 1.0.4
		umollu_ash: ASH - Another Simple HUD 1.1.16
		upgradedshulkers: Upgraded Shulkers 1.1.1-1.18
		voicechat: Simple Voice Chat 1.18.1-2.2.10
		whereisit: Where Is It 1.14.7

**Comment by TropheusJ** [comment] 2022-02-02 02:19
duplicate of #62

**Closed as completed by TropheusJ** 2022-02-02 02:19 UTC
Labels: type: bug
