### ISSUE TITLE
When entering the server, the player disconnects

### ISSUE THREAD

**Issue by XionioXMaster** [Fabricators-of-Create/Create#225] opened 2022-04-02 10:34 UTC
### Describe the Bug

When entering the server, the player disconnects, i used last Action Build 1.18.1

### Reproduction Steps

1. Put mod for server (not localhost)
2. Put mod client
3. Join to the server
...

### Expected Result

?

### Operating System

unbuntu 20

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment] 2022-04-02 20:44
Duplicate of #182

**Closed by TropheusJ** 2022-04-02 20:44 UTC
Labels: bug, 1.18
