### ISSUE TITLE
Server crash in create a train

### ISSUE THREAD

**Issue by HoiGe** [Fabricators-of-Create/Create#757] opened 2023-01-18 10:01 UTC
### Describe the Bug

When I press the done button of the following station after linking the train with glue, the server crashes.

### Reproduction Steps

1.Create a train
2.Use the funnel as part of the body
3.Click finish in the station

### Expected Result

I want to create a train

### Crash Report or Log

Log https://pastebin.com/gWpuJxPw / Crash report https://pastebin.com/KHu3K6Fx

### Operating System

MacOS 13.1

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

- starlight-1.1.1+fabric.ae22326
- otyacraftengine-fabric-mc1.19.2-3.2.0
- minimotd-fabric-mc1.19.2-2.0.9
- lithium-fabric-mc1.19.2-0.10.4
- lazydfu-0.1.3
- iammusicplayer-fabric-mc1.19.2-3.19.4
- ferritecore-5.0.3-fabric
- fabric-carpet-1.19.2-1.4.84+v221018
- fabric-api-0.70.0+1.19.2
- cloth-config-8.2.88-fabric
- architectury-6.3.56-fabric

**Comment by TropheusJ** [comment] 2023-01-18 13:33
duplicate of #503
wait for next update or remove minimotd

**Closed as completed by TropheusJ** 2023-01-18 13:33 UTC
Labels: type: bug

**Comment by itsdinkd** [comment] 2023-04-27 19:24
> duplicate of #503 wait for next update or remove minimotd

is it safe to add back now?
