### ISSUE TITLE
Not compatible with the latest Sodium version

### ISSUE THREAD

**Issue by Edoliviro** [Fabricators-of-Create/Create#1093] opened 2023-09-02 17:33 UTC
### Describe the Bug

The game crashes before opening

### Reproduction Steps

Open the game with create 1.20.1 and Sodium 0.5.2 installed

### Expected Result

The title screen :)

### Screenshots and Videos

![The issue](https://github.com/Fabricators-of-Create/Create/assets/94635465/17db5698-d18e-4386-9a9c-17975362174c)

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Sodium 0.5.2

**Comment by AlphaMode** [comment] 2023-09-02 17:38
Duplicate of #1039

**Closed as completed by AlphaMode** 2023-09-02 17:38 UTC
Labels: type: bug
