### ISSUE TITLE
Chutes not grabbing logs from belt

### ISSUE THREAD

**Issue by Papaturts** [Fabricators-of-Create/Create#244] opened 2022-04-12 18:34 UTC
### Describe the Bug

Ran a belt above chutes to feed furnaces with logs
chutes are not pulling logs off the belt/neither are hoppers
belts are unable to trasnfer items to chutes as well
Mechanical arms not able to pull items off belts

### Reproduction Steps

1.use a belt to move logs from chest
2.try to get logs from belt with chutes to transfer to furnaces
3.
...

### Expected Result

chutes to logs from belts to furnace

### Screenshots and Videos

![2022-04-12_13 31 48](https://user-images.githubusercontent.com/97408568/163029894-bac3f04c-7b58-4c5e-85b1-be8d20a475ea.png)

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

latest build
#500

**Comment by JieningYu** [comment] 2022-04-14 10:41
from your screenshot, the chutes seems not placed directly under the belt.
Also test this machine in Forge.

**Comment by Papaturts** [comment] 2022-04-14 11:50
They are directly beneath
Also this machine works flawlessly in forge 1.18.2-had the same idea to try there as well, to make sure i didnt mess something up or something going on
![2022-04-14_06 49 41](https://user-images.githubusercontent.com/97408568/163384867-d4282a1d-dd66-44d2-b4c0-03ca36444d62.png)

**Comment by TropheusJ** [comment] 2022-04-14 11:51
In testing I discovered this is caused by a much deeper issue: somehow only some of the block entities of the belt are ticking.

**Comment by Papaturts** [comment] 2022-04-14 11:57
tried chutes, smart chutes and hoppers, all fail, just came across another issue as well
items arent getting placed onto depots from chutes below-they are dissapearing instead

**Comment by TropheusJ** [comment] 2022-04-28 02:55
after WAY too much debugging, this is a lithium incompat.

**Comment by TropheusJ** [comment] 2022-04-28 04:46
After more debugging, it turns out it’s not.

**Comment by Papaturts** [comment] 2022-04-28 06:21
That narly of a bug huh?
Dang

**Comment by TropheusJ** [comment] 2022-04-28 20:52
I was lucky enough to misclick on the forge github feed and found [this issue](https://github.com/Creators-of-Create/Create/issues/2968). Will need to be fixed by upstream.

**Comment by TropheusJ** [comment] 2022-05-10 20:16
reopening this just too keep track of it

**Comment by Papaturts** [comment] 2022-05-11 04:18
I was wondering how this was coming along

**Comment by TropheusJ** [comment] 2022-05-23 14:13
[Will be resolved in 0.5.](https://github.com/Creators-of-Create/Create/pull/3038#issuecomment-1133912904)

**Comment by Seon82** [comment] 2022-05-31 17:35
I'm running into the same issue, but it's with all belts (not only those broken and rebuilt) and isn't fixed on relog. Is that expected behaviour?

**Comment by TropheusJ** [comment] 2022-07-09 01:07
This should now be fixed, a 0.5 fabric/quilt version is hopefully not too far out.

**Closed as completed by TropheusJ** 2022-07-09 01:07 UTC
Labels: type: bug, type: upstream

**Comment by Papaturts** [comment] 2022-07-09 01:56
Alrighty, looking foward to it
currently have a server running-just basically getting started yet
