### ISSUE TITLE
Game crashes due to contraption

### ISSUE THREAD

**Issue by SFort** [Fabricators-of-Create/Create#1166] opened 2023-10-21 09:22 UTC
### Describe the Bug

Actually running [create sodium fix](https://github.com/Treetrain1/Create) i'm just assuming it's not related.

Server crashed while one player was online, probably caused by the contraption in the screenshot since the contraption used to be a double chest, not two seperate chests. 
It duped the items it's made of and it's contents.
The player was far away from the contraption.

![2023-10-21_11 02 59](https://github.com/Fabricators-of-Create/Create/assets/1879846/92550eab-8a4a-423a-8595-c9d89eac6b80)

### Crash Report or Log

https://pastebin.com/niZmX0JK

### Operating System

Linux

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by drwoops** [comment] 2023-10-21 10:39
downgrade fabric api to 0.88.1

**Comment by ARitz-Cracker** [comment] 2023-10-25 22:41
Seems to me this relates to #1134 #1038 #1080

**Comment by TropheusJ** [comment] 2023-12-18 03:58
duplicate of #1080

**Closed as completed by TropheusJ** 2023-12-18 03:58 UTC
Labels: type: bug
