### ISSUE TITLE
Game crashes when a deployer kills a mob

### ISSUE THREAD

**Issue by putte86** [Fabricators-of-Create/Create#1227] opened 2023-12-18 19:48 UTC
### Describe the Bug

i built a blaze farm, the blaze lands infront of a deployer which attacks the blaze with a dieamond sword. when the blaze dies, the game crashes

### Reproduction Steps

1.put a mob infront of a deployer
2.right click deployer with a wrench to put it on attack mode
3.give the deployer a diamond sword
4. poweer the deployer
5. wait for the mob to die

### Expected Result

i expected the game not to crash as i assume this is the intendet feuture of having a deployer attack a mob

### Crash Report or Log

Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "capturedDrops" is null
	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activateInner(DeployerHandler.java:207)
	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activate(DeployerHandler.java:134)
	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.activate(DeployerBlockEntity.java:358)
	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.tick(DeployerBlockEntity.java:244)
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)

### Operating System

windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Create Crafts & Additions, AE2

**Comment by drwoops** [comment] 2023-12-18 19:51
duplicate of #1096

**Closed as completed** 2023-12-18 20:49 UTC
Labels: type: bug
