### ISSUE TITLE
Deployers causing server crash on 1.19.2

### ISSUE THREAD

**Issue by Spider987** [Fabricators-of-Create/Create#703] opened 2022-12-25 22:03 UTC
### Describe the Bug

A player on my mc server is using a deployer, which causes the server to crash. Everytime the chunk is loaded, the server crashes, meaning they can't log in.

### Reproduction Steps

1. Player logs in
2. Deployer loads
3.Server crashes
...

### Expected Result

Server does not crash

### Crash Report or Log

https://pastebin.com/VYxBh0LQ

### Operating System

Server provider doesn't provide info

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

[BackpackKingdomsRiptidev1.zip](https://github.com/Fabricators-of-Create/Create/files/10300679/BackpackKingdomsRiptidev1.zip)

**Comment by TropheusJ** [comment] 2022-12-25 22:26
Duplicate of #503

**Closed as completed by TropheusJ** 2022-12-25 22:26 UTC
Labels: type: bug
