### ISSUE TITLE
Filter's are not being respected on Smart chutes

### ISSUE THREAD

**Issue by Fade-Alchemist** [Fabricators-of-Create/Create#1506] opened 2024-05-27 17:20 UTC
### Describe the Bug

Before the most recent update, If I had an empty mana tablet set in a basic filter and told it to respect data, it would not allow full mana tablets to pass (expected behavior) Now Full tablets are being allowed to pass.

### Reproduction Steps

1. Set basic filter on smart chute to empty mana tablet
2. Get sad when nonempty tablets are allowed through. 
3.
...
 

### Expected Result

Only tablets of the indicated fill level are allowed to pass (as was the past behavior)

### Screenshots and Videos

![Image1](https://github.com/Fabricators-of-Create/Create/assets/29619427/010f1ce6-8d80-4086-acc4-0ae4161b8fe6)
![Image2](https://github.com/Fabricators-of-Create/Create/assets/29619427/37f3cdca-8f0a-4542-a33d-85ce790145ca)

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.19.2

**Comment by VoidLeech** [comment] 2024-05-27 17:29
Duplicate of #5780

**Closed as not planned** 2024-05-27 17:30 UTC
Labels: type: bug
