### ISSUE TITLE
Incorrect textures for belts and chests not rendering correctly (possible problem with amd graphics cards)

### ISSUE THREAD

**Issue by Squ-Cog** [Fabricators-of-Create/Create#1328] opened 2024-02-19 20:51 UTC
### Describe the Bug

When using the latest version of create fabric on 1.20.1, belts and chests don't render correctly.
When turning off flywheel the issue is resolved. I would post the bug there but the github page is described as (legacy) so I'm not sure if that is the correct place.

### Reproduction Steps

1. Use the latest version of fabric api and create fabric on 1.20.1
2. Place a belt or a chest
3. Rotate the belts
...

### Expected Result

[latest.log](https://github.com/Fabricators-of-Create/Create/files/14336731/latest.log)

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/60276291/67811727-2652-4cd3-b35b-612e2883b301

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Fabric API 0.92.0+1.20.1

### Additional Context

Other friends that don't have a AMD graphics card don't have this problem, but other friends with one do.

**Comment by TropheusJ** [comment] 2024-02-19 21:03
Please get an F3 screenshot from everyone experiencing the problem.

**Comment by Squ-Cog** [comment] 2024-02-19 21:09
![2024-02-19_22 07 39](https://github.com/Fabricators-of-Create/Create/assets/60276291/fc66a06f-4a7d-401d-a43c-3bc1b5aacbbd)

here's is mine

**Comment by Squ-Cog** [comment] 2024-02-19 21:33
and my friends:
![2024-02-19_22 30 49](https://github.com/Fabricators-of-Create/Create/assets/60276291/4ac0fb3c-caff-4151-a99e-21a1b7a0f78a)

![image](https://github.com/Fabricators-of-Create/Create/assets/60276291/bebd0479-5351-4401-b75d-e1755fe90e0a)


and an example without the bug, (on nvidea)
![image](https://github.com/Fabricators-of-Create/Create/assets/60276291/dd80eaa3-ea33-4e3a-ba0e-c8f4801b0d96)

**Comment by NolanHewitt** [comment] 2024-02-22 10:28
Did this start with the recent driver updates? Same thing happened for me on a 7900XTX with the 24.1.1 drivers, a bunch of other games had graphical issues as well.

**Comment by Squ-Cog** [comment] 2024-03-28 00:30
I don't know if it is related to this bug but I'm also getting a regular crash when placing belts and tracks.
[crash-2024-03-27_23.33.22-client.txt](https://github.com/Fabricators-of-Create/Create/files/14782509/crash-2024-03-27_23.33.22-client.txt)
[latest.log](https://github.com/Fabricators-of-Create/Create/files/14782518/latest.log)

**Comment by Squ-Cog** [comment] 2024-03-28 14:47
I'm also encountering a crash to might be related:
[crash-2024-03-28_15.45.18-client.txt](https://github.com/Fabricators-of-Create/Create/files/14791298/crash-2024-03-28_15.45.18-client.txt)
[latest.log](https://github.com/Fabricators-of-Create/Create/files/14791301/latest.log)

**Comment by IThundxr** [comment] 2024-03-28 14:49
> I'm also encountering a crash to might be related: [crash-2024-03-28_15.45.18-client.txt](https://github.com/Fabricators-of-Create/Create/files/14791298/crash-2024-03-28_15.45.18-client.txt) [latest.log](https://github.com/Fabricators-of-Create/Create/files/14791301/latest.log)

Removed sound physics remastered, it's incompatible with create due to calling non thread safe code off thread

**Comment by SirNoods** [comment] 2024-04-16 07:40
> Did this start with the recent driver updates? Same thing happened for me on a 7900XTX with the 24.1.1 drivers, a bunch of other games had graphical issues as well.

Downgrading my AMD Driver to 23.12.1 helped on a 6650XT

**Comment by Mettwasser** [comment] 2024-04-19 15:45
> Did this start with the recent driver updates? Same thing happened for me on a 7900XTX with the 24.1.1 drivers, a bunch of other games had graphical issues as well.

Yup, exact same thing here. Probably the cause.

**Comment by 209jkjkjk** [comment] 2024-04-23 14:25
same problem RX7800XT
use /flywheel backend batching workaround
![image](https://github.com/Fabricators-of-Create/Create/assets/74671686/3dd4b999-f869-468d-adc1-787145243355)
![image](https://github.com/Fabricators-of-Create/Create/assets/74671686/e72d8e6c-26dc-48b5-a5ab-8917d382bfe7)

**Comment by NolanHewitt** [comment] 2024-07-18 06:42
Any update on if this will be fixed?

**Comment by IThundxr** [comment] 2024-09-30 01:57
Caused by the AMD driver, either downgrade it, or wait for 0.5.2.

**Closed as completed by IThundxr** 2024-09-30 01:57 UTC
Labels: type: bug
