### ISSUE TITLE
Deployer crashes Fabric server

### ISSUE THREAD

**Issue by sall0-0p** [Fabricators-of-Create/Create#485] opened 2022-08-03 08:40 UTC
### Describe the Bug

It just crashes server. When I launch it again, it crashes again.

### Reproduction Steps
1. Have fabric server + Velocity
2. 3. Place deployer
4. CRAAASH
...

### Expected Result

it do not crash

### Crash Report or Log

https://pastebin.com/L6MFNKK7

### Operating System

MacOSX

### Mod Version

0.5.0

### Minecraft Version

1.18.2

### Other Mods

Stated in crash report

**Comment by TropheusJ** [comment] 2022-08-03 09:24
Duplicate of #117

**Closed as completed by TropheusJ** 2022-08-03 09:24 UTC
Labels: type: bug
