### ISSUE TITLE
Trying to load Create with Shetiphiancore causes the loader to get stuck

### ISSUE THREAD

**Issue by Tempest-5ky** [Fabricators-of-Create/Create#505] opened 2022-08-08 23:54 UTC
### Describe the Bug

Trying to load Create 5.0 alongside Shetiphiancore (https://www.curseforge.com/minecraft/mc-mods/shetiphiancore-fabric) causes the game to get stuck approx. halfway through the loading process. No crash, like others have been reporting, it just gets stuck.
No log errors or anything of the sort.

This only happens on the client, if both mods are put on the server it loads with no issue.

### Reproduction Steps

1. Install Create Fabric and Shetiphiancore
2. Try to load minecraft
3. Observe
...

### Expected Result

Minecraft loads as usual. Removing Shetiphiancore allows this to happen, but unfortunately it's a mod that several of our server's mods depend on and cannot be removed without causing serious issues due to blocks from said mods being used in most builds.

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment] 2022-08-09 00:35
Duplicate of #452

**Closed as completed by TropheusJ** 2022-08-09 00:35 UTC
Labels: type: bug
