### ISSUE TITLE
Twigs Mod + Frame API + Create Fabric 1.19.2 = crashing game.

### ISSUE THREAD

**Issue by MrJorman** [Fabricators-of-Create/Create#780] opened 2023-01-28 05:48 UTC
### Describe the Bug

When I try to view information about the mechanism, the game crashes.
[crash-2023-01-20_17.53.43-client (3).txt](https://github.com/Fabricators-of-Create/Create/files/10526045/crash-2023-01-20_17.53.43-client.3.txt)

### Reproduction Steps

When I try to view information about the mechanism, the game crashes.

### Expected Result

When I try to view information about the mechanism, the game crashes.

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Twigs
Frame API
Create

**Comment by SplendidAlakey** [comment] 2023-01-29 16:27
Duplicate of #655 

https://github.com/moddingplayground/frame-fabric/issues/6

**Closed as not planned** 2024-08-24 16:56 UTC
Labels: type: bug
