### ISSUE TITLE
Compatibility issues at least for me

### ISSUE THREAD

**Issue by NetunooOG** [Fabricators-of-Create/Create#879] opened 2023-04-06 13:49 UTC
### Describe the Bug

Cant make it past the launcher with the new patch 989 with twilight forest installed 

### Reproduction Steps

1.Have both mods 
2.Try launch fabric 1.19.2
3.Crash
...

### Expected Result

It will swap between saying conflict Twilight forest/Create

### Crash Report or Log

https://pastebin.com/cLns5Mew

### Operating System

W10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Have a huge mod pack personal constructed but can recreate with no mods like with out twilight forest but I think your aware of that already. With TF it conflicts

**Comment by TropheusJ** [comment] 2023-04-06 19:09
duplicate of #845

**Closed as completed by TropheusJ** 2023-04-06 19:09 UTC
Labels: type: bug
