### ISSUE TITLE
Crash during scrolling through creative in front of a chute. Ticking Block Entity.

### ISSUE THREAD

**Issue by Aquaeyes** [Fabricators-of-Create/Create#702] opened 2022-12-25 15:56 UTC
### Describe the Bug

Game hard crashed when putting chutes above and below a vault.

### Reproduction Steps

1. Have chute in hotbar
2. Have chute pointing into item vault on top, chute pointing out of item vault on bottom, have lever placed next to chute on bottom.
3. Search creative inventory for dark oak planks.
... Unable to reproduce after initial bug found.

### Expected Result

For the game not to crash when seemingly unrelated to the actions being undertaken. No items present in vault during the crash either.

### Screenshots and Videos

![Uploading image.png…]()

### Crash Report or Log

[crash-2022-12-25_23.37.33-server.txt](https://github.com/Fabricators-of-Create/Create/files/10300259/crash-2022-12-25_23.37.33-server.txt)

### Operating System

M1 Mac OS

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

architectury-6.4.62-fabric
autotag-2.0.0+1.19
botarium-fabric-1.19.2-1.8.0
charm-fabric-1.19.2-4.4.4
charmonium-fabric-1.19.2-4.2.1
cloth-config-8.2.88-fabric
create-fabric-0.5.0g-796+1.19.2
CreativeCore_FABRIC_v2.9.3_mc1.19.2
dataattributes-1.2.8
emi-0.5.3+1.19.2
everycomp-1.19.2-2.1.6
geckolib-quilt-1.19-3.1.40
modelfix-1.3-universal
modmenu-4.1.2
moonlight-1.19.2-2.1.20-fabric
nbtcrafting-2.2.3+mc1.19
owo-lib-0.9.3+1.19
Patchouli-1.19.2-77-FABRIC
qfapi-4.0.0-beta.25_qsl-3.0.0-beta.24_fapi-0.70.0_mc-1.19.2
resourcefulconfig-fabric-1.19.2-1.0.17
resourcefullib-fabric-1.19.2-1.1.17
wraith-alloy-forgery-2.0.17+1.19

### Additional Context

[2022-12-25-7.log](https://github.com/Fabricators-of-Create/Create/files/10300265/2022-12-25-7.log)

**Comment by TropheusJ** [comment] 2022-12-25 18:50
does it happen again if you reopen the world?

**Comment by Aquaeyes** [comment] 2022-12-26 01:20
It does not, no. I'm going to be trying to reproduce it again now.

**Comment by TropheusJ** [comment] 2022-12-26 06:10
unlikely you'll be able to.
This crash is caused by the item being null, *after* a check that should guarantee it's not null.
This is usually an indicator of item stacks being modified off-thread. 
There's no real way to fix it.

**Comment by TropheusJ** [comment] 2023-02-02 02:42
This has been fixed by FAPI

**Closed as completed by TropheusJ** 2023-02-02 02:42 UTC
Labels: type: bug
