### ISSUE TITLE
Minecraft crashes while using Ponder due to Lithium

### ISSUE THREAD

**Issue by aunrea** [Fabricators-of-Create/Create#839] opened 2023-03-11 16:14 UTC
### Describe the Bug

When I ponder an item Minecraft will crash with the following message:

> The game crashed whilst ticking screen
> Error: java.lang.ClassCastException: class com.simibubi.create.foundation.ponder.PonderWorld cannot be cast to class net.minecraft.class_2791 (com.simibubi.create.foundation.ponder.PonderWorld and net.minecraft.class_2791 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @69b794e2)

### Reproduction Steps

1. Ponder an item
2. During animation it will crash

### Expected Result

Watch ponder animation all the way through without Minecraft crashing.

### Crash Report or Log

https://gist.github.com/aunrea/6275a8588337789329477732f1d1ad72

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

- Chat Heads 0.10.5
- Head Index 1.0.9
- ReplayMod 2.6.10
- Spark 1.9.45
- Frame API 0.26.1
- Architectury 6.5.69
- AudioPlayer 1.4.5
- Cloth Config 8.2.88
- CorgiLib 1.0.0.32
- Decorative Blocks 3.0.0
- Essentials Commands 0.30.0
- Frabic API 0.75.1
- Fabric Waystones 3.0.7
- GeckoLib 3.1.40
- Indium 1.0.9
- Iris Shaders 1.5.2
- LambDynamicLights 2.2.0
- Light Overlay 7.0.0
- Lithium 0.11.0
- Mod Menu 4.1.2
- OwoLib 0.9.3
- Phosphor 0.8.1
- Simple Backpack 1.3.25
- Simple Voice Chat 2.3.28
- Sodium 0.4.4+Build.18
- Twigs 2.0.0
- WorldEdit 7.2.12
- Xaero's MiniMap 23.2.0
- Xaero's World Map 1.29.2

### Additional Context

This is installed on a Farbic server hosted by Apex Hosting with 4GB ram. On the server I have the following mods installed (all fabric versions):

- Architectury 6.5.69
- AudioPlayer 1.4.5
- Chat Heads 0.10.5
- Cloth Config 8.2.88
- CorgiLib 1.0.0.32
- Create Fabric 0.5.0.i
- Decorative Blocks 3.0.0
- Essentials Commands 0.30.0
- Fabric API 0.75.1
- Frame 0.26
- Geckolib 3.1.40
- HeadIndex 1.0.9
- Lithium 0.11.0
- LuckPerms 5.4.64
- MCDiscordChat 2.1.2
- MiniMOTD 2.0.9
- Multiworld 1.6
- OwoLib 0.9.3
- Phosphor 0.8.1
- RoughlyEnoughItems 9.1.591
- Sodium 0.4.4+build.18
- Spark 1.9.45
- Status 1.0.0
- Twigs 2.0.0-beta.9
- VoiceChat 2.3.28
- WorldEdit 7.2.12
- Fabric Waystones 3.0.7

**Comment by goldstargloww** [comment] 2023-03-12 01:01
same issue here
[crash-2023-03-11_19.55.02-client.txt](https://github.com/Fabricators-of-Create/Create/files/10949768/crash-2023-03-11_19.55.02-client.txt)
[crash-2023-03-11_19.50.04-client.txt](https://github.com/Fabricators-of-Create/Create/files/10949769/crash-2023-03-11_19.50.04-client.txt)
two different crash reports from the same error

**Comment by ryan-griffin** [comment] 2023-03-13 03:24
I have identified the cause to be lithium. Try removing it for now and see if that fixes it. A specific optimization can probably be disabled in the config, but I don't know what that would be.

**Comment by TropheusJ** [comment] 2023-03-13 04:18
issue forwarded to lithium: https://github.com/CaffeineMC/lithium-fabric/issues/455

**Comment by TropheusJ** [comment] 2023-03-26 07:12
fixed by lithium 0.11.1

**Closed as completed by TropheusJ** 2023-03-26 07:12 UTC
Labels: type: bug, area: compatibility
