### ISSUE TITLE
Deployer causes crash on dedicated server

### ISSUE THREAD

**Issue by Oliver-makes-code** [Fabricators-of-Create/Create#210] opened 2022-03-16 22:45 UTC
### Describe the Bug

Placing a deployer causes a crash on dedicated server

### Reproduction Steps

1. install mods
2. place deployer
3. crash

### Expected Result

It doesn't crash

### Crash Report or Log

https://pastebin.com/Y6wDbEfq

### Operating System

Windows 11

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

		adorn: Adorn 3.3.1+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		adventure-platform-fabric: adventure-platform-fabric 5.0.0-SNAPSHOT
		alloy_forgery: Alloy Forgery 2.0.9+1.18
		apoli: Apoli 2.2.2
		architectury: Architectury 3.7.31
		aurorasdeco: Aurora's Decorations 1.0.0+1.18
		autoconfig1u: Auto Config v1 Updated 3.4.0
		automated_crafting: Automated Crafting 1.4.3-a1
		bannerpp: Banner++ 2.0.4+mc.1.18-rc4
		blockbot-api: BlockBot Api 1.0.0
		blockbot-discord: BlockBot Discord 2.0.0-beta
		blue_endless_jankson: jankson 1.2.1
		boat_step_up: Boat Step Up 1.2.1
		calio: Calio 1.4.2
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		carpet: Carpet Mod 1.4.57
		carpet-fixes: Carpet Fixes 1.18.x-1.7.1+v220311
		carpet-shadow: Carpet Shadow 1.9.4-MC1.18+
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		clumps: Clumps 8.0.0+5
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_github_llamalad7_mixinextras: MixinExtras 0.0.6
		com_google_code_findbugs_jsr305: jsr305 3.0.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		conditional-mixin: conditional mixin 0.1.5
		copper_pipe: Simple Copper Pipes r1.9
		create: Create mc1.18.1_v0.4d+441
		crowdin-translate: CrowdinTranslate 1.4+1.18
		deepslatecutting: Deepslate Cutting 1.3.1
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		dynmap: Dynmap 3.3.2
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		entitybanners: Entity Banners 1.0.2-BETA+1.18
		extension: Extension 1.5+1.18
		extraorigins: Extra Origins 1.18-9
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.3+d7c144a8d2
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 1.0.0+3fec4ad9c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabricloader: Fabric Loader 0.13.3
		fake-player-api: Fake Player API 0.3.0
		ferritecore: FerriteCore 4.1.2
		fiber: fiber 0.23.0-2
		forge_tags: Forge Tags 2.0
		forgeconfigapiport: Forge Config API Port 3.1.0
		gud_asm: gudASM 0.3.0
		horseinboat: HorseInBoat fabric-1.1.1
		infinitevillagertrading: InfiniteVillagerTrading 1.18-fabric0.43.1-1.1
		invview: InvView 1.4.8-1.18+
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		krypton: Krypton 0.1.6
		ksyxis: Ksyxis 1.1
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.2.0+1.18
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.7
		maybe-more-data: Maybe More Data 1.0.0-1.18.1
		medievalorigins: Medieval Origins 1.18.x-3.3.1
		microconfig: Microconfig 2.1.2
		milk: Milk Lib 0.1.6
		minecraft: Minecraft 1.18.1
		moborigins: Mob Origins 1.8.0
		morevillagers-fabric: MoreVillagersFabric 3.1.1-SNAPSHOT
		net_kjp12_hachimitsu_utilities_: utilities 0.0.0
		net_kyori_adventure-api: adventure-api 4.9.3
		net_kyori_adventure-key: adventure-key 4.9.3
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.9.3
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.9.3
		net_kyori_examination-api: examination-api 1.3.0
		net_kyori_examination-string: examination-string 1.3.0
		op-fortune: OP Fortune 1.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		origins: Origins 1.3.1
		origins-classes: Origins: Classes 1.2.4
		owo: oωo 0.5.2+1.18
		patchouli: Patchouli 1.18.1-65-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		phonos: Phonos 0.2+1.18
		phosphor: Phosphor 0.8.1
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.3.0
		playerless: playerless final
		plymouth-anti-xray: Plymouth: Anti-Xray 0.0.0-rc.4+mc.1.18.1
		quilt_base: Quilt Base API 1.0.0+1.18-SNAPSHOT
		quilt_block_extensions: Quilt Block Extensions API 1.0.0+1.18-SNAPSHOT
		raknet-fabric: RaknetFabric 0.1.0+alpha.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		recipecache: recipecache 0.2.1-1.17.1
		registrate-fabric: Registrate for Fabric MC1.18.1-1.0.7
		roughlyenoughitems: Roughly Enough Items 7.3.443
		servercore: ServerCore 1.2.7-1.18.1
		servshred: ServShred 1.0.7
		sgui: sgui 1.0.0-rc6+1.18-pre5
		sidebar-api: Sidebar API 0.1.0+1.18
		taxfreelevels: Tax Free Levels 1.2.1
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		trinkets: Trinkets 3.2.0
		twigs: Twigs 1.1.2
		victus: Victus 0.1.7+1.18
		villager_see_villager_do: Villager See, Villager Do 1.1.3+MC1.18-1.18.1
		vmp: Very Many Players 0.2.0+beta.3.8

### Additional Context

I can't play on my server until its fixed

**Comment by TropheusJ** [comment] 2022-03-16 22:49
duplicate of #117

**Closed as completed by TropheusJ** 2022-03-16 22:49 UTC
Labels: type: bug
