### ISSUE TITLE
the shield can't prevent the debuff caused by mobs

### ISSUE THREAD

**Issue by Clock-Paradox** [Fabricators-of-Create/Create#1117] opened 2023-09-17 04:13 UTC
### Describe the Bug

when i went into the fortress to kill the blaze, i found i can use the shield to prevent the danmage caused by their fireball but i was in fire. so did the wither skeleton. i didn't harm by its sword but i get wither. also,when skeleton hit me. i won't get any danmage but i was knocked back. i test in vanilla and the shield worked well.

### Reproduction Steps

1.just place a blaze and arm a shield
2.right click
3.you are in fire

### Expected Result

just make the shield work properly.

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/145242844/e67dd652-6600-49b3-9b1e-3018b472147d

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/145242844/4cb8abcd-84ed-4c93-a648-8b057220c619)

**Comment by ady4398** [comment] 2023-09-23 12:48
Confirmed in my testing. 
i compared how the shield work between fully vanilla client and with only Create fabric installed

in fact, not just blaze
it seems that shield only block damage, but does not block any effect that comes with that damage, like knockback from skeleton arrow, knockback from zombie hit, blaze fire, shulker levitation, etc.
And the weirdest of them all being, if you block a creeper explosion while jumping backwards, you got knocked FORWARD as if the explosion comes from the back.

making shield completely useless imo, and making raiding fortress harder than it should be

**Comment by drwoops** [comment] 2023-09-23 12:51
it would be interesting to test with a fabric instance with no mods, just to see if it might be caused by fabric itself.

**Comment by ady4398** [comment] 2023-09-23 15:56
Retested with just fabric loader 0.14.22 without any mods installed

And shield behave as expected just like in vanilla

**Comment by Clock-Paradox** [comment] 2023-09-24 08:11
> Retested with just fabric loader 0.14.22 without any mods installed
> 
> And shield behave as expected just like in vanilla

so it means this is a bug caused by Create and needs to be solved? :)

**Comment by Clock-Paradox** [comment] 2023-09-24 08:18
> it would be interesting to test with a fabric instance with no mods, just to see if it might be caused by fabric itself.

i use these mods except Create to test and the shield works well.

**Comment by TropheusJ** [comment] 2024-02-14 08:00
this should be fixed on patch f

**Closed as completed by TropheusJ** 2024-02-14 08:00 UTC
Labels: type: bug
