### ISSUE TITLE
Contraption entitiy invisible when running

### ISSUE THREAD

**Issue by Helios21cz** [Fabricators-of-Create/Create#247] opened 2022-04-15 21:42 UTC
### Describe the Bug

When starting a Windmill, sails attached to windmill bearing turns invisible and at same time ghost of sails stick to my cursor (hard to describe, check the video link I sent). It stays in this state until I right-click same Windmill. I haven't checked behaviour with multiple complete Windmills, I have only one... clicking another empty Windmill bearing didn't change anything.

### Reproduction Steps

1. Start Windmill
2. See the magic
3. Stop Windmill to get things back to normal.
...

### Expected Result

Sails stays at bearing, visible, and my cursor is normal.

### Screenshots and Videos

https://www.youtube.com/watch?v=P2M9yclbCqo

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

AppleSkin
Architectury API
AttributeFix
Better Biome Blend
Bookshelf
Chisels & Bits
Clear despawn
Cloth Config API
Comforts
Concurrent Chunk Managment
Controlling
Detail Armor Bar
EditSign
Enchantment Description
Enhanced Block Entities
FallingTree
FerriteCore
FPS Display
FPS Monitor
Indium
Iris Shaders
LazyDFU
Lithium
Mod Menu
Mouse Tweaks
REI
Simple Backpack
Sodium
Starlight
Terralith
Tool Stats
Universal Graves
WTHIT
Xaero's Minimap
Xaero's World Map

**Comment by TropheusJ** [comment] 2022-04-15 21:47
Duplicate of #97

**Closed as completed by TropheusJ** 2022-04-15 21:47 UTC
Labels: type: bug
