### ISSUE TITLE
The create:deployer in the latest version crashes the server

### ISSUE THREAD

**Issue by MrShellad** [Fabricators-of-Create/Create#628] opened 2022-11-26 15:48 UTC
### Describe the Bug

Time: 2022-11-26 23:34:19
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because the return value of "net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel()" is null
	at net.minecraft.class_3244.handler$zga000$adventure$initTracking(class_3244.java:3044)
	at net.minecraft.class_3244.<init>(class_3244.java:242)
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayNetworkHandler.<init>(FakeServerPlayNetworkHandler.java:21)
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayer.<init>(FakeServerPlayer.java:20)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerFakePlayer.<init>(DeployerFakePlayer.java:58)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.initHandler(DeployerTileEntity.java:146)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.initialize(DeployerTileEntity.java:139)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntity.tick(SmartTileEntity.java:67)
	at com.simibubi.create.content.contraptions.base.KineticTileEntity.tick(KineticTileEntity.java:94)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.tick(DeployerTileEntity.java:172)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:1589)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_3244.handler$zga000$adventure$initTracking(class_3244.java:3044)
	at net.minecraft.class_3244.<init>(class_3244.java:242)
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayNetworkHandler.<init>(FakeServerPlayNetworkHandler.java:21)
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayer.<init>(FakeServerPlayer.java:20)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerFakePlayer.<init>(DeployerFakePlayer.java:58)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.initHandler(DeployerTileEntity.java:146)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.initialize(DeployerTileEntity.java:139)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntity.tick(SmartTileEntity.java:67)
	at com.simibubi.create.content.contraptions.base.KineticTileEntity.tick(KineticTileEntity.java:94)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.tick(DeployerTileEntity.java:172)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)

-- Block entity being ticked --
Details:
	Name: create:deployer // com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity
	Block: Block{create:deployer}[axis_along_first=true,facing=north]
	Block location: World: (-775,66,1281), Section: (at 9,2,1 in -49,4,80; chunk contains blocks -784,-64,1280 to -769,319,1295), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,-64,1024 to -513,319,1535)
	Block: Block{create:deployer}[axis_along_first=true,facing=north]
	Block location: World: (-775,66,1281), Section: (at 9,2,1 in -49,4,80; chunk contains blocks -784,-64,1280 to -769,319,1295), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,-64,1024 to -513,319,1535)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:1589)

-- Affected level --
Details:
	All players: 2 total; [class_3222['Hanzo9527'/211, l='ServerLevel[www]', x=-789.47, y=68.00, z=1367.57], class_3222['mengxi'/851, l='ServerLevel[www]', x=-775.53, y=66.00, z=1283.83]]
	Chunk stats: 5740
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,96,-48), Section: (at 0,0,0 in 1,6,-3; chunk contains blocks 16,-64,-48 to 31,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 2425220 game time, 1349744 day time
	Level name: www
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 24868 (now: false), thunder time: 85312 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:1589)

### Reproduction Steps

The create:deployer in the latest version crashes the server

### Expected Result

The create:deployer in the latest version crashes the server

### Operating System

Windows11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment] 2022-11-26 15:51
Duplicate of #503

**Closed as completed by TropheusJ** 2022-11-26 15:51 UTC
Labels: type: bug
