### ISSUE TITLE
Crash in NBTSerializer

### ISSUE THREAD

**Issue by Vavency** [Fabricators-of-Create/Create#1391] opened 2024-03-21 14:58 UTC
### Describe the Bug

Saving the world crashes internal server.

### Reproduction Steps

1. Download the instance [here](https://onedrive.live.com/download?resid=61A64287FCD71DDA%21369&authkey=!AJKiELg72C_ZYl8)
2. Install it with prism launcher (or just cherry pick the world)
3. Load it up in single player
4. Save the world.

### Expected Result

Saving without a crash

### Crash Report or Log

https://gist.github.com/Vavency/1b1a68594af77a33fd39297f45768983

### Operating System

Fedora 39 Linux 

### Mod Version

0.5.1f

### Minecraft Version

1.19.2

### Additional Context

The world was upgraded from 0.5.1c

**Comment by IThundxr** [comment] 2024-03-21 15:02
Duplicate of https://github.com/Fabricators-of-Create/Create/issues/1363

**Closed as completed by IThundxr** 2024-03-21 15:02 UTC
Labels: type: bug
