### ISSUE TITLE
Mechanical Saw Crash.

### ISSUE THREAD

**Issue by KateReller** [Fabricators-of-Create/Create#976] opened 2023-06-26 07:15 UTC
### Describe the Bug

Pondering the mechanical saw crashes the server.

### Reproduction Steps

1. Ponder mechanical saw.
2. Crash.

### Expected Result

To be able to fully ponder the mechanical saw.

### Crash Report or Log

https://mclo.gs/cCZKO3D

### Operating System

Windows 10 (Atlas OS)

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.15
		adaptive-tooltips: Adaptive Tooltips 1.0.1
		advancementinfo: AdvancementInfo 1.19.1-fabric0.58.5-1.3.1
		alternate-current: Alternate Current 1.5.0
		amecs: Amecs 1.3.8+mc.1.19-rc2
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.5.82
		autoclicker-fabric: Auto Clicker 1.19.2-1.4.2-build.19
		autofish: Autofish 0.9.5-SNAPSHOT
		automated-cobble-miner: Automated Cobble Miner 1.0.0+mc1.19
		badpackets: Bad Packets 0.2.1
		balm-fabric: Balm 4.5.7
		basicshields: Basic Shields [Fabric] 1.4.0-1.19.2
			crowdin-translate: CrowdinTranslate 1.4+1.19
		bclib: BCLib 2.1.6
		beaconoverhaul: Beacon Overhaul 1.7.3+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		bedrodium: Bedrodium 0.2
		betterbeds: Better Beds 1.2.0
		betterbiomeblend: Better Biome Blend 1.19-1.3.6-fabric
		betterend: Better End 2.1.5
		betterf3: BetterF3 4.0.0
		betterhurtcam: BetterHurtCam 1.5.5
			betterhurtcam-mc119: BetterHurtCam+mc1.19 1.5.5
		bettermounthud: Better Mount HUD 1.2.0
		betternether: Better Nether 7.1.3
		betterpingdisplay: Better Ping Display 1.1.1
		betterstats: Better Statistics Screen 2.9.3+1.19.2
			tcdcommons: TCD Commons API 2.9.1+1.19.2
		bettertaskbar: Better Taskbar 1.5.1
		blockmeter: Block Meter 1.7
		borderlessmining: Borderless Mining 1.1.5+1.19
		bugjump: BugJump 1.0.0-1.19.2
		cat_jam: cat_jam 1.0.1
		chatpatches: Chat Patches 192.2.1
		cleardespawn: Clear Despawn 1.1.10
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.57
		colormeoutlines: Color Me Outlines 1.1.1
		connectedglass: Connected Glass 1.1.6
		connectivity: Connectivity Mod 1.19.2-4.2
		cookingforblockheads: Cooking for Blockheads 13.3.2
		create: Create 0.5.0.i-1017+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.8.a-4
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.954+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_accessors: Porting Lib Accessors 2.1.954+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.954+1.19.2
				porting_lib_base: Porting Lib Base 2.1.954+1.19.2
				porting_lib_common: Porting Lib Common 2.1.954+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.954+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.954+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.954+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.954+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.954+1.19.2
				porting_lib_loot: Porting Lib Loot 2.1.954+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.954+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.954+1.19.2
				porting_lib_models: Porting Lib Models 2.1.954+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.954+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.954+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.954+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			registrate-fabric: Registrate for Fabric 1.1.57-MC1.19.2
		create_crystal_clear: Create: Crystal Clear 1.0+1.19.2
		createaddition: Create Crafts & Additions 20230211a
			team_reborn_energy: Energy 2.2.0
		cullleaves: Cull Leaves 3.0.1
			midnightlib: MidnightLib 1.0.0
		cursorcenteredfix: CursorCentered Fix 1.0
		custom_hud: CustomHud 3.1.0+1.19.2
		customfov: Custom FoV 6.0.0-beta.1+1.19.2
		customwindowtitle: Custom Window Title 1.1.1
		dark-loading-screen: Dark Loading Screen 1.6.12
		debugify: Debugify 2.8.0
		deepslatecutting: Deepslate Cutting 1.5.0
			maybe-data: Maybe data 1.3.2-1.19.2
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		dimthread: DimensionalThreading 1.2.7
			com_github_wearblackallday_javautils: JavaUtils bd58640372
		doggomodoverhauled: Doggo Mod Overhauled 2.1.0
		draggable-resource-packs: Draggable Resource Packs 3.0.1+build.9
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		ears: Ears 1.4.6
		easeify: Easeify 1.1.0
			vigilance: Vigilance 258
		easymagic: Easy Magic 4.3.3
		eatinganimationid: Eating Animation 1.9.1
		elementalcreepers: Elemental Creepers: Refabricated 1.4.3+1.19
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.19
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.2
		entityoutliner: Entity Outliner 1.2.5
		eternaleats: Eternal Eats 1.0.4
		everycomp: Every Compat 1.19.2-2.4.8
		expandeddelight: Expanded Delight 0.2.5.2
		expandedstorage: Expanded Storage 8.3.3
		explosiveenhancement: Explosive Enhancement 1.1.0-1.19.2
		extremesoundmuffler: Extreme sound muffler 3.37-fabric-1.19.2
			fiber: fiber 0.23.0-2
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.4+kotlin.1.8.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabric-tree-chopper: Fabric Tree Chopper 0.8.10
			fiber2cloth: Fiber To Cloth 4.0.0
		fabrication: Fabrication 3.2.7+1.19
			lib39-deferral: Lib39 (Deferral) 1.1.1
		fabricloader: Fabric Loader 0.14.21
		fabricshieldlib: Fabric Shield Lib 1.7-1.19.2
			mm: Manningham Mills 2.3
		fallingleaves: Falling Leaves 1.13.0+1.19.2
		fallingtree: FallingTree 3.10.0
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farmersknives: Farmer's Knives 2.4
		faster_entity_animations: FastAnim 1.5.6
		ferritecore: FerriteCore 5.0.3
		fishonaleash: Fish on a Leash! 1.19-1.0.0
		forgeconfigapiport: Forge Config API Port 4.2.11
		freecam: Freecam (Modrinth Edition) 1.1.6
		ftbchunks: FTB Chunks 1902.3.21-build.266
		ftblibrary: FTB Library 1902.3.19-build.214
		ftbteams: FTB Teams 1902.2.13-build.100
		fwaystones: Fabric Waystones 3.0.7+mc1.19.2
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		highlight: Highlight 1.0.0
			resourcefullib: Resourceful Lib 1.1.9
		immediatelyfast: ImmediatelyFast 1.1.12
			net_lenni0451_reflect: Reflect 1.1.0
		indium: Indium 1.0.9+mc1.19.2
		ingredient-extension-api: Ingredient Extension API 3.0.6
		inventorio: Inventorio 1.9.1
		inventorysorter: Inventory Sorter 1.8.10-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemmodelfix: Item Model Fix 1.0.3+1.19
		itemswapper: ItemSwapper 0.4.0-mc1.19.2
		jamlib: JamLib 0.6.0+1.19
		java: Java HotSpot(TM) 64-Bit Server VM 17
		keymap: keymap 0.7.0-beta.1+1.19.2-fabric
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		lazydfu: LazyDFU 0.1.3
		leashmod: Leashable Players 1.0.2
		lighty: Lighty 1.3.0+1.19.2
		lithium: Lithium 0.11.1
		lod: Distant Horizons 1.6.9a
		magistuarmory: Epic Knights Mod 7.11
		mcwbridges: Macaw's Bridges 2.0.7
		mcwdoors: Macaw's Doors 1.0.8
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwfurnitures: Macaw's Furniture 3.1.0
		mcwlights: Macaw's Lights and Lamps 1.0.5
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwpaths: Macaw's Paths and Pavings 1.0.3
		mcwtrpdoors: Macaw's Trapdoors 1.1.0
		mcwwindows: Macaw's Windows 2.1.2
		megane: megane 8.4.2
			megane-api: megane-api 8.4.2
			megane-create: megane-create 8.4.2
			megane-fabric-transfer: megane-fabric-transfer 8.4.2
			megane-reborn-energy: megane-reborn-energy 8.4.2
			megane-runtime: megane-runtime 8.4.2
			megane-vanilla: megane-vanilla 8.4.2
		memoryleakfix: Memory Leak Fix 1.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		meticulous: Meticulous 1.1.1
		minecraft: Minecraft 1.19.2
		minequery: MineQuery 1.7.0
			com_github_octocynth_calculator-lib: calculator-lib 8c69c67b0e
		modernfix: ModernFix 5.0.2+mc1.19.2
		modmenu: Mod Menu 4.1.2
		moonlight: Moonlight 1.19.2-2.2.38
		moreculling: More Culling 1.19.1-0.17.0
			conditional-mixin: conditional mixin 0.3.0
		mousetweaks: Mouse Tweaks 2.22
		mousewheelie: Mouse Wheelie 1.11.1+mc1.19.2
			amecsapi: Amecs API 1.4.0+mc22w17a
			coat: Coat 1.0.0-beta.20+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.7.1+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc22w17a
		mtape: M-Tape 1.6.0
		netherite: Easy Netherite 0.0.8-1.19.2
		nmuk: No More Useless Keys 1.1.0+mc1.19.2
		nnvf: No Night Vision Flickering 0.1.3
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		notenoughanimations: NotEnoughAnimations 1.6.2
		notes: Notes 1.19.2-2.0.0-fabric
		omegamute: Omega Mute 3.0
		owo: oωo 0.8.5+1.19
			blue_endless_jankson: jankson 1.2.1
		patchouli: Patchouli 1.19.2-77-FABRIC
		pickupnotifier: Pick Up Notifier 4.2.4
		placementpog: Bridging Mod 1.2.0
		puzzleslib: Puzzles Lib 4.4.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		resourcify: Resourcify 1.1.0
			elementa: Elementa 590+markdown
			universalcraft: UniversalCraft 269
		rhino: Rhino 1902.2.2-build.268
		rightclickharvest: Right Click Harvest 3.2.2+1.19.x-1.20.1-fabric
		roughly_enough_loot_tables: Roughly Enough Loot Tables 1.19-1.0
		roughlyenoughitems: Roughly Enough Items 9.1.595
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.1.4
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		screenshot_viewer: Screenshot Viewer 1.1.2-fabric-mc1.19x
			catconfig-mc: Cat Config MC 0.1.1
				io_github_lgatodu47_catconfig: catconfig 0.2.4
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		servercore: ServerCore 1.3.3-1.19.2
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			me_lucko_spark-api: spark-api 0.1-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
		sleepwarp: SleepWarp 2.0.0+1.19.2
		smoke_suppression: Smoke Suppression 1.0.13
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		spark: spark 1.10.37
		staaaaaaaaaaaack: Staaaaaaaaaaaack 1.19.2-1.1-34
		stack-to-nearby-chests: Stack to Nearby Chests 0.3.0
			libgui: LibGui 6.3.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		starlight: Starlight 1.1.1+fabric.ae22326
		stendhal: Stendhal 1.3.4-1.19
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.9-f
		t_and_t: Towns and Towers 1.9
		taxfreelevels: Tax Free Levels 1.3.3
		terrablender: TerraBlender 2.0.1.136
		terralith: Terralith 2.3
		the_bumblezone: The Bumblezone - Fabric 6.7.24+1.19.2
			fake-player-api: Fake Player API 0.5.0
		thiccpackets: Extra Thicc Packets 1.17-1.19+
		toms_storage: Tom's Simple Storage Mod 1.5.6
		trinkets: Trinkets 3.4.2
		ukulib: ukulib 0.6.1+1.19.2
			gs_mclo_java_mclogs-java: mclogs-java 2.1.1
		vanilla-hammers: Vanilla Hammers 3.5.0-1.19.2
			magna: Magna 1.8.0-1.19.2
			omega-config: OmegaConfig 1.1.0
			static-content: Static Content 1.0.2-1.16.2
				staticdata: Static Data 1.1.2
		vanityslots: Vanity Slots 1.2.8
		wthit: wthit 5.16.1
		xaerominimap: Xaero's Minimap 23.4.3
		xaeroworldmap: Xaero's World Map 1.30.2
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yigd: You're in Grave Danger 1.4.9
		zoomify: Zoomify 2.9.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.5
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.5
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.5
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.5

**Comment by TropheusJ** [comment] 2023-07-03 04:08
can't reproduce, might've been fixed in 0.5.1

**Closed as completed by TropheusJ** 2023-07-03 04:08 UTC
Labels: type: bug
