### ISSUE TITLE
Brass funnel causes game crash

### ISSUE THREAD

**Issue by w3ricardo** [Fabricators-of-Create/Create#570] opened 2022-10-12 23:16 UTC
### Describe the Bug

I had a brass funnel getting stuff from a chest to a belt, 16 items at a time. I added some chain leggins to the chest, and the server crashed. I'm guessing the funnel tried to stack them.

### Reproduction Steps

1. Connect a brass funnel to a chest.
2. Set it to output 2 items at a time.
3. Add two isntances of an item that doesn't stack to the chest.

### Expected Result

The game crashes.

### Operating System

Ubuntu 22.04

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

### Other Mods

modpack: All of Fabric 2.0.4

**Comment by PRO-2684** [comment] 2022-11-05 14:26
Same problem. In my case I connected the funnel to a chest with some sand paper and when I adjusted the funnel the game crashed. Unable to re-enter that save.

**Comment by w3ricardo** [comment] 2022-11-07 12:44
> Same problem...

My game was saved a few minutes before the crash, the chest was empty when I got back.
If your chest still has sand paper, I suppose it will continue to crash.
You may have to edit the world (MCEdit?) to get back.

**Comment by TropheusJ** [comment] 2022-11-22 01:10
need the log

**Comment by Catoverflow** [comment] 2022-11-27 16:01
I can reproduce this error following the steps above. Also I'm attaching screenshot and log here.

![2022-11-27_23 53 54](https://user-images.githubusercontent.com/55503205/204144743-032ea329-1f5f-4850-90b8-f2d76331517d.png)

What I did later: put several potion (unstackable) into the chest in a short time, and game crashed immediately.

[crash-2022-11-27_23.54.01-server.txt](https://github.com/Fabricators-of-Create/Create/files/10098664/crash-2022-11-27_23.54.01-server.txt)

---

For others encountered with this problem, you can try deleting the funnel to get your save back working.
My friend's [blogpost](https://ibug.io/p/54) on steps to restore our save after triggering this bug.

**Comment by w3ricardo** [comment] 2022-11-30 20:34
If you have a funnel set to 20 items, what should be the correct behaviour:
* output 1 potion as soon as possible
* output 1 potion at a time when there are at least 20 potions in the chest
* output 16 torches as soon as possible
* output 16 + 4 torches as soon as there are 20 torches in the chest

**Comment by iBug** [comment] 2022-12-08 16:41
> If you have a funnel set to 20 items, what should be the correct behaviour:

Make it simple: Output 20 torches as soon as possible.

If the FilterAmount is higher than an item can stack (1 or 16), then that kind of item will never be exported or imported.

**Comment by TropheusJ** [comment] 2022-12-26 06:43
duplicate of #561

**Closed as completed by TropheusJ** 2022-12-26 06:43 UTC
Labels: type: bug
