### ISSUE TITLE
crashes with hephaestus.

### ISSUE THREAD

**Issue by bananaOHHHOOOOHAHAHAHAAAAHA** [Fabricators-of-Create/Create#1145] opened 2023-10-08 01:05 UTC
### Describe the Bug

so apparently haphaestus and create both use porting lib but different versions which causes a crash, and they said they would fix it for 1.20.2. i use 1.20.1 so i was wondering you could fix it in your latest update on creates end. thanks

### Reproduction Steps

1. download create and hephaestus.
2. launch game
3. crash
...

### Expected Result

it should not crash.

### Crash Report or Log

https://mclo.gs/QlhzZQs

### Operating System

windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

guard villagers, but even without it it still crashes. also obviously fabric api

**Comment by TropheusJ** [comment] 2023-12-18 03:29
duplicate of #1061

**Closed as completed by TropheusJ** 2023-12-18 03:29 UTC
Labels: type: bug
