### ISSUE TITLE
Crash when ponder fluid pipe, with twilightforest mod

### ISSUE THREAD

**Issue by ErrorPower2001** [Fabricators-of-Create/Create#762] opened 2023-01-20 18:24 UTC
### Describe the Bug

(Sry for poor English) An unknown bug causes a crash.

When just install [twilightforest](https://github.com/TeamTwilight/twilightforest-fabric) and [Create[Fabric]](), and `Hold [w] to Ponder` the `Fluid Pipe`, Game will Crash

### Reproduction Steps

1. Install [twilightforest[Fabric]](https://github.com/TeamTwilight/twilightforest-fabric) and [Create[Fabric]]()
2. Hold w to Ponder the `Fluid Pipe` in any ui you can do it, include [JEI](https://github.com/mezz/JustEnoughItems) or [REI](https://github.com/shedaniel/RoughlyEnoughItems)

### Expected Result

Game crash.

### Crash Report or Log

https://1drv.ms/u/s!AljLE5SywXEtgP4pWGyccF8bBaicCg?e=il0zUW

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

[twilightforest-fabric-4.1.313](https://github.com/TeamTwilight/twilightforest-fabric)
fabric-api-0.67.0+1.18.2

**Comment by TropheusJ** [comment] 2023-01-20 19:19
Duplicate of #759

**Closed as completed by TropheusJ** 2023-01-20 19:19 UTC
Labels: type: bug
