### ISSUE TITLE
Conveyor Belts are randomly not working

### ISSUE THREAD

**Issue by LambdAurora** [Fabricators-of-Create/Create#285] opened 2022-05-10 19:49 UTC
### Describe the Bug

Conveyor belts will stop picking up any items standing on top of them, and this issue can be fixed by restarting the game, introducing a random nature to it.

### Reproduction Steps

1. Place belts and make them move.
2. Have a contraption dispense items on top of the belts
3. Belts will not transport the items

### Expected Result

Belts should transport the dispensed items as it works with the same setup in the Forge version.

### Screenshots and Videos

https://user-images.githubusercontent.com/12587332/167709782-fe095b6f-5ae4-473c-8e2c-f90ce62b04b7.mp4

### Operating System

Arch Linux

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

```
[18:40:54] [main/INFO]: Loading 139 mods:
	- advancementinfo 1.18.2-fabric0.47.10-1.3.1
	- appleskin 2.4.0+mc1.18.2
	- aurorasdeco 1.0.0+1.18
	- cardinal-components-base 4.1.3
	- cardinal-components-entity 4.1.3
	- clickthrough 1.18.2-fabric0.47.10-0.4
	- cloth-basic-math 0.6.0
	- cloth-config 6.0.42
	- com_electronwill_night-config_core 3.6.3
	- com_electronwill_night-config_toml 3.6.3
	- com_formdev_flatlaf 2.2
	- com_github_llamalad7_mixinextras 0.0.9
	- com_google_code_findbugs_jsr305 3.0.2
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT
	- config2brigadier 1.1.1
	- create mc1.18.2_v0.4.1+551
	- crowdin-translate 1.4+1.18.2
	- dripstone_fluid_lib 1.2.0
	- elytratrinket 3.0.0-1.18.1
	- expandedstorage 7.3.12
	- fabric-data-generation-api-v1 2.0.7+6d3e563660
	- fabric-language-kotlin 1.7.2+kotlin.1.6.20
	- fabric-permissions-api-v0 0.1-SNAPSHOT
	- fabrication 2.3.1-exp3
	- fabrictailor 1.8.1
	- fake-player-api 0.3.0
	- flywheel 1.18-0.6.2.25
	- forge_tags 2.1
	- forgeconfigapiport 3.2.0
	- gbfabrictools 1.3.4+1.18.2
	- improved_dedicated_server_gui 1.0.0+1.18
	- inspecio 1.4.1+1.18
	- java 17
	- krypton 0.1.9
	- lambdamap 0.1.0+1.18
	- lazydfu 0.1.2
	- litematica 0.11.2
	- lithium 0.7.9
	- lovely_snails 1.0.4+1.18
	- malilib 0.12.1
	- milk 0.3.0
	- minecraft 1.18.2
	- mm 2.3
	- more_codecs 0.2.1+1.18
	- ninjaphenix_container_lib 1.3.0
	- noindium 1.0.1+1.18.2
	- omega-config 1.2.3-1.18.1
	- org_jetbrains_kotlin_kotlin-reflect 1.6.20
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.20
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.20
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.20
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.0
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.0
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2
	- packet_tweaker 0.3.0+1.18.2
	- placeholder-api 1.1.3+1.17.1
	- player-data-api 0.1.0+1.18
	- playerpronouns 1.3.0+1.18
	- pockettools 1.1.3
	- polymer 0.2.0-pre.2+1.18.2
	- polymer-all 0.2.0-pre.2+1.18.2
	- polymer-blocks-ext 0.1.0-alpha.7+1.18.2
	- polymer-legacy 0.1.9+0.2.0-pre.2+1.18.2
	- porting_lib 0.2.0+1.18.2.db29e7a
	- pride 1.1.0+1.17
	- quilt_base 1.1.0-beta.8+1.18.2
	- quilt_block_extensions 1.1.0-beta.8+1.18.2
	- quilt_client_command 1.1.0-beta.8+1.18.2
	- quilt_command 1.1.0-beta.8+1.18.2
	- quilt_crash_info 1.1.0-beta.8+1.18.2
	- quilt_dimension 1.1.0-beta.8+1.18.2
	- quilt_item_group 1.1.0-beta.8+1.18.2
	- quilt_item_setting 1.1.0-beta.8+1.18.2
	- quilt_lifecycle_events 1.1.0-beta.8+1.18.2
	- quilt_loader 0.16.0
	- quilt_networking 1.1.0-beta.8+1.18.2
	- quilt_recipe 1.1.0-beta.8+1.18.2
	- quilt_registry 1.1.0-beta.8+1.18.2
	- quilt_registry_entry_attachments 1.1.0-beta.8+1.18.2
	- quilt_resource_loader 1.1.0-beta.8+1.18.2
	- quilt_tags 1.1.0-beta.8+1.18.2
	- quilt_tooltip 1.1.0-beta.8+1.18.2
	- quilted_fabric_api 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_api_base 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_api_lookup_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_biome_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_blockrenderlayer_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_command_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_commands_v0 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_containers_v0 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_content_registries_v0 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_convention_tags_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_crash_report_info_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_dimensions_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_entity_events_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_events_interaction_v0 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_events_lifecycle_v0 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_game_rule_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_item_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_item_groups_v0 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_key_binding_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_keybindings_v0 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_lifecycle_events_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_loot_tables_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_mining_level_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_models_v0 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_networking_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_networking_v0 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_object_builder_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_particles_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_registry_sync_v0 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_renderer_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_renderer_indigo 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_renderer_registries_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_rendering_data_attachment_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_rendering_fluids_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_rendering_v0 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_rendering_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_resource_conditions_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_resource_loader_v0 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_screen_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_screen_handler_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_textures_v0 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_transfer_api_v1 1.0.0-beta.12+0.51.1-1.18.2
	- quilted_fabric_transitive_access_wideners_v1 1.0.0-beta.12+0.51.1-1.18.2
	- randomblockplacement 1.18.2-fabric0.47.10-1.1.2
	- reach-entity-attributes 2.1.1
	- registrate-fabric MC1.18.2-1.0.x
	- shulkerease 1.0.0
	- slotlink 4.3.1
	- spruceui 3.3.3+1.18
	- styled-nicknames 1.0.4+1.18
	- terraform-wood-api-v1 3.0.0
	- trinkets 3.3.0
	- tweakeroo 0.13.1
	- villager-hats 1.3.1
	- waystones 2.5.0
```

It is to be mentioned that after further testing, other mods don't seem to be the cause of the issue.

**Comment by TropheusJ** [comment] 2022-05-10 19:52
duplicate of #244

**Closed as completed by TropheusJ** 2022-05-10 19:52 UTC
Labels: type: bug
