### ISSUE TITLE
Ground under vertical gearbox is transparent

### ISSUE THREAD

**Issue by ChristopherHaws** [Fabricators-of-Create/Create#649] opened 2022-12-02 04:33 UTC
### Describe the Bug

When placing a vertical gearbox on the ground, it makes the grass underneath it transparent so you can see through the ground.

### Reproduction Steps

1. Place a vertical gearbox on the ground
2. Rotate the vertical gearbox so it has a shaft connection facing up
3. Notice that the ground beneath it is transparent

### Expected Result

You should be able to see the texture of the block under the vertical gearbox

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/5934505/205215010-2486565c-3f52-4878-8e42-ddc6c56cf613.png)

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Accurate Block Placement
Advanced Tooltips
Advancements Debug
AfkDisplay
Alternate Current
AntiXray
AppleSkin
Architectury API (Fabric/Forge)
Armor Statues
Armored Elytra
AudioPlayer
Auto Clicker (Fabric)
Axes Are Weapons
bad packets
Balm
BanHammer
Beenfo
Better Advancements
Better Beds
Better Third Person
BetterDarkMode
BetterF3
Blanket
Block Meter
Bobby
Bookshelf
Borderless Mining
Better Recipe Book
Concurrent Chunk Management Engine (Fabric)
Carpet-Fixes
Carpet
Chat Heads
Chat Signing Hider
Chat Up!
Chattix
ChestTracker
Chunky
CIT Resewn
Cloth Config API
Collective (Fabric)
Collective
Command Aliases
Consistency+
Continuity
Coord Finder
Couplings
Create Fabric
Creative One-Punch
Crops Love Rain
CrossStitch
Cull Less Leaves
Cycle Paintings
DeathLog
DeepslateCutting
Discontinuous Beacon Beams
Dynamic FPS
Dynmap-Forge/Fabric
EasierVillagerTrading
Enchanted Vertical Slabs
EnchantedShulkers
Enchantment Lore
EnderChests [Fabric]
Entity Collision FPS Fix
Entity Texture Features - [Fabric & Forge]
Entity View Distance
EntityCulling
Entity Texture Features
Essential Commands
Expanded Axe Enchanting
Fabric API
Fabric Language Kotlin
Fabric Votifier
Fabrication & Forgery
FabricProxy-Lite
FastAnim
Fastload
FerriteCore
Forge Config API Port
Forge Config API Port
ForgetMeChunk
Head Index
Horse Stats Vanilla
HotbarCycle
Image2Map
Indium
Interdimensional Map Markers
Inventory Essentials
Inventory Profiles Next
Inventory Totem
Inv View
Iris Shaders
Just Player Heads
Keep Head Names
KoroWorld-Lib
Krypton
LambDynamicLights
Lanterns Belong on Walls
Lapis Reserve
LazyDFU
Leaves Be Gone
Ledger Databases
Ledger
libIPN
Litematica Server Paster
Litematica
Lithium
Let Me Despawn
Login Protection[Forge/Fabric]
LuckPerms
LuckPerms
MaLiLib
Memory Leak Fix
MiniHUD
Mixin Conflict Helper
MixinTrace
MobFilter
Modern Glass Doors
Mod Menu
More Music Discs [Fabric / Forge]
MoreChatHistory
More Culling
MySQL JDBC (Fabric/Forge)
No Sneaking Over Magma!
Observable
Oh The Biomes You'll Go Refabricated
Pick Block Pro
Placeholder API
Player Pronouns
Puzzles Lib
RebindAllTheKeys
Recipe Cache
Reese's Sodium Options
Roughly Enough Items (REI)
Rules
Screenshot to Clipboard
Server Hats
ServerCore
Server Tick
Set World Spawn Point
Shards!
Sheep Consistency
ShetiPhianCore [Fabric]
Shift-Scroll Fix for macOS [Fabric]
ShulkerBoxTooltip [Fabric/Forge]
Simple Discord Link Bot [Forge/Fabric]
Simple Voice Chat
Skin Swapper
SleepWarp
Server Performance - Smooth Chunk Save[Forge/Fabric]
Smooth Boot (Fabric)
Sodium Extra
Sodium Shadowy Path Blocks
Sodium
Sound Physics Remastered
spark
Stack Refill (Fabric)
Starlight (Fabric)
Status Effect Timer
Styled Nicknames
Styled Player List
Suggestion Tweaker
Syncmatica
TerraBlender (Fabric)
Text Utilities
Textile Backup
The One Probe Fabric
thorium
Tool Stats
ToolTipFix
Trinkets
Tweakeroo
Vanilla Permissions
VTDownloader
WorldEdit
WorldEdit CUI (Fabric)
Xaero's Minimap
Xaero's World Map
YetAnotherConfigLib
Zoomify

**Comment by SplendidAlakey** [comment] 2022-12-02 09:31
Technically caused by MoreCulling, but I think it can be fixed on Create's side. For now, you can disable MoreCulling.

**Comment by digitaltrucker** [comment] 2022-12-03 09:23
Same thing happens with train tracks, btw.

**Comment by ChristopherHaws** [comment] 2022-12-05 05:46
I can confirm that setting `useBlockStateCulling = false` in moreculling's config does indeed mitigate the issue.

**Comment by TropheusJ** [comment] 2022-12-25 01:25
duplicate of #479

**Closed as completed by TropheusJ** 2022-12-25 01:25 UTC
Labels: type: bug, area: compatibility
