### ISSUE TITLE
Sequenced Gearshift Causes Game Crash

### ISSUE THREAD

**Issue by Tempest-5ky** [Fabricators-of-Create/Create#382] opened 2022-06-17 03:05 UTC
### Describe the Bug

More or less what the title says, powering a sequenced gearshift with redstone while it's connected to a creative motor and mechanical piston causes a crash.
Possibly caused by Starlight?

### Reproduction Steps

1. Load Minecraft with latest version of Create, Fabric API, and Starlight (I have several other mods in the logs but the crash happens regardless of whether those are loaded)
2. Attach a creative motor to a sequenced gearshift and a downwards-facing mechanical piston
3. Set gearshift to extend said piston
4. Power gearshift
5. Crash
...

### Expected Result

No game crash, contraption works as normal

### Crash Report or Log

https://mclo.gs/nfALp7U or https://crashy.net/w7AMUF5GL3f1ZrDbQ4eq

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

A crap ton but as I said, the crash does also occur with only Fabric API, Create, and Starlight loaded!

**Comment by TropheusJ** [comment] 2022-06-17 03:10
duplicate of #360, happens on Forge too, awaiting a PR. If the contraption has more blocks on it, it should be fine.

**Closed as completed by TropheusJ** 2022-06-17 03:10 UTC
Labels: type: bug
