### ISSUE TITLE
crash when mixing in basin 

### ISSUE THREAD

**Issue by 3dguru** [Fabricators-of-Create/Create#604] opened 2022-11-20 03:44 UTC
### Describe the Bug

crash when creating brass in basin

### Reproduction Steps

1. added hand crack to cogwheel 
2. added zinc and copper to basin
3. turn hand crack and crashes 
...

### Expected Result

mixing would make brass 

### Crash Report or Log

https://pastebin.com/7MAtHuE3

### Operating System

windows 11, macos 13 

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

Mods:   [✔] architectury-6.3.49-fabric   [✔] create-fabric-1.19.2-0.5.0f-776   [✔] ecologics-fabric-1.19.2-2.1.10   [✔] fabric-api-0.66.0+1.19.2   [✔] geckolib-fabric-1.19-3.1.37   [✔] Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13   [✔] Patchouli-1.19.2-76-FABRIC   [✔] RoughlyEnoughItems-9.1.572   [✔] TerraBlender-fabric-1.19.2-2.0.1.130   [✔] Terralith_v2.3.5   [✔] The_Graveyard_2.0_(FABRIC)_for_1.19.2   [✔] The_Graveyard_Biomes_1.2_(FABRIC)_for_1.19   [✔] WilderWild-1.1.1-Fabric+1.19.2   [✔] worldedit-mod-7.2.12   [✔] wwoo-3.1.8-FABRIC-1.19.2

**Comment by digitaltrucker** [comment] 2022-11-20 03:49
The problem is Wilder Wild, it loads NBT Crafting which causes the crash.

**Comment by 3dguru** [comment] 2022-11-20 03:57
would it be a possible fix in future release?

**Comment by TropheusJ** [comment] 2022-11-22 22:51
duplicate of 596

**Closed as completed by TropheusJ** 2022-11-22 22:51 UTC
Labels: type: bug
