### ISSUE TITLE
0.5.1b Visual bug with sandpaper and rose quartz

### ISSUE THREAD

**Issue by LastLightTonight** [Fabricators-of-Create/Create#1012] opened 2023-07-22 06:34 UTC
### Describe the Bug

When you are polishing rose quartz with a piece of sandpaper in your main hand and you drop it during polishing, it drops as a usual sandpaper with a glitchy rose quartz in it.

### Reproduction Steps

1. Get a piece of sandpaper and rose quartz and start polishing
2. While it's being polished, press Q and drop the sandpaper which won't give the quartz back
3. Done, You've got a glitchy rose quartz texture "glued" to the sandpaper
(bug disappears when you pick them up again)
...

### Expected Result

IDK choose something:
1. You only drop the sandpaper but the r.quartz gets back to your inventory
2. You drop the sandpaper and the r.quartz as two separate items
3. Just fix the glitchy combination of textures and maybe add a unique texture of sandpaper with r.quartz

### Crash Report or Log

It's a soft bug

### Operating System

Windows 10 Pro

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

I currently use CreateDeco, and ExtendedDrawers (it's just StorageDrawers for new versions of Minecraft) but the bug also happened without those mods, on pure Create.

**Comment by LastLightTonight** [comment] 2023-07-22 06:37
Upd: Checked again and the bug doesn't disappear when you pick up the glitchy sandpaper but does when you use it again (RMB to start polishing)

**Comment by TropheusJ** [comment] 2023-08-04 05:21
going to consider this a duplicate of #906, same as forge

**Closed as completed by TropheusJ** 2023-08-04 05:21 UTC
Labels: type: bug
