### ISSUE TITLE
Copycat panels not applying bar textures properly when continuity mod is installed

### ISSUE THREAD

**Issue by StanaKun** [Fabricators-of-Create/Create#1542] opened 2024-07-14 13:19 UTC
### Describe the Bug

Applying any bar (iron, andesite, brass or copper) texture on Copycat Panels results in wrong textures being applied

### Reproduction Steps

1. Place Copycat Panel in any orientation
2. Apply any bar to placed panel

### Expected Result

Iron Bar texture (or any other bar) showing as if iron bar was placed next to other iron bars.

### Screenshots and Videos

![2024-07-14_15 08 50](https://github.com/user-attachments/assets/f37d416d-df33-4a49-80b7-980821d4ae5e)
This is with continuity integrated resource pack being disabled:
![2024-07-14_15 08 39](https://github.com/user-attachments/assets/5958ecc3-e32b-4f5c-8744-900ca0901afd)

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Continuity 3.0.0-beta.5+1.20.1
Fabric API 0.92.2+1.20.1

### Additional Context

There is a workaround if u dont need any connected textures except the glass:
You can use Complementary shaders with iris and enabling the connected glass option instead of continuity, but it then creates the same problem that was described in #1540

**Comment by IThundxr** [comment] 2024-07-14 13:22
duplicate of https://github.com/Fabricators-of-Create/Create/issues/1176

**Closed as not planned by IThundxr** 2024-07-14 13:22 UTC
Labels: type: bug
