### ISSUE TITLE
Crashing game 1.18.2 v0.5.0c

### ISSUE THREAD

**Issue by ghost** [Fabricators-of-Create/Create#523] opened 2022-08-21 17:51 UTC
### Describe the Bug

I just added your amazing mod into my pack and I can not play because it will crash on startup

### Reproduction Steps

1. Added mod Create Fabric into my pack
2. Started the game and crash

### Expected Result

No crash

### Crash Report or Log

https://pastebin.com/cyputqZz

### Operating System

Windows10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

In crashlog

**Comment by TropheusJ** [comment] 2022-08-21 17:53
duplicate of #452

**Closed as completed by TropheusJ** 2022-08-21 17:53 UTC
Labels: type: bug
