### ISSUE TITLE
Hose Pulleys Crashing server when pulling from infinite source

### ISSUE THREAD

**Issue by ArmouredDrood** [Fabricators-of-Create/Create#607] opened 2022-11-20 08:06 UTC
### Describe the Bug

https://pastebin.com/8wys10jE
Crashlog

seems similar to :
https://github.com/Fabricators-of-Create/Create/issues/492

### Reproduction Steps

1. Use hose pulley in nether on infinite source of lava.
2.all hose pulleys pull 1 bucket of lava from the world (infinite source mechanic not working) 
3.all hose pulleys get stuck and pull no lava
4. chunk loaded pump area
5. left nether
6. restarted server
7. crash on server startup
...

### Expected Result

multiple different hose pulleys each pulling infinite lava from the nether, while chunkloaded.

### Crash Report or Log

https://pastebin.com/8wys10jE

### Operating System

Windows 10

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

### Additional Context
edit:I also had a lava tank train contraption moving lava from the nether to the overworld
seems similar to:
https://github.com/Fabricators-of-Create/Create/issues/492

**Comment by TropheusJ** [comment] 2022-11-20 23:53
duplicate of #533

**Closed as completed by TropheusJ** 2022-11-20 23:53 UTC
Labels: type: bug
