### ISSUE TITLE
Crash when launching

### ISSUE THREAD

**Issue by sirben99** [Fabricators-of-Create/Create#494] opened 2022-08-04 18:43 UTC
### Describe the Bug

Hey!

I updated create to the newest version (0.5.0c) and it crashes on startup. It complains something about menu buttons (and possible is crashing resource packs too because of Contiunity mod?).

This is a modpack, but i desided to create a report just incase it can be fixed form Creates site.

### Reproduction Steps

1. Update
2. Launch
3. Crash
4. ???
5. Profit

### Expected Result

No crash

### Crash Report or Log

https://pastebin.com/rLxpgBK0

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

		I have _alot_ of mods
		
		accurateblockplacement: Accurate Block Placement 1.0.12
		adorn: Adorn 3.5.0+1.18.2
		advancementinfo: AdvancementInfo 1.18.2-fabric0.47.10-1.3.1
		ambientenvironment: Ambient Environment 7.0+19
		amphitritecoffer: Amphitrite Coffer 1.2.0
		anchor: Anchor 1.1.0
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.2
		another_furniture: Another Furniture 1.1.3-1.18.2
		appleskin: AppleSkin 2.4.0+mc1.18.2
		aquatictorches: Aquatic Torches 1.0.0
		architects_palette: Architect's Palette Fabric 2.2
		architectury: Architectury 4.7.78
		armor_visibility: Armor Visibility 4.0.0
		armorpointspp: Armorpoints++ 3.0.1
			fiber: fiber 0.23.0-2
		attributefix: AttributeFix 14.0.2
		axolotlitemfix: Axolotl Item Fix 1.1.3
		badpackets: Bad Packets 0.1.2
		badwithernocookiereloaded: Bad Wither No Cookie! Reloaded 3.10.18 (Fabric 1.18.2)
		balm-fabric: Balm 3.1.0+0
		bcc: BetterCompatibilityChecker fabric-1.0.5
		bclib: BCLib 1.4.7
		better_climbing: Better Climbing 1.0.1
		better_loading_screen: Better Loading Screen 1.4.0
		betteradvancements: Better Advancements 0.2.1.132
		betterbiomeblend: Better Biome Blend 1.18.2-1.3.5-fabric
		betterdeserttemples: YUNG's Better Desert Temples 1.18.2-Fabric-1.3
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		betterenchantmentboosting: Better Enchantment Boosting 1.2.0
		betterend: Better End 1.1.1
		bettermending: Better Mending 1.4.1
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.2
		betternether: Better Nether 6.1.2
		bettersafebed: BetterSafeBed 1.18-fabric-a
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		bettertaskbar: Better Taskbar 1.4
		bettertridentreturn: Better Trident Return 1.18.2-1.0.2
		betterwitchhuts: YUNG's Better Witch Huts 1.18.2-Fabric-1.0.1
		big_items_duh: Big items, duh! 1.1.2+mc1.18.2
			amecsapi: Amecs API 1.3.6+mc22w06a
			coat: Coat 1.0.0-beta.17+mc1.18.2
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			tweed4_annotated: tweed4_annotated 1.3.0
			tweed4_base: tweed4_base 1.5.0+mc1.18.2
			tweed4_data: tweed4_data 1.2.1+mc1.18.2
			tweed4_data_hjson: tweed4_data_hjson 1.1.0
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18.2
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18.2
		biomemakeover: Biome Makeover 1.18.2-1.4.29
		blockus: Blockus 2.4.7+1.18.2
			terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		bole: Bole 1.0.7-mc1.18.2-fabric
		bookshelf: Bookshelf 13.2.48
		cem: Custom Entity Models 0.7.1
		chalk: Chalk 2.0.1+1.18.2
		chimes: Chimes 1.1.1
		chipped: Chipped 1.2
		citresewn: CIT Resewn 1.1.1+1.18.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.18.2
		cleancut: CleanCut 1.18.2-5.0-fabric
		cleanview: CleanView 1.18.2-v1-fabric
		clear-skies: Clear Skies 2.0.92
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 8.0.0+15
		collective-fabric: Collective (Fabric) 4.36
		colytra: Colytra 2.1.1-1.18.1
		completeconfig: CompleteConfig 1.4.1
		concreteconversion: Concrete Conversion 6.1.0.0
		conduitspreventdrowned-fabric: Conduits Prevent Drowned (Fabric) 1.5
		configured_feature_saplings: Configured Feature Saplings 1.0.0
		conjuring: Conjuring 1.0.22+1.18
		continuity: Continuity 2.0.0+1.18.2
		controlling: Controlling For Fabric 9.0+21
		cozycabincore: Cozy Cabincore 1.2
		create: Create 0.5.0c-708
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 0.6.4-30
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			noindium: No Indium? 1.0.1+1.18.2
			porting_lib: Porting Lib 1.2.421-beta+1.18.2-dev.b8d195a
				serialization_hooks: Serialization Hooks 0.3.21
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.3
		creativecore: CreativeCore (Fabric) 2.6.12
		creeperoverhaul: Creeper Overhaul 1.3.1
		crops_love_rain: Crops Love Rain 1.2.2
		cull-less-leaves: Cull Less Leaves 1.0.1
		customizableelytra: Customizable Elytra 1.5.3-1.18
		customstars: Custom Stars 1.1+1.18.2
		deathknell: DeathKnell 3.0.2
		debugify: Debugify 1.11.0
		decor4fabric: Decor4Fabric 1.2
		decorative_blocks: Decorative Blocks 2.1.0
		decorative_winter: Decorative Winter 2.1.0
		delaybegone: Delay Be Gone 1.1.3
		dimension_data_fix: Dimension Data Fix 1.0.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		dismountentity-fabric: Dismount Entity (Fabric) 1.5
		dramaticdoors: Dramatic Doors (Fabric) 1.18.2-1.1.1
		dual_riders: Dual Riders 1.1.1
		dynamiccrosshair: Dynamic Crosshair 3.4+1.18.2
		dynamiccrosshaircompat: Dynamic Crosshair Compat 1.1+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		eatinganimationid: Eating Animation 1.8
		ecologics: Ecologics 1.7.6
		economical_villager_trading: Economical Villager Trading 1.2.5
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		editsign: EditSign 2.3.1
		effectsleft: EffectsLeft 0.1.1
		elytra_physics: ElytraPhysics 1.0.2
		enchdesc: EnchantmentDescriptions 10.0.6
		enderchests: EnderChests 1.0.10
		enhanced_mushrooms: Enhanced Mushrooms 4.0.1
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.18.2
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		entity_texture_features: Entity Texture Features 3.1.4-mc1.18.x
		exlinedoors: Exline's Doors 2.1.1
		exlinefurniture: Exline's Furniture 2.3.0
		expandeddelight: Expanded Delight 0.1.9
		experiencebugfix: Experience Bug Fix 18
		extendedclouds: Extended Clouds 1.1.1
		extraalchemy: Extra Alchemy 1.8.1
		extrasounds: ExtraSounds 2.3.1+1.18.2
			soundcategories: Sound Categories 1.2.4+1.18
		extremesoundmuffler: Extreme sound muffler 3.28_fabric-1.18.1
		fabric: Fabric API 0.58.0+1.18.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.1+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.10+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.3+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fallingleaves: Falling Leaves 1.11.1+1.18.2
		fancysporeblossom: FancySporeBlossom 1.0.1
		farmersdelight: Farmer's Delight 1.18.2-0.2.1
		farmersknives: Farmer's Knives 1.3.1
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		findme: FindMe 3.0.6
		fireworkfrenzy: Firework Frenzy 1.9
		flytre_lib: FlytreLib 1.8.2
		forgeconfigapiport: Forge Config API Port 3.2.0
		frameless: Frameless 1.0.1
		galosphere: Galosphere 1.18.2-1.1.1
		geckolib3: Geckolib 3.0.52
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		globaldataandresourcepacks: Global Data- & Resourcepacks 1.12.2.1
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		go-fish: Go Fish 1.5.0-1.18.2
		goblintraders: Goblin Traders 1.5.1
		graveyard: The Graveyard 1.9
		guardiansgalore: GuardiansGalore 1.18.2-3.0
		harvest-with-ease: Harvest with ease 1.18.2-1.0.0.1-fabric
		heartbond: Heartbond 1.3.0
		highlighter: Highlighter 1.1.2
		horseinboat: HorseInBoat 1.1.2
		horsestonks: Horse Stonks 1.0.1
		hyle: Hyle 0.1.0
		ia: Immersive Amethyst 1.1
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.4
		immersive_armors: Immersive Armors 1.3.6
		immersive_paintings: Immersive Paintings 0.1.5+1.18.2
		indium: Indium 1.0.7+mc1.18.2
		indypets: Independent Pets 1.0.0
		inmis: Inmis 2.6.0-1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		inventorysorter: Inventory Sorter 1.8.8-1.18
			kyrptconfig: Kyrpt Config 1.4.6-1.18
				blue_endless_jankson: jankson 1.2.1
		ironchests: Iron Chests: Restocked 2.0.3
		itemmodelfix: Item Model Fix 1.0.3+1.18
		itemscroller: Item Scroller 0.16.1
		jade: Jade 5.99.6
		jamlib: JamLib 0.0.5
		java: OpenJDK 64-Bit Server VM 17
		keybind_fix: Keybind Fix 1.0.0
		kiwi: Kiwi Lib 6.0.2
		knowmyname: Know my Name! 1.0.1
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		lightoverlay: Light Overlay 6.0.5
		lithium: Lithium 0.7.10
		make_bubbles_pop: Make Bubbles Pop Mod 0.0.2-1.19
		malilib: MaLiLib 0.12.1
		map_atlases: Map Atlases 2.0.1
		marketcrates: Marketcrates 1.4.1
		mavm: More Axolotl Variants Mod 1.0.8a
		maxhealthfix: MaxHealthFix 5.0.1
		mca: Minecraft Comes Alive 7.3.15+1.18.2
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.6
		mcwlights: Macaw's Lights and Lamps 1.0.4
		mcwpaintings: Macaw's Paintings 1.0.3
		mcwpaths: Macaw's Paths and Pavings 1.0.0
		mcwroofs: Macaw's Roofs 2.1.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.7
		mcwwindows: Macaw's Windows 2.0.3
		mendedminecarts: Mended Minecarts 1.0.1
		merchantmarkers: Merchant Markers 1.2.2
		microdurability: microDurability 0.3.6+1.17
			microdurability-core: microDurability Core 0.3.6
		midnightlib: MidnightLib 0.4.4
		minecarttweaks: Cammie's Minecart Tweaks 1.5
		minecraft: Minecraft 1.18.2
		minekea: Minekea 2.8.3
		missingwilds: Missing Wilds 1.0.1
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.7
		mob_catcher: Mob Catcher 1.1.27
		modmenu: Mod Menu 3.2.3
		monsters_in_the_closet: Monsters in the Closet 1.0.3+1.18
		morebannerfeatures: More Banner Features 1.1.3
		mores: Mores 1.3.0
		morevillagers: More Villagers 3.3.2
		mousetweaks: Mouse Tweaks 2.22
		moyai: Moyai 1.18.2-1.1.0
		multibeds: MultiBeds 1.2.5
		multiworldborders: Multi World Borders 1.4-fabric-1.18.2
		naturalist: Naturalist 1.0.4
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		nbtcrafting: NBT Crafting 2.1.3+mc1.18.2
		netherportalfix: NetherPortalFix 9.0.0
		nicemod: NiceMod - New blocks 1.1 - 1.18.2
		no-resource-pack-warnings: No Resource Pack Warnings 1.0.0
		no-telemetry: No Telemetry 1.4.0
		no_angled_brackets: No Angled Brackets 1.0.0
		no_nether_portal_overlay: No Nether Portal Overlay 1.0.2
		noexpensive: NoExpensive 1.18-Fabric-1.4.0
		nomorescore: No More Score 1.0.0
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughbreeding: Not Enough Breeding 1.18.2-1.0.0-fabric
		numismatic-overhaul: Numismatic Overhaul 0.2.2+1.18
			stacc: Stacc 1.3.0
		nyfsquiver: Nyf's Quivers Fabric-0.5.0-1.18.2
		observable: Observable 2.2.3
		ostoverhaul: Ost Overhaul 0.2.5
		our_villager_discounts: Our Villager Discounts 1.18.2+build.1
		owo: oωo 0.7.2+1.18
		particlerain: Particle Rain 2.0.0
		patchouli: Patchouli 1.18.2-71.1-FABRIC
		perfectaccuracy: Perfect Accuracy 1.2
		petnames-fabric: Pet Names (Fabric) 2.0
		phosphor: Phosphor 0.8.1
		piglessportals: Pigless Portals 1.1.0
		platforms: Platforms 1.2.5
		pollen: Pollen 1.4.6
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		polymorph: Polymorph 0.0.21-1.18.2
			cardinal-components-block: Cardinal Components API (blocks) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
		portal_accessibility: Nether Portal Accessibility 1.0.0-mc1.18.2
		presencefootsteps: Presence Footsteps 1.5.1
			kirin: Kirin UI 1.10.0
		prettybeaches: Pretty Beaches 7.0.0
		professions: Professions 0.2.3
			com_typesafe_config: config 1.4.1
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			octo-economy-api: Octo Economy API 1.0.1
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		puddles: Puddles 1.2.1
		puzzle: Puzzle 1.3.4-1.18
			puzzle-base: Puzzle Base 1.3.4-1.18
			puzzle-gui: Puzzle GUI 1.3.4-1.18
			puzzle-models: Puzzle Models 1.3.4-1.18
			puzzle-splashscreen: Puzzle Splash Screen 1.3.4-1.18
		puzzleslib: Puzzles Lib 3.3.5
		pyrotastic: Pyrotastic 1.18.2+0.0.2
		rainbegoneritual-fabric: Rain Be Gone Ritual (Fabric) 2.1
		reeses-sodium-options: Reese's Sodium Options 1.4.4+mc1.18.2-build.46
		repurposed_structures: Repurposed Structures 4.1.14+1.18.2
		reroll: Reroll 1.5.0-1.18.2
			omega-config-gui: Omega Config GUI 1.2.1-1.18.1
				cloth-config-lite: cloth-config-lite 2.0.6
		ridehud: Ride Hud 1.2.3+1.18.x
		rocks: This Rocks! 1.6.0
		roughlyenoughitems: Roughly Enough Items 8.3.519
		roughlyenoughprofessions: Roughly Enough Professions 1.0.1
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		roughlysearchable: Roughly Searchable 2.4.1+1.18.2
		scaffoldingdropsnearby-fabric: Scaffolding Drops Nearby (Fabric) 1.9
		sheepconsistency: Sheep Consistency 1.0.4
		shetiphiancore: ShetiPhianCore 1.2.13
			myron: Myron 1.6.3+1.18.1
		shinyhorses: Shiny Horses 1.0.0
		shulkerboxtooltip: Shulker Box Tooltip 3.0.10+1.18.2
			mm: Manningham Mills 2.3
		simplefog: Simple Fog Control 1.2.1
		skeletonfix: Skeleton Aiming Fix 1.1.2+1.18.2
		smitheesfoundry: Smithee's Foundry 1.3.3
			sussyconfig: Sussy Config 1.0.0
		sneakfix: Sneak Fix 1.0.0
		snowrealmagic: Snow! Real Magic! 4.1.1
		snowytrees: Snowy Trees 1.1.0
		sod: Sod 22.8.1
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.6
		spark: spark 1.9.11
		spelunker: Spelunker 1.4.1
		splash_milk: Splash Milk 1.0.2
		sponj: Sponj 1.1.0
		spyglass-improvements: Spyglass Improvements 1.2+mc1.18.2+fabric
		sspb: Sodium Shadowy Path Blocks 2.0.1
		statuseffecttimer: Status Effect Timer 1.1.1+1.18.1
		structures_compass: Structures Compass 1.18.2-1.4.2
		sturdy_carts: Sturdy Carts 1.0.1
		talkbubbles: Talk Bubbles 1.0.1
		taxfreelevels: Tax Free Levels 1.3
		thonkutil: ThonkUtil 2.14.1+1.18
			thonkutil-base: ThonkUtil Base 1.12.2+23c1dc2c60
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.3.2+9e23427060
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.19+9b80223760
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.0.14+9b80223760
			thonkutil-legacy: ThonkUtil Legacy 1.0.20+9b80223760
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.0.12+9b80223760
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.4.1+9b80223760
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.1.9+9b80223760
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.20+9b80223760
		thorium: thorium 1.2.1
		toms_storage: Tom's Simple Storage Mod 1.3.4
		toolstats: ToolStats 9.0.3
		tooltipscroller: Tooltip Texts Scroller 1.0.0
		tooltiptweaks: Tooltip Tweaks 1.0
		trade_cycling: Trade Cycling 1.18.2-1.0.2
		tradingpost: Trading Post 3.2.0
		transportables: Transportables 1.2
		trapperpelts: Trapper Pelts 1.0.1
		trashslot: TrashSlot 11.0.2
		trinketofundying: Trinket of Undying 2.0.2-1.18.2
		trinkets: Trinkets 3.3.1
		trulytreasures: Truly Treasures fabric-1.18.1-2.0.1
		twigs: Twigs 1.1.3-patch2+1.18.2
		unofficial_sodium_biome_blending_fix: Unofficial Sodium Biome Blending Fix 1.0.0+1.18.2
		valley: ValleyCraft 2.3.1-1.18.2
		vanillaconfig: Vanilla Config 1.2.1+1.18.x
		vanityslots: Vanity Slots 1.1.2
		variantbarrels: Variant Barrels 1.4.0
		variantcraftingtables: Variant Crafting Tables 2.4
		vehiclefix: VehicleFix 3.3
		villager-hats: Villager Hats 1.4.0
		visuality: Visuality 0.4.2
			goosik-config: goosik-config 0.2.0
			tlcosmetica: Cosmetica 0.4.0
		visualoverhaul: VisualOverhaul 4.1.0
		walllanterns: Lanterns Belong on Walls 1.3.0-1.18.x
		wandering_collector: Wandering Collector 1.1.2+mc1.18.2
		wandering_trapper: Wandering Trapper 1.2.0
		waterdripsound: Drip Sounds 1.18-0.3.0
		waveycapes: WaveyCapes 1.2.0
		waystones: Waystones 2.5.4
		weaponmaster: YDM's Weapon Master 1-18-x
		whatthebucket: WhatTheBucket 4.0.1
		wiredredstone: Wired Redstone 0.3.6+1.18.2
			graphlib: Graph Lib 0.2.4+1.18.2
			libmultipart_deps_container: LibMultiPart (Dependency Container) 0.7.3-pre.4
				libblockattributes_core: LibBlockAttributes (Core) 0.10.2
				libmultipart: LibMultiPart 0.7.3-pre.4
				libnetworkstack: Lib Network Stack 0.6.0
			team_reborn_energy: Energy 2.2.0
		wither_cage_fix: Wither Cage Fix 1.0.12
		woof: Woof 1.1.0-1.18
			com_github_llamalad7_mixinextras: MixinExtras 0.0.12
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8

**Comment by TropheusJ** [comment] 2022-08-04 19:09
likely duplicate of #452

**Closed as completed by TropheusJ** 2022-08-04 19:09 UTC
Labels: type: bug

**Comment by sirben99** [comment] 2022-08-04 19:20
Ohhh. I looked at the issue and it seems like the same log. Sorry to waste ur time with a dublicate!
