### ISSUE TITLE
Game crash when using deployer with attack

### ISSUE THREAD

**Issue by symoner66** [Fabricators-of-Create/Create#1185] opened 2023-11-05 21:53 UTC
### Describe the Bug

Everytime I use the deployer to attack skeletons, (i'm using the delpoyer as a xp farm) the game crashes. 

### Reproduction Steps

1.build xp farm with deployer on attack mode
2.wait for deployer to kill one mob
3.game crashes
...

### Expected Result

For the mob drops to fall into dropper and into a conveyor belt into storage containers.

### Crash Report or Log

---- Minecraft Crash Report ---- // Don't do that.  Time: 2023-11-05 15:43:27 Description: Ticking block entity  java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "capturedDrops" is null 	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activateInner(DeployerHandler.java:207) 	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activate(DeployerHandler.java:134) 	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.activate(DeployerBlockEntity.java:358) 	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.tick(DeployerBlockEntity.java:244) 	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15) 	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662) 	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716) 	at net.minecraft.class_1937.method_18471(class_1937.java:470) 	at net.minecraft.class_3218.method_18765(class_3218.java:390) 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) 	at net.minecraft.class_1132.method_3748(class_1132.java:105) 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) 	at java.base/java.lang.Thread.run(Thread.java:833)   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Server thread Stacktrace: 	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activateInner(DeployerHandler.java:207) 	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activate(DeployerHandler.java:134) 	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.activate(DeployerBlockEntity.java:358) 	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.tick(DeployerBlockEntity.java:244) 	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15) 	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662) 	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716) 	at net.minecraft.class_1937.method_18471(class_1937.java:470) 	at net.minecraft.class_3218.method_18765(class_3218.java:390)  -- Block entity being ticked -- Details: 	Name: create:deployer // com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity 	Block: Block{create:deployer}[axis_along_first=false,facing=south] 	Block location: World: (-42,-59,45), Section: (at 6,5,13 in -3,-4,2; chunk contains blocks -48,-64,32 to -33,319,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511) 	Block: Block{create:deployer}[axis_along_first=false,facing=south] 	Block location: World: (-42,-59,45), Section: (at 6,5,13 in -3,-4,2; chunk contains blocks -48,-64,32 to -33,319,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511) Stacktrace: 	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662) 	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716) 	at net.minecraft.class_1937.method_18471(class_1937.java:470) 	at net.minecraft.class_3218.method_18765(class_3218.java:390) 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) 	at net.minecraft.class_1132.method_3748(class_1132.java:105) 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) 	at java.base/java.lang.Thread.run(Thread.java:833)  -- Affected level -- Details: 	All players: 1 total; [class_3222['starrymonie'/318, l='ServerLevel[build world]', x=-39.73, y=-60.00, z=46.67]] 	Chunk stats: 2809 	Level dimension: minecraft:overworld 	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511) 	Level time: 300450 game time, 7298 day time 	Level name: build world 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true 	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false) 	Known server brands: fabric 	Removed feature flags:  	Level was modded: true 	Level storage version: 0x04ABD - Anvil Stacktrace: 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) 	at net.minecraft.class_1132.method_3748(class_1132.java:105) 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) 	at java.base/java.lang.Thread.run(Thread.java:833)  -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Windows 11 (amd64) version 10.0 	Java Version: 17.0.8, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 626935152 bytes (597 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB) 	CPUs: 12 	Processor Vendor: AuthenticAMD 	Processor Name: AMD Ryzen 5 7535HS with Radeon Graphics         	Identifier: AuthenticAMD Family 25 Model 68 Stepping 1 	Microarchitecture: Zen 3 	Frequency (GHz): 3.29 	Number of physical packages: 1 	Number of physical CPUs: 6 	Number of logical CPUs: 12 	Graphics card #0 name: AMD Radeon(TM) Graphics 	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002) 	Graphics card #0 VRAM (MB): 512.00 	Graphics card #0 deviceId: 0x1681 	Graphics card #0 versionInfo: DriverVersion=31.0.14060.0 	Graphics card #1 name: NVIDIA GeForce RTX 2050 	Graphics card #1 vendor: NVIDIA (0x10de) 	Graphics card #1 VRAM (MB): 4095.00 	Graphics card #1 deviceId: 0x25ad 	Graphics card #1 versionInfo: DriverVersion=31.0.15.3734 	Memory slot #0 capacity (MB): 16384.00 	Memory slot #0 clockSpeed (GHz): 4.80 	Memory slot #0 type: Unknown 	Virtual memory max (MB): 23765.37 	Virtual memory used (MB): 19645.23 	Swap memory total (MB): 8192.00 	Swap memory used (MB): 98.46 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	Fabric Mods:  		ambientsounds: AmbientSounds 5.2.21 		architectury: Architectury 9.1.12 		balm-fabric: Balm 7.1.4 		betterfpsdist: Better FPS distance Mod 1.20.1-4.0 		bettervillage: Better village 3.1.0 		cardinal-components: Cardinal Components API 5.2.2 			cardinal-components-base: Cardinal Components API (base) 5.2.2 			cardinal-components-block: Cardinal Components API (blocks) 5.2.2 			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2 			cardinal-components-entity: Cardinal Components API (entities) 5.2.2 			cardinal-components-item: Cardinal Components API (items) 5.2.2 			cardinal-components-level: Cardinal Components API (world saves) 5.2.2 			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2 			cardinal-components-world: Cardinal Components API (worlds) 5.2.2 		chunkloaders: Chunk Loaders 1.2.8 		cloth-config: Cloth Config v11 11.1.106 			cloth-basic-math: cloth-basic-math 0.6.1 		cookingforblockheads: Cooking for Blockheads 16.0.1 		create: Create 0.5.1-d-build.1161+mc1.20.1 			com_google_code_findbugs_jsr305: jsr305 3.0.2 			flywheel: Flywheel 0.6.9-1 			milk: Milk Lib 1.2.60 				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2 			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20 			porting_lib_base: Porting Lib Base 2.1.1127+1.20 				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20 				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20 			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20 			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20 				mm: Manningham Mills 2.3 			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20 				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20 			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20 			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20 			porting_lib_models: Porting Lib Models 2.1.1127+1.20 			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20 				porting_lib_core: Porting Lib Core 2.1.1127+1.20 				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20 			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20 				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20 				porting_lib_common: Porting Lib Common 2.1.1127+1.20 				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20 			porting_lib_tags: Porting Lib Tags 3.0 			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20 			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20 			reach-entity-attributes: Reach Entity Attributes 2.4.0 			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1 				porting_lib_data: Porting Lib Data 2.1.1090+1.20 				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20 					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20 		createutilities: Create Utilities 0.1.3+1.20.1 		creativecore: CreativeCore 2.11.5 			net_minecraftforge_eventbus: eventbus 6.0.3 		cupboard: cupboard 1.20.1-2.1 		doggomodoverhauled: Doggo Mod Overhauled 5.2.2 		elytraslot: Elytra Slot 6.3.0+1.20.1 		elytratrims: Elytra Trims 1.4.1 			com_github_llamalad7_mixinextras: MixinExtras 0.2.0 			conditional-mixin: conditional mixin 0.3.2 		exlinefurniture: Exline's Furniture 2.6.3 		extended_drawers: Extended Drawers 2.0.7+mc.1.20.1 			config_toolkit: ConfigToolkit 1.0.0 				io_determann_shadow-api-17: shadow-api-17 0.1.1 				net_fabricmc_javapoet: javapoet 0.1.0 			graphlib: Graph Lib 1.4.0+1.20 				kmodlib-overlay: KModLib Overlay 0.2.12+1.20 				libnetworkstack: Lib Network Stack 0.10.0 			noindium: No Indium? 1.1.0+1.20 			yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20 				com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT 				com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT 				com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT 				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT 				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT 				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT 				org_quiltmc_parsers_gson: gson 0.2.1 				org_quiltmc_parsers_json: json 0.2.1 		fabric-api: Fabric API 0.88.1+1.20.1 			fabric-api-base: Fabric API Base 0.4.30+7abfd51577 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977 			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77 			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777 			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77 			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577 			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77 			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77 			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377 			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377 			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77 			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77 			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77 			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77 			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77 			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677 			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77 			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177 			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777 			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677 			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877 			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077 			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277 			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.3+92a0d36777 			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.3+6bdb2ed077 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377 			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177 			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77 			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77 		fabric-language-kotlin: Fabric Language Kotlin 1.10.9+kotlin.1.9.0 			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0 			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0 			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0 			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0 			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0 			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3 			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3 			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0 			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0 			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0 			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0 		fabricloader: Fabric Loader 0.14.23 		farmersdelight: Farmer's Delight 1.20.1-1.4.2 		forgeconfigapiport: Forge Config API Port 8.0.0 		geckolib: Geckolib 4.2.3 			com_eliotlash_mclib_mclib: mclib 20 		handcrafted: Handcrafted 3.0.1 		immersive_paintings: Immersive Paintings 0.6.7+1.20.1 		indium: Indium 1.0.21+mc1.20.1 		indypets: IndyPets - Independent Pets 1.2.2-1.20 		iris: Iris 1.6.4 			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13 			org_anarres_jcpp: jcpp 1.4.14 			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1 		java: OpenJDK 64-Bit Server VM 17 		jei: Just Enough Items 15.2.0.27 		lambdynlights: LambDynamicLights 2.3.1+1.20.1 			pride: Pride Lib 1.2.0+1.19.4 			spruceui: SpruceUI 5.0.0+1.20 		libraryferret: Library ferret 4.0.0 		luphieclutteredmod: Cluttered 2.1.0+1.20.1 		malilib: MaLiLib 0.16.3 		mca: Minecraft Comes Alive 7.5.8+1.20.1 		mcwfences: Macaw's Fences and Walls 1.0.7 		minecraft: Minecraft 1.20.1 		modmenu: Mod Menu 7.2.2 		moonlight: Moonlight 1.20-2.8.49 		naturalist: Naturalist 4.0.0 		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric 		patchouli: Patchouli 1.20.1-81-FABRIC 			fiber: fiber 0.23.0-2 		presencefootsteps: Presence Footsteps 1.9.0 			kirin: Kirin UI 1.15.0 		resourcefullib: Resourceful Lib 2.1.11 			com_teamresourceful_bytecodecs: bytecodecs 1.0.2 			com_teamresourceful_yabn: yabn 1.0.3 		scarecrowsterritory: Scarecrows' Territory 1.1.10 		sliceanddice: Create Slice & Dice 3.0.0 		sodium: Sodium 0.4.10+build.27 		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a 		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.15 		supplementaries: Supplementaries 1.20-2.6.12 		terrablender: TerraBlender 3.0.0.167 		travelersbackpack: Traveler's Backpack 1.20.1-9.1.6 		trinkets: Trinkets 3.7.1 		veinmining: Vein Mining 1.2.1+1.20.1 			spectrelib: SpectreLib 0.13.14+1.20.1 				com_electronwill_night-config_core: core 3.6.5 				com_electronwill_night-config_toml: toml 3.6.5 		waystones: Waystones 14.0.2 		wildlife: Wildlife 1.19.2-2.2 	Loaded Shaderpack: (off) 	NEC status: No NEC detected 	Flywheel Backend: GL33 Instanced Arrays 	Server Running: true 	Player Count: 1 / 8; [class_3222['starrymonie'/318, l='ServerLevel[build world]', x=-39.73, y=-60.00, z=46.67]] 	Data Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, Supplementaries Generated Pack 	Enabled Feature Flags: minecraft:vanilla 	World Generation: Stable 	Type: Integrated Server (map_client.txt) 	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric' 	Launched Version: fabric-loader-0.14.23-1.20.1

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by mcbeaniee** [comment] 2023-11-15 04:01
i am also having this issue.

**Comment by adaliszk** [comment] 2023-11-15 05:30
Can confirm that the issue also exists on 1.20.1.

It seems to me that what happens is that once the deployer kills something, it will collect the drops into itself which then you can chute/hopper out from it after your server rebooted. While I like this mechanic that the items don't actually spawn but get collected, it feels a bit weird because normally the internal inventory slot is for items to use by the deployer.

One workaround I want to test is to hopper swords into the deployer so that it cannot pick up the drops from the mobs.

**Comment by TropheusJ** [comment] 2023-12-18 04:10
duplicate of #1096

**Closed as completed by TropheusJ** 2023-12-18 04:10 UTC
Labels: type: bug
