### ISSUE TITLE
(1.18.2) ticking block entity crash

### ISSUE THREAD

**Issue by TungstenWolf** [Fabricators-of-Create/Create#747] opened 2023-01-08 16:02 UTC
### Describe the Bug

I was not online for this, however a player on the server was building a steam engine and now the game crashes when trying to load those chunks 
The server is also running a custom pack on curseforge named "Fabri-pack" 
This below is a short snippet from the log 

Time: 1/8/23, 2:38 AM
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "java.util.function.Predicate.test(Object)" because "this.validator" is null
	at io.github.fabricators_of_create.porting_lib.transfer.fluid.FluidTank.isFluidValid(FluidTank.java:39)
	at io.github.fabricators_of_create.porting_lib.transfer.fluid.FluidTank.insert(FluidTank.java:44)
	at com.simibubi.create.content.contraptions.fluids.OpenEndedPipe$OpenEndFluidHandler.extract(OpenEndedPipe.java:323)
	at com.simibubi.create.content.contraptions.fluids.OpenEndedPipe$OpenEndFluidHandler.extract(OpenEndedPipe.java:249)
	at com.simibubi.create.content.contraptions.fluids.FluidNetwork.tick(FluidNetwork.java:195)
	at com.simibubi.create.content.contraptions.fluids.PipeConnection.manageFlows(PipeConnection.java:149)
	at com.simibubi.create.content.contraptions.fluids.FluidTransportBehaviour.tick(FluidTransportBehaviour.java:131)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1067)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntity.forEachBehaviour(SmartTileEntity.java:171)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntity.tick(SmartTileEntity.java:76)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:831)

### Reproduction Steps

It's really unknown to me, however the player built a steam engine and in the crash log it looks to be something about validation with fabricators

### Expected Result

For the server to not crash when those chunks are loaded

### Crash Report or Log

https://pastebin.com/PtWXPK1j

### Operating System

It's using pebblehost so I assume windows server edition

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

The entire list is in this pack here https://www.curseforge.com/minecraft/modpacks/fabri-pack
Latest pack version

**Comment by TropheusJ** [comment] 2023-01-08 20:04
duplicate of #696
fixed in dev
caused by TF loading an older version of Porting Lib. Either remove TF or manually install [this version](https://github.com/Fabricators-of-Create/Porting-Lib/actions/runs/3799435823) as a temporary fix.

**Closed as completed by TropheusJ** 2023-01-08 20:04 UTC
Labels: type: bug
