### ISSUE TITLE
Cannot compile shader because 'flywheel:oriented' is not recognized. Crash after trying to join the world

### ISSUE THREAD

**Issue by aerokero** [Fabricators-of-Create/Create#559] opened 2022-09-20 09:34 UTC
### Describe the Bug

https://mclo.gs/Tj130U8

The game crashes almost instantly after loading in the world

### Reproduction Steps

I have no idea how I could reproduce the problem. I could join the game last night and I didn't crash. I have also not changed nor updated any mods. All I can say is that I disconnected while being in a boat

### Expected Result

The game will crash with the following error:

java.lang.NullPointerException: Cannot compile shader because 'flywheel:oriented' is not recognized.

### Crash Report or Log

https://mclo.gs/Tj130U8

### Operating System

Windows 11

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

### Other Mods

- ad_astra 1.0.1  - additionaladditions 4.0.5  - additionalentityattributes 1.0.0 1.18.2 via spectrum  - adorn 3.5.0 1.18.2  - advanced_runtime_resource_pack 0.5.7 via missingwilds  - advancementinfo 1.18.2-fabric0.47.10-1.3.1  - adventurez 1.4.11  - ae2 11.1.7  - ae2things 1.1.0-beta.8  - ambientsounds 5.0.16  - amecs 1.3.8 mc.1.18.2  - amecsapi 1.3.5 mc22w06a via amecs  - animatica 0.5 1.18.2  - antighost 1.18.2-fabric0.47.10-1.1.4  - arcanus 1.29  - architects_palette 2.2  - architectury 4.9.83  - artifacts 7.0.3 fabric  - badpackets 0.1.2  - balm-fabric 3.2.0 0  - bannerpp 2.0.6-teb.1 mc.1.18.2 via spectrum  - bclib 1.4.7  - beaconoverhaul 1.6.0 1.18.2  - betterdeserttemples 1.18.2-Fabric-1.3.1  - betterdungeons 1.18.2-Fabric-2.1.0  - betterf3 1.2.5  - bettermounthud 1.1.4  - betterpingdisplay 1.1.1  - betterstrongholds 1.18.2-Fabric-2.1.1  - betterwitchhuts 1.18.2-Fabric-1.0.1  - bewitchment 1.18-23  - biomemakeover 1.18.2-1.4.31  - bitsandchisels 2.6.13  - blockus 2.4.8 1.18.2  - blossom 1.0.5  - blue_endless_jankson 1.2.1 via jankson  - bookshelf 13.2.50  - borderlessmining 1.1.2 1.18.2  - bosses_of_mass_destruction 1.3.8-1.18.2  - botania 1.18.2-435-FABRIC  - breakfree 1.0.1  - cacao 1.2  - caffeineconfig 1.0.0 1.17 via sodium-extra  - capes 1.3.1 1.18.2  - cardinal-components 4.2.0  - cardinal-components-base 4.2.0 via cardinal-components  - cardinal-components-block 4.2.0 via cardinal-components  - cardinal-components-chunk 4.2.0 via cardinal-components  - cardinal-components-entity 4.2.0 via cardinal-components  - cardinal-components-item 4.2.0 via cardinal-components  - cardinal-components-level 4.2.0 via cardinal-components  - cardinal-components-scoreboard 4.2.0 via cardinal-components  - cardinal-components-world 4.2.0 via cardinal-components  - carrier 1.10.0  - ce 1.1.5  - cem 0.7.1  - chalk 2.0.1 1.18.2  - chat_heads 0.6.0  - cherishedworlds 2.0.2-1.18  - chipped 1.2  - chisel 1.4.5  - citresewn 1.1.1 1.18.2  - citresewn-defaults 1.1.1 1.18.2 via citresewn  - cloth-api 3.2.64 via rpgdifficulty  - cloth-basic-math 0.6.1 via cloth-config  - cloth-client-events-v0 3.2.64 via cloth-api  - cloth-common-events-v1 3.2.64 via cloth-api  - cloth-config 6.3.81  - cloth-config-lite 2.0.6 via omega-config-gui  - cloth-datagen-api-v1 3.2.64 via cloth-api  - cloth-scissors-api-v1 3.2.64 via cloth-api  - cloth-utils-v1 3.2.64 via cloth-api  - com_electronwill_night-config_core 3.6.5 via globaldataandresourcepacks  - com_electronwill_night-config_toml 3.6.5 via globaldataandresourcepacks  - com_eliotlash_mclib_mclib 18 via geckolib3  - com_eliotlash_molang_molang 18 via geckolib3  - com_flowpowered_flow-math 1.0.3 via dimdoors  - com_github_dimensionaldevelopment_poly2tri_java 0.1.1 via dimdoors  - com_github_llamalad7_mixinextras 0.0.11 via registrate-fabric  - com_github_luben_zstd-jni 1.5.2-2 via dashloader  - com_google_code_findbugs_jsr305 3.0.2 via create  - com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps  - com_typesafe_config 1.4.1 via croptopia  - com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton  - companion 2.0.1  - completeconfig 1.0.0 via cem  - conjuring 1.0.22 1.18  - consistency_plus 0.5.0 1.18.2  - continuity 2.0.1 1.18.2  - cookingforblockheads 12.1.0  - coxinhautilities 1.4.2 1.18.2  - create 0.5.0d-731  - create_crystal_clear 0.1  - createaddition ${version}  - createplus 1.0  - creativecore 2.6.12  - croptopia 2.1.0  - crowdin-translate 1.4 1.18.2 via antighost  - cull-less-leaves 1.0.1  - curse_maven_wthit-3707010 440979 via dimdoors  - custom-fog 2.2.0-1.18.2  - dankstorage 1.18.2-3.7.1  - dark-enchanting 1.0.0 1.18.2  - darkutils 10.0.5  - dashloader 4.1.3 1.18  - dawn 3.3.2  - dcch 1.0  - de_poiu_apron_apron 2.1.1 via mconfig  - decorative_blocks 2.1.1  - dev_isxander_settxi 2.1.1 via zoomify  - dev_quantumfusion_hyphen 0.2.2 via dashloader  - dev_quantumfusion_taski 1.1.0 via dashloader  - dimdoors 4.0.4  - dml-refabricated 1.18.2  - dml-refabricated-base 1.18.2 via dml-refabricated  - dml-refabricated-events 1.18.2 via dml-refabricated  - dml-refabricated-modular-armor 1.18.2 via dml-refabricated  - dml-refabricated-rei 1.18.2 via dml-refabricated  - dragonloot 1.1.0  - dripstone_fluid_lib 1.2.0 via milk  - dusk 1.18.2-2.1  - dynamicfps 2.1.0  - earthtojavamobs 1.8.0 1.18.2  - edenring 0.5.2  - ellemes_container_lib 1.4.0-beta.2  - elytratrinket 3.0.0-1.18.1  - enhancedcelestials 2.0.7  - entity_texture_features 4.0.2  - entityculling 1.5.1  - error_notifier 1.0.9 via roughlyenoughitems  - expandability 6.0.0 via artifacts  - expandedstorage 7.4.0-beta.4  - extended_drawers 1.3.3 mc.1.18.2  - fabric 0.58.0 1.18.2  - fabric-api-base 0.4.4 d7c144a860 via fabric  - fabric-api-lookup-api-v1 1.6.2 2373a54560 via fabric  - fabric-biome-api-v1 8.0.6 651bcc5960 via fabric  - fabric-blockrenderlayer-v1 1.1.12 3ac43d9560 via fabric  - fabric-command-api-v1 1.1.9 d7c144a860 via fabric  - fabric-commands-v0 0.2.8 b4f4f6cd60 via fabric  - fabric-containers-v0 0.1.23 d7c144a860 via fabric  - fabric-content-registries-v0 3.1.1 c85f2e3860 via fabric  - fabric-convention-tags-v1 1.0.1 474e4f7960 via fabric  - fabric-crash-report-info-v1 0.2.1 ee261a3e60 via fabric  - fabric-data-generation-api-v1 3.0.1 9fcb91d260 via fabric  - fabric-dimensions-v1 2.1.20 489d6f8260 via fabric  - fabric-entity-events-v1 1.4.8 d7c144a860 via fabric  - fabric-events-interaction-v0 0.4.19 d7c144a860 via fabric  - fabric-events-lifecycle-v0 0.2.19 d7c144a860 via fabric  - fabric-game-rule-api-v1 1.0.13 d7c144a860 via fabric  - fabric-item-api-v1 1.5.2 17cbbd4360 via fabric  - fabric-item-groups-v0 0.3.14 91896a4960 via fabric  - fabric-key-binding-api-v1 1.0.12 54e5b2ec60 via fabric  - fabric-keybindings-v0 0.2.10 b4f4f6cd60 via fabric  - fabric-language-kotlin 1.8.3 kotlin.1.7.10  - fabric-lifecycle-events-v1 2.1.0 cc71601c60 via fabric  - fabric-loot-api-v2 1.1.0 1997ad1260 via fabric  - fabric-loot-tables-v1 1.1.2 e747827960 via fabric  - fabric-mining-level-api-v1 2.1.4 cc71601c60 via fabric  - fabric-models-v0 0.3.6 d7c144a860 via fabric  - fabric-networking-api-v1 1.0.23 2d30af4b60 via fabric  - fabric-networking-v0 0.3.10 b4f4f6cd60 via fabric  - fabric-object-builder-api-v1 2.1.3 032c981d60 via fabric  - fabric-particles-v1 0.2.12 526dc1ac60 via fabric  - fabric-permissions-api-v0 0.1-SNAPSHOT via bewitchment  - fabric-registry-sync-v0 0.9.10 0d9ab37260 via fabric  - fabric-renderer-api-v1 0.4.13 d882b91560 via fabric  - fabric-renderer-indigo 0.5.3 41a02c8a60 via fabric  - fabric-renderer-registries-v1 3.2.11 b4f4f6cd60 via fabric  - fabric-rendering-data-attachment-v1 0.3.7 d7c144a860 via fabric  - fabric-rendering-fluids-v1 2.0.2 54e5b2ec60 via fabric  - fabric-rendering-v0 1.1.13 b4f4f6cd60 via fabric  - fabric-rendering-v1 1.10.7 54e5b2ec60 via fabric  - fabric-resource-conditions-api-v1 2.0.3 91b7aa6660 via fabric  - fabric-resource-loader-v0 0.5.2 446e059560 via fabric  - fabric-screen-api-v1 1.0.10 d882b91560 via fabric  - fabric-screen-handler-api-v1 1.2.2 1f6558e860 via fabric  - fabric-textures-v0 1.0.12 3ac43d9560 via fabric  - fabric-transfer-api-v1 1.6.3 f4563ac860 via fabric  - fabric-transitive-access-wideners-v1 1.1.0 e747827960 via fabric  - fabricloader 0.14.9  - fabricskyboxes 0.5.5  - fabrishot ${version}  - fake-player-api 0.3.0 via create  - farmersdelight 1.18.2-1.2.1  - farmingforblockheads 10.0.2  - farsight 1.18-1.9  - fastload 1.2.0  - feature_nbt_deadlock_be_gone 2.0.0 1.18.2-rc1  - ferritecore 4.2.1  - fiber 0.23.0-2 via botania  - flywheel 0.6.4-30 via create  - forge_tags 2.1 via create  - forgeconfigapiport 3.2.0 via create  - forgetmechunk 1.0.4-1.18.X-1.19.X  - friendsandfoes 1.4.5  - ftblibrary 1802.3.6-build.140  - ftbquests 1802.3.8-build.106  - ftbteams 1802.2.6-build.67  - gateofbabylon 1.7.0-1.18.2  - geckolib3 3.0.60  - globaldataandresourcepacks 1.12.1  - go-fish 1.5.0-1.18.2  - goosik-config 0.2.0 via visuality  - graphlib 0.2.4 1.18.2 via extended_drawers  - harvest_scythes 2.5.1  - here-be-no-dragons 1.0.0 via twilightforest  - holdthatchunk 1.0.3  - hologram-api 0.2.1 1.18-pre5 via universal-graves  - iknowwhatimdoing 4.1.0  - immersive_weathering 2.5.6  - impersonate 2.4.1 via bewitchment  - incubus_core 1.7.1 via spectrum  - indium 1.0.7 mc1.18.2  - indrev 1.14.0-BETA  - infusion_table 1.1.0  - inmis 2.6.0-1.18.2  - inventoryprofilesnext 1.7.2  - io_leangen_geantyref_geantyref 1.3.11 via croptopia  - isxander-main-menu-credits 1.1.1  - itemfilters 1802.2.7-build.33  - itemmodelfix 1.0.3 1.18  - jankson 4.0.0 j1.2.0 via libgui  - java 17  - javax_annotation_javax_annotation-api 1.3.2 via twilightforest  - kanos_config 0.3.1 1.14.4-1.19 via pehkui  - kibe 1.9.9-BETA 1.18  - krypton 0.1.9  - ktdatataglib 1.6.5 1.18.2 via dml-refabricated  - kubejs 1802.5.5-build.546  - lambdabettergrass 1.2.4 1.18  - lambdynlights 2.1.0 1.17  - languagereload 1.2.1  - lazydfu 0.1.2  - libblockattributes_core 0.10.0 via indrev  - libblockattributes_fluids 0.10.0 via indrev  - libblockattributes_items 0.10.0 via indrev  - libgui 5.4.0 1.18.2 via dark-enchanting  - libninepatch 1.1.0 via libgui  - lithium 0.7.10  - logbegone 1.0.1  - lovely_snails 1.0.4 1.18  - maelstrom_library 1.2.4-1.18.2 via bosses_of_mass_destruction  - magna 1.7.0-1.18-pre1 via indrev  - matrix 1.0.0 via dimdoors  - mconfig 1.2.0 via extended_drawers  - me_hypherionmc_simplerpc_simple-rpc-common 4.0.3 via simple-rpc  - memoryleakfix 1.18.2-0.7.0  - midnightcontrols 1.5.0 1.18  - midnightlib 0.4.4 via midnightcontrols  - milk 0.3.2 via create  - minecraft 1.18.2  - minimalmenu 1.18.2-0.1.5  - missingwilds 1.1.0  - mixintrace 1.1.1 1.17  - mm 2.3 via friendsandfoes  - modern_industrialization 1.2.2  - modmenu 3.2.3  - morechathistory 1.1.0  - mostructures 1.4.2 1.18.2  - multipart_entities 1.1.5-1.18.2 via bosses_of_mass_destruction  - naturalist 1.1.1  - naturescompass 1.18.2-2.0.3-fabric  - nethermap 2.0.2-1.18.2  - no-telemetry 1.4.0  - nofade 1.18-2.0.1  - noindium 1.0.2 1.18.2 via ae2  - nostalgic_tweaks 1.0.7  - omega-config 1.2.3-1.18.1 via capes  - omega-config-gui 1.2.3-1.18.1 via coxinhautilities  - onastick 2.0.0  - optigui 1.1.0  - org_apache_commons_commons-text 1.9 via optigui  - org_aperlambda_lambdajcommon 1.8.1 via midnightcontrols  - org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin  - org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin  - org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin  - org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin  - org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin  - org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin  - org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin  - org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin  - org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin  - org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin  - org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin  - org_jgrapht_jgrapht-core 1.1.0 via dimdoors  - org_joml_joml 1.10.2 via sodium  - org_spongepowered_configurate-core 4.1.2 via croptopia  - org_spongepowered_configurate-hocon 4.1.2 via croptopia  - owo 0.7.2-no-cme 1.18  - packet_tweaker 0.3.0 1.18.2 via polymer  - patchouli 1.18.2-66-FABRIC-SNAPSHOT via modern_industrialization  - pehkui 3.4.2 1.14.4-1.19.2  - piercingpaxels 1.0.3 1.18.x  - placeholder-api 1.1.3 1.17.1 via universal-graves  - plasmo_voice 1.2.19  - playerabilitylib 1.5.0 via bewitchment  - polymer 0.2.0-rc.2 1.18.2 via universal-graves  - polymer-legacy 0.1.9 0.2.0-rc.2 1.18.2 via polymer  - polymorph 0.0.21-1.18.2  - porting_lib 1.2.460-beta 1.18.2-dev.cca931b via create  - pride 1.1.0 1.17 via lambdynlights  - probablychests 0.5.4-1.18.2  - programmerartinjector 1.2.1 via spectrum  - puzzle 1.4.0-1.18  - puzzle-base 1.4.0-1.18 via puzzle  - puzzle-gui 1.4.0-1.18 via puzzle  - puzzle-models 1.4.0-1.18 via puzzle  - puzzle-splashscreen 1.4.0-1.18 via puzzle  - puzzleslib 3.3.5  - raised 1.1.2  - reach-entity-attributes 2.1.1 via beaconoverhaul  - reasonable-sorting 2.0.2  - reborncore 5.2.0  - reeses-sodium-options 1.4.7 mc1.18.2-build.58  - registrate-fabric MC1.18.2-1.1.4 via create  - repurposed_structures 4.1.14 1.18.2  - revelationary 1.0.2  - rhino 1802.2.0-build.232  - roughlyenoughitems 8.3.529  - roughlyenoughprofessions 1.0.2  - roughlyenoughresources 2.5.0  - roughlysearchable 2.4.1 1.18.2  - rpgdifficulty 1.0.12  - satin 1.7.2 via spectrum  - seasons 1.4-BETA 1.18  - serialization_hooks 0.3.23 via porting_lib  - server_translations_api 1.4.12 1.18.2 via universal-graves  - settxicloth 1.0.2 via zoomify  - sgui 1.0.2 1.18.2 via universal-graves  - simple-rpc 3.1.1  - smoothboot 1.18.2-1.7.0  - sodium 0.4.1 build.15  - sodium-extra 0.4.10 mc1.18.2-build.63  - someforgepatchesported 1.0.3  - spark 1.9.11  - spectrum 1.5.7-1.18.2-magic  - spirit 2.1.8  - spruceui 3.3.3 1.18 via lambdabettergrass  - stacc 1.3.2 via stacker  - stacker 3.0.2-1.18.2  - starlight 1.0.2 fabric.89b8d9f  - step-height-entity-attribute 1.0.0 via artifacts  - stonecutter_recipe_tags 3.0.1 1.18.bc850d5.fabric via consistency_plus  - taxfreelevels 1.3.3  - team_reborn_energy 2.2.0 via ad_astra  - techreborn 5.2.0  - terrablender **.**.**.**  - terraform-biome-remapper-api-v1 3.1.0 via traverse  - terraform-config-api-v1 3.1.0 via traverse  - terraform-surfaces-api-v1 3.1.0 via traverse  - terraform-tree-api-v1 3.1.0 via traverse  - terraform-wood-api-v1 3.1.0 via traverse  - tlcosmetica 0.4.0 via visuality  - tooltipfix 1.0.4-1.18  - totw_additions 1.2.1  - travelersbackpack 1.18.2-7.1.7  - traverse 5.1.3  - traverse-client 5.1.3 via traverse  - traverse-common 5.1.3 via traverse  - traverse-worldgen 5.1.3 via traverse  - trinketofundying 2.0.2-1.18.2  - trinkets 3.3.1  - twigs 1.1.3-patch2 1.18.2  - twilightforest 4.1.268  - universal-graves 2.0.3 1.18.2  - valley 2.3.1-1.18.2  - visuality 0.4.2  - vmp 0.2.0 beta.3.98  - waystones 2.5.5 mc1.18.2  - wthit 4.13.3  - xaerominimap 22.14.1  - xaeroworldmap 1.27.0  - xp_storage 1.4.3 1.18  - xp_storage_trinkets 0.1 1.18  - xps 0.4.6-r 1.18.2-Fabric  - xps_additions 0.1.4-r 1.18.2-Fabric  - yosbr 0.1.1  - yungsapi 1.18.2-Fabric-2.0.8  - yungsextras 1.18.2-Fabric-2.1.0  - zoomify 1.6.0

**Comment by TropheusJ** [comment] 2022-09-20 12:43
duplicate of #461

**Closed as completed by TropheusJ** 2022-09-20 12:43 UTC
Labels: type: bug
