### ISSUE TITLE
Compatibility issue with first person mod

### ISSUE THREAD

**Issue by marvin2309** [Fabricators-of-Create/Create#979] opened 2023-06-26 22:35 UTC
### Describe the Bug

When playing with Create (create-fabric-0.5.1-b-build.1079+mc1.19.2) and First-Person (firstperson-fabric-2.2.3-mc1.19.2) a render issue of the create hud of create items such as the extended grip appears (First Image). When playing with the forge version and create (create-1.19.2-0.5.1.b) and First-Person (firstperson-forge-2.2.3-mc1.19.2) this issue does not appear.

### Reproduction Steps

See above.

### Expected Result

The Extended Grip should not render twice with the fabric version.

### Screenshots and Videos

Fabric Version
![2023-06-27_00 05 58](https://github.com/Fabricators-of-Create/Create/assets/70077396/5d892cbd-b859-49f2-b12e-f99fbde7ada5)

Forge Version
![2023-06-26_23 59 03](https://github.com/Fabricators-of-Create/Create/assets/70077396/9531f6e4-232d-4407-97ca-12a5c6db5dde)

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

Fabric, First-Person Mod (See Above)

**Comment by electricsteve** [comment] 2023-06-27 12:15
duplicate of #905

**Closed as completed** 2023-07-02 23:22 UTC
Labels: type: bug
