### ISSUE TITLE
Shafts Apear in two rotation when placing them down

### ISSUE THREAD

**Issue by chrishere2156** [Fabricators-of-Create/Create#110] opened 2022-01-24 13:47 UTC
### Describe the Bug

after placing a shaft down at any rotation every 1 block the shaft appears at two rotations at once in the same block. this rotation is visible after place a belt over them.

### Reproduction Steps

1. load Minecraft
2. new savegame
3. place multiple shafts next to each other
4. see that it is not placed correctly.
...

### Expected Result

the shaft appears as one rotation after placing.

### Screenshots and Videos

![2022-01-24_13 13 31](https://user-images.githubusercontent.com/63650606/150791282-966626a0-d65f-421d-9908-b3780dac1313.png)
![2022-01-24_13 44 34](https://user-images.githubusercontent.com/63650606/150793973-85418925-4867-4aca-afa6-84935d19eeec.png)

### Crash Report or Log

https://pastebin.com/aw1PpTKf

### Operating System

Windows 10

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

Mods I had activated on curse forge:
Sodium
Fabric Loader
Create mod 0.4c

**Comment by TropheusJ** [comment] 2022-01-24 13:56
Install indium, duplicate of #54

**Closed as completed by TropheusJ** 2022-01-24 13:56 UTC
Labels: type: bug
