### ISSUE TITLE
[CRITICAL] Multiplayer seat glitching

### ISSUE THREAD

**Issue by redstonerti** [Fabricators-of-Create/Create#705] opened 2022-12-26 14:30 UTC
### Describe the Bug

I'm not even sure how to describe this bug. I have an elevator with two seats, and my friend tries to get on one seat. He right clicks, but on his screen, he's not on the seat. He right clicks again, and then he's on the seat. Then he somehow gets off, but he's still on the seat on my screen. I can punch him while he's on the seat, and he takes damage wherever it is he is on his screen. It's very weird.

If he crouches again, on his screen he gets teleported back to the seat and gets out of the seat, and on my screen he gets out of the seat and I can see him move again

### Reproduction Steps

1. Place a seat
2. Have your friend right click to get on
3. Have them crouch to get off

### Expected Result

Him getting on the seat on both screens and exiting on both screens

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/48157961/209558131-c41cdb70-71d8-49d4-a6b3-d42ba58cae9d.png)
![image](https://user-images.githubusercontent.com/48157961/209558139-f555fac5-ef6b-43a2-b238-c9beb1e9640e.png)

Here's a video with more detail:
https://streamable.com/kbxfia

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment] 2022-12-27 09:08
can't reproduce. maybe fixed in dev, maybe an incompat.

**Comment by IThundxr** [comment] 2024-05-06 01:24
Open a new issue if this still occurs

**Closed as completed by IThundxr** 2024-05-06 01:24 UTC
Labels: type: bug
