### ISSUE TITLE
new updates are acting quite strange

### ISSUE THREAD

**Issue by 444wa** [Fabricators-of-Create/Create#543] opened 2022-09-03 06:35 UTC
Hey yall so i had installed create before September in a client for fabric 1.18.2, and everything was perfectly fine, until recently, i saw there was an update from September first, which i had promptly installed. but this started making the mod wierd, A small amount of the items were invisible, and every time i had opened the Ponderer, it would crash my game. i recently installed the most recent update you guys just put out, but nothing seems to have been changed or fixed. Do you think i could be missing something? i swear i have the Create mod alongside fabric API, which is all it needs, right? Ive even tried copy-pasting the older version to this newer modpack i had created, but the same issue was still there. Really could use some guidance on this. Thank you in advance. 
![image](https://user-images.githubusercontent.com/104756144/188259004-efec8559-2c7a-4996-afb6-f63506a3b8d3.png)

**Comment by TropheusJ** [comment] 2022-09-03 06:56
send the log. ponder should be fixed as of an hour ago

**Comment by 444wa** [comment] 2022-09-03 16:56
yup heres the log from one of the first crash es. youre right, it was fixed and thats really good. but the same bug with the invisible items keeps happening, and i hope this can be fixed too.

heres the crash log from the first ponderer crash in the 9/1 update, i hope itll help

[crash-2022-09-02_17.49.56-client.txt](https://github.com/Fabricators-of-Create/Create/files/9483024/crash-2022-09-02_17.49.56-client.txt)

**Comment by TropheusJ** [comment] 2022-09-03 17:01
yeah that crash was fixed. For the invisible items you'll need to narrow down which mod causes it.

**Comment by 444wa** [comment] 2022-09-03 17:03
alright sure. is it okay if i send the list of mods in the modpack so you could help me narrow it down? im not too good at this kind of stuff

**Comment by TropheusJ** [comment] 2022-09-03 17:10
The list is already in the log. I looked through it and didn’t see any suspects. The best way to figure it out is a binary split.

Split the mods into 2 groups and test each. If the problem happens, split again and repeat. If it doesn’t happen, check the other group. The goal is to figure out which set of mods together causes it.

**Comment by 444wa** [comment] 2022-09-03 18:18
hey man, i just did this. i think i narrowed it down to a mod called The Corners, that makes the items disappear. I just don't understand why, though. The Corners is a mainly new dimensions kind of mod, and it is puzzling as to why it makes Create items invisible. Maybe I'm not understanding how this works from a coding perspective, but do you think there is a way we could fix this? 
Everything else in my modpack is turned on except for The Corners, and that's when i was able to see the Create items again
![image](https://user-images.githubusercontent.com/104756144/188283361-16af4bd8-eb84-4e07-8b95-e72cc6e72a07.png)

**Comment by TropheusJ** [comment] 2022-09-03 19:25
ah, duplicate of #349. there's no way to fix it.

**Closed as completed by TropheusJ** 2022-09-03 19:25 UTC
