### ISSUE TITLE
Server crashes due to ticking block entity (create:brass_funnel)

### ISSUE THREAD

**Issue by Pianospa** [Fabricators-of-Create/Create#499] opened 2022-08-06 23:43 UTC
### Describe the Bug

The brass funnel block switched position to WEST and started dropping brass funnels from an air block.

### Reproduction Steps

1. Have a double chest filled with create:incomplete_track
2. Connect a funnel to it
3. Now it switches position to west and starts dropping an unending amount of brass funnels from an air block
...

### Expected Result

To unfill all Incomplete tracks from the double chest, and once it stopped it would cease dropping.

### Crash Report or Log

https://gist.github.com/Pianospa/823bb82f688ca2b38a281d8523fc3c20

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment] 2022-08-26 21:03
can't reproduce, can you send a screenshot?

**Comment by lennertekas** [comment] 2022-09-25 08:36
[crash-2022-09-24_18.33.41-server.txt](https://github.com/Fabricators-of-Create/Create/files/9640308/crash-2022-09-24_18.33.41-server.txt)
Hi, i had the same issue, i hope this helps
![2022-09-25_10 30 15](https://user-images.githubusercontent.com/43001353/192134907-61e8da88-e301-4bdc-8a06-f8151ae52976.png)
![2022-09-25_10 30 23](https://user-images.githubusercontent.com/43001353/192134908-b4c3201e-fa72-4384-8055-dc36ad022829.png)
![2022-09-25_10 30 29](https://user-images.githubusercontent.com/43001353/192134909-57fb0ef5-20bb-4a09-b3cb-ff207179a241.png)

For me it manifested in the following setup.
The brass belt funnel with 9 blaze cakes as a filter was just before the crash set to 9, but i had not given it an item. Iam not sure if i right clicked it with an empty hand, but after i set it to 9 and the blaze cakes where gone out of the item vault, my game crashed and i could not start it up again.

**Comment by TropheusJ** [comment] 2022-11-21 00:24
closing in favor of #561

**Closed as completed by TropheusJ** 2022-11-21 00:24 UTC
Labels: type: bug
