### ISSUE TITLE
After removing items from moving contraption by shift-clicking, the contraption cannot be disassembled properly and could duplicated

### ISSUE THREAD

**Issue by RanolP** [Fabricators-of-Create/Create#1264] opened 2024-01-06 12:25 UTC
### Describe the Bug

Extract an item from a moving contraption assembled by shift-clicking, and disassemble the contraption. It crashes (or logs an error) with the message `java.lang.IllegalArgumentException: Transfer variant may not be blank.`.

### Reproduction Steps

1. Construct any moving contraption with an attached chest containing some items (maybe reproducible with other storage blocks e.g. barrel) - I had reproduced w/ windmill (not crashes, but could lead to dupe bug in Singleplayer), minecart (crashes, see the comment from https://github.com/Fabricators-of-Create/Create/issues/1211#issuecomment-1842518942 for vids), gantry (crashes)
3. Remove item from the inventory by shift-clicking
4. Disassemble the contraption

### Expected Result

It should be disassembled properly

### Screenshots and Videos

[output.webm](https://github.com/Fabricators-of-Create/Create/assets/16236317/038bdc7a-5916-4af0-b937-d42c99920cee)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

- EMI 1.0.9
- Trinkets 3.7.0
- ModMenu 7.1.0

### Additional Context

Related Issues
- #1080 (and issues marked as duplicates)
  - #1208
  - #1134 - Discovered most of the reason, see https://github.com/Fabricators-of-Create/Create/issues/1134#issuecomment-1746084470
  - #1211

Possible Solutions
- I have locally fixed the issue by copying the return value (L102) of `StorageInteractionContainer.getItem` in my dev env. It seems that the shift-click interaction modifies the return value of getItem directly. But I have no idea if the solution could produce other side effects.
  https://github.com/Fabricators-of-Create/Create/blob/49cc17e3de33c965b1c409130abe436821f7410c/src/main/java/com/simibubi/create/content/contraptions/MountedStorageInteraction.java#L96-L103
- Another possible solution is changing the Porting-Lib code. Apply the isEmpty filter whenever `ItemStackHandler.nonEmptyViews` is called.
  https://github.com/Fabricators-of-Create/Porting-Lib/blob/41c9aacb30f43e0993c63f1da4438e1943fc6697/transfer/src/main/java/io/github/fabricators_of_create/porting_lib/transfer/item/ItemStackHandler.java#L101-L111

**Comment by ergo3983** [comment] 2024-01-10 06:04
I've had this one too, with gantries.
It seems removing a stack (through shift clicking or not) of a moving contraption causes it.

**Comment by TropheusJ** [comment] 2024-01-10 23:12
duplicate of #1080

**Closed as completed by TropheusJ** 2024-01-10 23:12 UTC
Labels: type: bug
