### ISSUE TITLE
Train lighting is glitched

### ISSUE THREAD

**Issue by ghost** [Fabricators-of-Create/Create#541] opened 2022-09-02 04:29 UTC
### Describe the Bug

When assembling a train it goes completely dark, pressing f3 + a seems to fix it but only when in that chunk. Disabling the flywheel engine also seems to work however fps drop massively, specially when having multiple contraptions

### Reproduction Steps

1.Assemble a train
2.Try to move it
3.
...

### Expected Result

The train maintaining the same level of lighting as everything else

### Screenshots and Videos

![2022-09-01_23 12 41](https://user-images.githubusercontent.com/112671201/188057616-b742eadb-3b62-4925-9de7-934bb395a4c8.png)

### Operating System

Windows 11

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment] 2022-09-02 04:59
duplicate of #468

**Closed as completed by TropheusJ** 2022-09-02 04:59 UTC
Labels: type: bug
