### ISSUE TITLE
Client crash (has crash report)

### ISSUE THREAD

**Issue by ZYFDroid** [Fabricators-of-Create/Create#725] opened 2022-12-30 15:20 UTC
### Describe the Bug

A player build a machine on my server causing client crash. 

Everyone near the machine got 'banned'

see crash report for more detail. 

### Reproduction Steps

Unknown

### Expected Result

None

### Crash Report or Log

https://bytebin.lucko.me/be4SLacj7d

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment] 2022-12-30 20:27
duplicate of #548

**Closed as completed by TropheusJ** 2022-12-30 20:27 UTC
Labels: type: bug
