### ISSUE TITLE
在1.19.2 fabric服务端中，放置机械手导致服务端崩溃

### ISSUE THREAD

**Issue by monika233333** [Fabricators-of-Create/Create#627] opened 2022-11-26 10:50 UTC
### Describe the Bug

从背包中拿出一个机械手，放置在方块上，服务端即刻崩溃
--- Minecraft Crash Report ----
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because the return value of "net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel()" is null
	at net.minecraft.class_3244.handler$zfk000$adventure$initTracking(class_3244.java:3044)
	at net.minecraft.class_3244.<init>(class_3244.java:242)
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayNetworkHandler.<init>(FakeServerPlayNetworkHandler.java:21)
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayer.<init>(FakeServerPlayer.java:20)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerFakePlayer.<init>(DeployerFakePlayer.java:58)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.initHandler(DeployerTileEntity.java:146)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.initialize(DeployerTileEntity.java:139)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntity.tick(SmartTileEntity.java:67)
	at com.simibubi.create.content.contraptions.base.KineticTileEntity.tick(KineticTileEntity.java:94)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.tick(DeployerTileEntity.java:172)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Reproduction Steps

1.从背包中拿出一个机械手
2.放置在方块上
3.服务端即刻崩溃
...

### Expected Result

从背包中拿出一个机械手，放置在方块上，服务端即刻崩溃

### Screenshots and Videos

从背包中拿出一个机械手，放置在方块上，服务端即刻崩溃

### Crash Report or Log

https://pan.baidu.com/s/1cCxuOQuA4vdbm3fE_ZEv0g?pwd=1111  提取码：1111

### Operating System

server 2022

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Fabric Mods: 
		antixray: AntiXray 1.2.6
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		architectury: Architectury 6.3.56
		chunky: Chunky 1.3.38
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v6 7.0.73
		collective-fabric: Collective (Fabric) 5.15
			fiber: fiber 0.23.0-2
		create: Create 0.5.0g-791+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.5.0
			forgeconfigapiport: Forge Config API Port 4.2.6
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.0.612+1.19.2
				porting_lib_base: Porting Lib Base 2.0.612+1.19.2
					com_github_llamalad7_mixinextras: MixinExtras 0.1.1
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.0.612+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.0.612+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.0.612+1.19.2
				porting_lib_models: Porting Lib Models 2.0.612+1.19.2
				porting_lib_networking: Porting Lib Networking 2.0.612+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.0.612+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.0.612+1.19.2
				porting_lib_tags: Porting Lib Tags 2.0.612+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.0.612+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.0.612+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.0.612+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.0.612+1.19.2
							porting_lib_constants: Porting Lib Constants 2.0.612+1.19.2
						porting_lib_common: Porting Lib Common 2.0.612+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
		dynmap: Dynmap 3.4
		enchantedshulkers: Enchanted Shulkers 1.0.4
			mm: Manningham Mills 2.3
		fabric-api: Fabric API 0.67.1+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.37+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.3+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.3+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.1+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.30+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.35+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.9+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.12+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.20+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.7+9244241690
			fabric-networking-v0: Fabric Networking (v0) 0.3.24+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.2+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.28+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.1+0d0f210290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.3+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.6+kotlin.1.7.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.10
		fldf: Fast Leaf Decay 1.0.0
		followersteleporttoo-fabric: Followers Teleport Too (Fabric) 1.2
		ftbbackups2: FTB Backups 2 1.0.17
		high-unrestricted: High Unrestricted 1.0.1
		inventorytotem-fabric: Inventory Totem (Fabric) 2.1
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jei: Just Enough Items 11.4.0.285
		koro-utils-lib: Koro Utils Lib 1.0.0
			cn_hutool_hutool-all: hutool-all 5.8.9
			org_java-websocket_java-websocket: Java-WebSocket 1.5.3
		koroworld-lib: KoroWorld Lib 2.0.1
		lazydfu: LazyDFU 0.1.3
		luckperms: LuckPerms 5.4.52
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		minecraft: Minecraft 1.19.2
		nullscape: Nullscape 1.2
		phosphor: Phosphor 0.8.1
		polylib: PolyLib 1900.0.2-build.42
		server-hats: Server Hats 0.11
		spark: spark 1.9.45
		tabtps-fabric: TabTPS 1.3.15
			adventure-platform-fabric: adventure-platform-fabric 5.4.0-SNAPSHOT
				net_kyori_adventure-api: adventure-api 4.11.0
				net_kyori_adventure-key: adventure-key 4.11.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.1.1
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.11.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.11.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.11.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.11.0
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
			cloud: Cloud 1.8.0-SNAPSHOT
				cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.8.0-SNAPSHOT
				cloud_commandframework_cloud-core_: cloud-core 1.8.0-SNAPSHOT
				cloud_commandframework_cloud-services_: cloud-services 1.8.0-SNAPSHOT
				io_leangen_geantyref_geantyref: geantyref 1.3.13
			cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.8.0-SNAPSHOT
			com_typesafe_config: config 1.4.2
			net_kyori_adventure-serializer-configurate4: adventure-serializer-configurate4 4.11.0
			net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
			net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.11.0
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		tectonic: Tectonic 1.0.2
		wso16: Why stacks of 16? 1.1

**Comment by JieningYu** [comment] 2022-11-26 12:21
请使用英语，谢谢。

**Comment by TropheusJ** [comment] 2022-11-26 15:51
Duplicate of #503

**Closed as completed by TropheusJ** 2022-11-26 15:51 UTC
Labels: type: bug
