### ISSUE TITLE
Hose Pulley Bottomless Supply dont work

### ISSUE THREAD

**Issue by hang666** [Fabricators-of-Create/Create#564] opened 2022-09-30 09:48 UTC
### Describe the Bug

fill 50x50x4 cube with lava
Lower a Hose Pulley to the Bottom
Use engineers Goggles show Bottomless Supply ,but Pumping liquid out of the pool incorrectly reduces the amount of magma in the pool
This bug is only present in the Fabric version, not in the Forge version

### Reproduction Steps

1.fill 51x51x4 cube with lava
2.Lower a Hose Pulley to the Bottom
3.Use engineers Goggles show Bottomless Supply ,but Pumping liquid out of the pool incorrectly reduces the amount of magma in the pool
...

### Expected Result

If  is Bottomless Supply, the liquid in the pool should not be consumed

### Operating System

Windows 11

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

**Comment by 404Mate** [comment] 2022-10-10 19:19
duplicate of https://github.com/Fabricators-of-Create/Create/issues/492

**Closed as completed** 2022-11-20 23:00 UTC
Labels: type: bug
