### ISSUE TITLE
Create on 1.20.1 Fabric breaks entity randomization in YUNG's Better structures

### ISSUE THREAD

**Issue by yungnickyoung** [Fabricators-of-Create/Create#1361] opened 2024-03-08 05:56 UTC
### Describe the Bug

My structure mods such as YUNG's Better Strongholds, YUNG's Better Desert Temples, and YUNG's Better Fortresses include item frames and armor stands that receive processing during structure placement to randomize their contents. This randomization system is enabled by a couple of mixins on YUNG's API: https://github.com/YUNG-GANG/YUNGs-API/blob/1.20/Fabric/src/main/java/com/yungnickyoung/minecraft/yungsapi/mixin/EntityProcessorMixin.java

When using Create Fabric, the item frames do not get randomized, meaning their respective StructureEntityProcessors never get executed. As a result, all item frames will contain their placeholder items. Similarly, armor stands will all be the same, only containing their placeholder armor.

### Reproduction Steps

1. Install the mods. To reproduce this I used Create 1.20.1 v0.5.1.d, YUNG's Better Strongholds v4.0.3, YUNG's Better Desert Temples v3.0.3, YUNG's Better Nether Fortresses v2.0.5, and YUNG's API v4.0.4. I believe the only relevant mods here are Create and YUNG's API though, since YUNG's API is what creates my structure entity processing system.
2. Locate one of my structures, e.g. `/locate structure betterstrongholds:betterstronghold`
3. Search for item frames and/or armor stands in the structure. In the case of strongholds, you will see that all item frames and armor stands within a room contain the same item.

### Expected Result

I expect the entities to be properly randomized and not all have the same thing.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/25270754/62dcf289-1a65-4132-97b5-5c6ccd771b19)
![image](https://github.com/Fabricators-of-Create/Create/assets/25270754/5959098e-388a-4dc8-8b4b-30f706389179)
![image](https://github.com/Fabricators-of-Create/Create/assets/25270754/f33dfc5f-ac37-4f96-a5c7-bae4bc59a388)
![image](https://github.com/Fabricators-of-Create/Create/assets/25270754/89289492-824d-4c60-b8fa-b0652f137d2c)
![image](https://github.com/Fabricators-of-Create/Create/assets/25270754/40cd7c24-b787-4120-926d-9a17e350e436)
![image](https://github.com/Fabricators-of-Create/Create/assets/25270754/c10ec1ae-4978-4bc3-b105-cb217efb95f8)
![image](https://github.com/Fabricators-of-Create/Create/assets/25270754/5c45ec1f-7c76-4d77-8ee8-d72abea24a13)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods
Necessary dependencies. fabric-api-0.89.0+1.20.1 and cloth-config-11.1.106-fabric

**Comment by TropheusJ** [comment] 2024-03-08 05:59
this is caused by a really bad mixin to StructureTemplate in porting lib. the code has been removed in the latest version, and it should be fixed in the next release.

**Closed as completed by TropheusJ** 2024-03-08 05:59 UTC
Labels: type: bug
