### ISSUE TITLE
Deployer makes server crash

### ISSUE THREAD

**Issue by suitun** [Fabricators-of-Create/Create#734] opened 2023-01-02 10:56 UTC
### Describe the Bug

When a deployer is placed in my server， it crash immediately.
Then, I restart the server.But it will crash when anyone enters the server.
I have to delete the chunk where the deployer was placed.

### Reproduction Steps

1.place a deployer
2.the server crash immediately
3.after restart the server，it will crash when anyone enters the server
...

### Expected Result

emm..

### Crash Report or Log

https://gist.github.com/suitun/e69833784d72d275a301502063ba3ca0

### Operating System

win server 2022

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

After many attempts, I found that these two mods would cause the crash of the deployer
1. tabtps-fabric-mc1.19.2-1.3.15
2. better-fabric-console-mc1.19.2-1.1.2

**Comment by opee2012** [comment] 2023-01-02 17:27
I had the same problem and don't have those mods on my server. I made a hotfix for it that I can send you to hopefully make it work.

**Comment by TropheusJ** [comment] 2023-01-02 18:09
duplicate of #503
remove both of those mods

**Closed as completed by TropheusJ** 2023-01-02 18:09 UTC
Labels: type: bug
