### ISSUE TITLE
The hopper extracts items from the depot without consumption.

### ISSUE THREAD

**Issue by Icewater661** [Fabricators-of-Create/Create#377] opened 2022-06-15 14:43 UTC
### Describe the Bug

The hopper can extract items from the depot without restriction, and the items on the depot will not be consumed.
*Sorry for my English

### Reproduction Steps

1.Place the depot, then place the hopper under the depot
2.Place more than one items on the depot（If only one item is placed, the hopper will not extract anything.）
3.The hopper is gradually filled, but the number of items on the depot has not changed.
...

### Expected Result

The hopper extracts items from the depot without consumption.

### Screenshots and Videos

![2022-06-15-22-32-23](https://user-images.githubusercontent.com/69789097/173854356-f980ccfe-310d-4269-9a4f-d32624452a03.gif)

### Operating System

Windows11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

appleskin-fabric-mc1.18.2-2.4.0.jar
architectury-4.4.61.jar
badpackets-fabric-0.1.2.jar
breakprogress-1.0.1.jar
carpet-tis-addition-mc1.18.2-v1.35.0.jar
CITResewn-1.0.1+1.18.2.jar
cloth-config-6.2.62-fabric.jar
DisableCustomWorldsAdvice-2.0.jar
fabric-api-0.51.1+1.18.2.jar
fabric-carpet-1.18.2-1.4.69+v220331 (1).jar
ftb-chunks-fabric-1802.3.6-build.145.jar
ftb-library-fabric-1802.3.6-build.119.jar
ftb-teams-fabric-1802.2.6-build.51.jar
indium-1.0.3+mc1.18.2.jar
InventoryProfilesNext-fabric-1.18.2-1.3.8.jar
iris-mc1.18.2-1.2.4-build.38.jar
itemscroller-fabric-1.18.2-0.16.0.jar
LavaClearView-1.18.2-fabric-4.0.1.jar
litematica-fabric-1.18.2-0.11.3.jar
lithium-fabric-mc1.18.2-0.7.9.jar
malilib-fabric-1.18.2-0.12.1.jar
MasaGadget-1.18.2-2.0.9.1.jar
minihud-fabric-1.18.2-0.22.0.jar
modmenu-3.2.2.jar
oh-my-minecraft-client-1.18.2-0.4.2 (1).jar
phosphor-fabric-mc1.18.x-0.8.1.jar
replaymod-1.18.2-2.6.5.jar
rer-2.5.0.jar
roughly-enough-characters-0.0.4+1.18.2-fabric0.13.3.jar
RoughlyEnoughItems-8.1.457.jar
RoughlyEnoughProfessions-fabric-1.18.2-1.0.1.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
tweakeroo-fabric-1.18.2-0.13.3.jar
worldedit-mod-7.2.10.jar
wthit-fabric-4.10.3.jar
BBOutlineReloaded-2.4-1.18.2-fabric.jar

**Comment by TropheusJ** [comment] 2022-06-15 15:16
Duplicate of #325

**Closed as completed by TropheusJ** 2022-06-15 15:16 UTC
Labels: type: bug
