### ISSUE TITLE
Smart Pipe Bug

### ISSUE THREAD

**Issue by NhanBreads** [Fabricators-of-Create/Create#128] opened 2022-02-05 11:51 UTC
### Describe the Bug

Whenever making chocolate (liquid) and is in the basin, the smart pipe is set to filter chocolate through only, however, it sends milk through the pipe system instead. Even if there is no milk, the chocolate will not filter through the smart pipe.

### Reproduction Steps

1. Make an auto chocolate system (Making milk and chocolate in the same basin)
2. Use the smart pipe to filter the chocolate out of the basin only and into another basin

### Expected Result

It was expected that the chocolate will be in the pipe system only and not the milk. The milk will stay in the basin and the chocolate will go into another basin to make bars of chocolate.

### Screenshots and Videos

This image shows that the basin on the right has chocolate and milk, with the smart pipe filtering out chocolate. However, on the left basin, it is shown that it is send milk through instead. (Note: I also tried replacing the basin and it will still pour out milk)
![image](https://user-images.githubusercontent.com/51067515/152640775-2ad9072c-694d-4dd2-9396-1ed397a6b0f4.png)

### Operating System

Windows 11

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment] 2022-02-05 12:32
Duplicate of #119, update

**Closed as completed by TropheusJ** 2022-02-05 12:32 UTC
Labels: type: bug
