### ISSUE TITLE
game crashes while loading main menu "The game crashed whilst rendering screen"

### ISSUE THREAD

**Issue by ShadowRocks2** [Fabricators-of-Create/Create#742] opened 2023-01-06 05:41 UTC
### Describe the Bug

when the game gets to main menu it crashes instantly
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$2" is null

### Reproduction Steps

1. Launch game
2. It crashes

### Expected Result

it doesnt crash

### Crash Report or Log

https://pastebin.com/THTwyhiZ

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

i have quite a few, hoping the crash log would maybe tell what if any is conflicting to cause suck a crash

**Comment by ShadowRocks2** [comment] 2023-01-06 14:10
the mod automobility was causing the crash

**Comment by TropheusJ** [comment] 2023-01-06 14:11
Duplicate of #452

**Closed as completed** 2023-01-06 14:10 UTC
Labels: type: bug
