### ISSUE TITLE
Fluid pipes incompatible with Modern Industrialization steam

### ISSUE THREAD

**Issue by Abalieno** [Fabricators-of-Create/Create#909] opened 2023-05-03 17:20 UTC
### Describe the Bug

My whole modpack is based around this, so I was so happy when I found out everything stopped working as intended...

Simply trying to pull steam from a MI boiler, with a mechanical pump and Create fluid pipes.

Up to create-fabric-0.5.0.i-946+1.19.2 (Feb 9) everything works normally.

Starting from create-fabric-0.5.0.i-961+1.19.2 and up to the most current version MI steam cannot be extracted.

### Reproduction Steps

1. Make steam in MI bronze boiler
2. Place a Create mechanical pump on top, with a cog + hand crank, couple of pipes going into a tank.
3. After the February version of Create the steam doesn't get moved anymore. Works normally in previous versions.
...

### Expected Result

That mechanical pumps can extract MI steam.

### Operating System

W10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by Abalieno** [comment] 2023-05-08 16:19
It got worse.

I figured out that NO fluid is working, this isn't MI problem.

Create pipes can't move any fluid, including lava and water. Item drains are also broken, right clicking with a water bucket does not empty it into the drain. Using a belt does work, the bucket gets emptied, but the fluid can't be extracted with a mechanical pump after it gets in the drain.

Not only, PONDER ITSELF is broken:

![yukyk](https://user-images.githubusercontent.com/4656436/236876348-38a7daee-97b7-4c30-a689-46c9163b6b3d.png)

It's showing pipes not being connected, and no fluid being moved.

Rolling back the mod to  the 946 version fixes it (including item drains, bucket interactions and everything):

![yu,kyi,l](https://user-images.githubusercontent.com/4656436/236876503-e742da64-c0bd-4e4b-b720-3b465388f617.png)

Wtf is going on?!

**Comment by TropheusJ** [comment] 2023-05-08 18:53
has to be some weird incompatibility. Try to narrow it down.

**Comment by Abalieno** [comment] 2023-05-09 03:22
Ok, there were different things.

The item drain/ponder bug was related to me testing the Tinkers port on 1.19.2. Removing the mod fixed it.
https://github.com/Argent-Matter/TinkersConstruct/releases/tag/3.6.0%2B3

I was mistaken because I reproduced the bug with a stripped down instance, but apparently I must have launched the wrong instance and so ended up with the wrong conclusion... Removing that mod indeed makes item drain and ponder work again.

The MI steam bug is still present, and using Hephaestus + Create 946 has a funny outcome, because I can see some steam particles coming out the mechanical pump, but steam doesn't actually get moved.

It's different from using Create 946 without Hephaestus, because that makes steam properly move.
And it's different from using Create 1003 with or without Hephaestus, because that makes no steam particles appear at all.

I really still need to have the steam bug addressed, since it's a major problem for what I do...

**Comment by screret** [comment] 2023-05-09 12:30
i've managed to get a crash by going to the 2nd page of fluid pipe ponder, got this crash.
anyone able to find the root cause for the actual issue report, because i for the life of me can't find why this happens?
[crash-2023-05-09_15.16.50-client.txt](https://github.com/Fabricators-of-Create/Create/files/11431041/crash-2023-05-09_15.16.50-client.txt)

**Comment by screret** [comment] 2023-05-09 19:35
Fixed.

**Comment by Abalieno** [comment] 2023-05-11 14:24
A few more details, in the hope the bug will be addressed...

Create tank + pipe + MI steam works.
MI boiler + Create tank attached to it + pipe starting from tank also works.

The problem is all about MI boiler + Create pipe and pump. It must be some conflict with extraction.

**Comment by TropheusJ** [comment] 2023-05-12 03:35
I've fixed this locally, will push tomorrow. A few things:
- this was an issue with MI machines in general, not steam.
- The Hephaestus 1.19.**2** port is unofficial, untested, and unsupported.
- that crash should be fixed in newer versions, and I'm assuming it was fixed by updating.

**Closed as completed by TropheusJ** 2023-05-12 03:35 UTC
Labels: type: bug

**Comment by Abalieno** [comment] 2023-05-12 07:35
Yes, thanks a lot.

As I said, I didn't intend to clump together the two issues, but I came to the wrong conclusions by launching the wrong instance. I wouldn't have reported the Tinkers problem here if I didn't wrongly thing it was all one issue.

I was only testing Tinkers and the status is uncertain. My best guess was that Alpha didn't intend to release Tinkers 1.19 publicly to avoid stepping on the original mod's/Forge toes.

With AE2/kubejs/ftb quests apparently skipping 1.19.4 I can only hope there's still some extended support for 1.19.2...
