### ISSUE TITLE
Incompability with Automobility?

### ISSUE THREAD

**Issue by TheRealPicasso** [Fabricators-of-Create/Create#715] opened 2022-12-28 01:32 UTC
I was trying to play my modpack, until it crashed. First I sent my crash-report to "Automobility", someone replied though, there might be an incompability with create, so I am trying to make sure here. I hope this problem gets solved soon.

Fabric: 1.18.2 (loader: 0.14.11)
create version: create-fabric-0.5.0g-792+1.18.2.jar
automobility version: automobility-0.3+1.18.2.jar

[crash-2022-12-27_21.12.25-client.txt](https://github.com/Fabricators-of-Create/Create/files/10311495/crash-2022-12-27_21.12.25-client.txt)

**Comment by TropheusJ** [comment] 2022-12-28 01:38
Automobility includes Myron on 1.18, duplicate of #452

**Closed as completed by TropheusJ** 2022-12-28 01:38 UTC
