### ISSUE TITLE
Create Crashes with Sodium

### ISSUE THREAD

**Issue by HiroWu1** [Fabricators-of-Create/Create#91] opened 2022-01-16 12:31 UTC
### Describe the Bug

I'm not sure if this is only for curseforge but when starting minecraft on curseforge with both sodium and create minecraft crashes

### Reproduction Steps

1. Use Curseforge
2. Install Sodium and Create
3. Start Minecraft
...

### Expected Result

Minecraft fails to start

### Crash Report or Log

https://pastebin.com/AxFWGFHi

### Operating System

Windows 10

### Mod Version

0.4.0b

### Minecraft Version

1.18.1

### Other Mods

Fabric API

**Comment by TropheusJ** [comment] 2022-01-16 13:19
Duplicate of #88

**Closed as completed by TropheusJ** 2022-01-16 13:19 UTC
Labels: type: bug
