### ISSUE TITLE
Crash in modpack using latest actions build (unknown cause)

### ISSUE THREAD

**Issue by Shadowevil015** [Fabricators-of-Create/Create#469] opened 2022-07-30 13:15 UTC
### Describe the Bug

Hi, I'm currently making a modpack to play with my friends, and before adding the latest create actions build (https://github.com/Fabricators-of-Create/Create/actions/runs/2758284828), it worked/launched fine, but while using it, the game gets stuck on resource generation? (i think its called that lol) part of startup, and eventually crashes

I've tried removing mods and slowly adding them back, but I can't seem to find a pattern for which mod(s) is causing the crash.

### Reproduction Steps

1. Use this modpack (curseforge format)
2. Launch and wait
3. The game will crash
[flat-smp.zip](https://github.com/Fabricators-of-Create/Create/files/9226518/flat-smp.zip)

### Expected Result

The game should launch with no issues

### Crash Report or Log

https://pastebin.com/mJszVTe2

### Operating System

Manjaro Linux

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

AwesomeDungeonEnd-Fabric-1.18.2-1.0.3.jar
AwesomeDungeonNether-Fabric-1.18.2-1.0.3.jar
LibraryFerret-Fabric-1.18.2-2.0.0.jar
Additional Additions | Fabric (https://minecraft.curseforge.com/projects/508556)
Adorn (https://minecraft.curseforge.com/projects/320215)
AE2 Things (https://minecraft.curseforge.com/projects/563800)
Amethyst Imbuement (https://minecraft.curseforge.com/projects/608261)
Among Us Plushies {FABRIC} (https://minecraft.curseforge.com/projects/639089)
An Origins Addon - Apocalypse (https://minecraft.curseforge.com/projects/521235)
AppleSkin (https://minecraft.curseforge.com/projects/248787)
Applied Energistics 2 Wireless Terminals (https://minecraft.curseforge.com/projects/459929)
Applied Energistics 2 (https://minecraft.curseforge.com/projects/223794)
Arcanus (https://minecraft.curseforge.com/projects/517833)
Architect's Palette [FABRIC] (https://minecraft.curseforge.com/projects/487364)
Architectury API (Fabric/Forge) (https://minecraft.curseforge.com/projects/419699)
Architectury API (UNUSED) (https://minecraft.curseforge.com/projects/419697)
Artifacts (Fabric) (https://minecraft.curseforge.com/projects/401236)
AttributeFix (https://minecraft.curseforge.com/projects/280510)
Auto Config Updated API (https://minecraft.curseforge.com/projects/373261)
bad packets (https://minecraft.curseforge.com/projects/615134)
Balm (Fabric Edition) (https://minecraft.curseforge.com/projects/500525)
BCLib (https://minecraft.curseforge.com/projects/495191)
Besmirchment 2 (https://minecraft.curseforge.com/projects/542196)
Better Compatibility Checker (https://minecraft.curseforge.com/projects/551894)
Better Ping Display [Fabric] (https://minecraft.curseforge.com/projects/406343)
Better Animals Plus (https://minecraft.curseforge.com/projects/303557)
Bewitchment (https://minecraft.curseforge.com/projects/394915)
Biome Makeover (https://minecraft.curseforge.com/projects/412182)
Blossom (https://minecraft.curseforge.com/projects/575248)
Bookshelf (https://minecraft.curseforge.com/projects/228525)
Borderless Mining (https://minecraft.curseforge.com/projects/310205)
Capybara [Fabric] (https://minecraft.curseforge.com/projects/549031)
Caracal Mod (Fabric/Forge) (https://minecraft.curseforge.com/projects/486505)
Cardinal Components (https://minecraft.curseforge.com/projects/318449)
Chisels & Bits - For Fabric (https://minecraft.curseforge.com/projects/561059)
Cloth Config API (Fabric/Forge) (https://minecraft.curseforge.com/projects/348521)
Continuity (https://minecraft.curseforge.com/projects/531351)
Controlling (https://minecraft.curseforge.com/projects/250398)
CoralReef (https://minecraft.curseforge.com/projects/248994)
Couplings (https://minecraft.curseforge.com/projects/311120)
Croptosis (https://minecraft.curseforge.com/projects/437552)
Dank Storage Fabric (https://minecraft.curseforge.com/projects/400619)
Dawn API (https://minecraft.curseforge.com/projects/399309)
Discord Integration Fabric (https://minecraft.curseforge.com/projects/493679)
Debugify (https://modrinth.com/mod/QwxR6Gcd)
Deep Mob Learning: Refabricated (https://minecraft.curseforge.com/projects/398614)
Dimension Fix (Some Forge Patches Ported) (https://minecraft.curseforge.com/projects/437779)
DimensionalDoors (https://minecraft.curseforge.com/projects/284876)
'Dustrial Decor [Fabric] (https://minecraft.curseforge.com/projects/592067)
Ecologics (https://minecraft.curseforge.com/projects/570463)
Eden Ring (https://minecraft.curseforge.com/projects/546590)
Ellemes' Container Library (https://minecraft.curseforge.com/projects/530668)
Enchantment Descriptions (https://minecraft.curseforge.com/projects/250419)
EnderChests [Fabric] (https://minecraft.curseforge.com/projects/564584)
Enhanced Quarries (Fabric) (https://minecraft.curseforge.com/projects/528338)
Entity Culling Fabric/Forge (https://minecraft.curseforge.com/projects/448233)
Expanded Storage (https://minecraft.curseforge.com/projects/317856)
Extended Drawers (https://minecraft.curseforge.com/projects/616602)
Extra Generators (https://minecraft.curseforge.com/projects/475623)
Extra Origins (https://minecraft.curseforge.com/projects/398419)
Fabric API (https://minecraft.curseforge.com/projects/306612)
Chisel Refabricated (https://minecraft.curseforge.com/projects/551763)
Fabric Language Kotlin (https://minecraft.curseforge.com/projects/308769)
Fabric Waystones (https://minecraft.curseforge.com/projects/410902)
FallingTree (Forge&Fabric) (https://minecraft.curseforge.com/projects/349559)
Farmer's Delight [Fabric] (https://minecraft.curseforge.com/projects/482834)
FastGrowth (https://minecraft.curseforge.com/projects/403544)
Feature NBT Deadlock Be Gone (https://minecraft.curseforge.com/projects/560323)
FerriteCore (Fabric) (https://minecraft.curseforge.com/projects/459857)
fish_of_thieves-mc1.18.2-v1.0.7-fabric.jar
tulipFloral Flairtulip (https://minecraft.curseforge.com/projects/549363)
Forge Config API Port (https://minecraft.curseforge.com/projects/547434)
Gamma Utils (https://minecraft.curseforge.com/projects/492295)
GeckoLib (https://minecraft.curseforge.com/projects/388172)
Haema (https://minecraft.curseforge.com/projects/391257)
Halfdoors (https://minecraft.curseforge.com/projects/596375)
Immersive Weathering [FABRIC] (https://minecraft.curseforge.com/projects/571035)
Improved Stations (Fabric) (https://minecraft.curseforge.com/projects/355914)
Indium (https://minecraft.curseforge.com/projects/459496)
Industrial Revolution (https://minecraft.curseforge.com/projects/391708)
Animal Origins - Infinite Origins (https://minecraft.curseforge.com/projects/597112)
Infusion Table (https://minecraft.curseforge.com/projects/531783)
Iris Shaders (https://minecraft.curseforge.com/projects/455508)
Iron Jetpacks Fabric (https://minecraft.curseforge.com/projects/386892)
Jade mag (https://minecraft.curseforge.com/projects/324717)
JamLib (https://minecraft.curseforge.com/projects/623764)
JourneyMap (https://minecraft.curseforge.com/projects/32274)
Kibe Utilities (https://minecraft.curseforge.com/projects/388832)
Krypton (https://minecraft.curseforge.com/projects/428912)
LambDynamicLights (https://modrinth.com/mod/yBW8D80W)
LazyDFU (https://minecraft.curseforge.com/projects/433518)
Lib Block Attributes (https://minecraft.curseforge.com/projects/317995)
Lifts (https://minecraft.curseforge.com/projects/451554)
Lithium (Fabric) (https://minecraft.curseforge.com/projects/360438)
Logical Zoom (https://minecraft.curseforge.com/projects/356461)
Login Protection[Forge/Fabric] (https://minecraft.curseforge.com/projects/358304)
Magnum Torch [Outdated] (https://minecraft.curseforge.com/projects/596517)
Memory Leak Fix (https://modrinth.com/mod/NRjRiSSD)
Mod Menu (https://minecraft.curseforge.com/projects/308702)
Space Dimensions (Fabric) (https://minecraft.curseforge.com/projects/429841)
More Culling (https://modrinth.com/mod/51shyZVL)
Mouse Wheelie (Fabric) (https://minecraft.curseforge.com/projects/317514)
Nature's Compass (https://minecraft.curseforge.com/projects/252848)
NetherPortalFix (Fabric Edition) (https://minecraft.curseforge.com/projects/547696)
Oh The Biomes You'll Go Refabricated (https://minecraft.curseforge.com/projects/391378)
Origins Extra Keybinds (https://minecraft.curseforge.com/projects/474612)
Origins (Fabric) (https://minecraft.curseforge.com/projects/391943)
Patchouli (Fabric/Quilt) (https://minecraft.curseforge.com/projects/393236)
Pehkui (https://minecraft.curseforge.com/projects/319596)
Plant In A Jar (https://minecraft.curseforge.com/projects/397183)
Player Events (https://minecraft.curseforge.com/projects/404348)
Polymorph (Fabric) (https://minecraft.curseforge.com/projects/397434)
Powah! (Rearchitected) (https://minecraft.curseforge.com/projects/633483)
Presence Footsteps [Fabric] (https://minecraft.curseforge.com/projects/334259)
Promenade (https://minecraft.curseforge.com/projects/399648)
Public Gui Announcement (https://minecraft.curseforge.com/projects/341727)
Puzzles Lib [Outdated] (https://minecraft.curseforge.com/projects/547429)
Reborn Core (https://minecraft.curseforge.com/projects/237903)
Reese's Sodium Options (https://minecraft.curseforge.com/projects/511319)
Replanter (https://minecraft.curseforge.com/projects/480657)
RightClickHarvest (https://minecraft.curseforge.com/projects/452834)
Roughly Enough Items Fabric/Forge (REI) (https://minecraft.curseforge.com/projects/310111)
Roughly Enough Resources (https://minecraft.curseforge.com/projects/325625)
Sandwichable (https://minecraft.curseforge.com/projects/374143)
Screenshot to Clipboard (Fabric) (https://minecraft.curseforge.com/projects/327154)
ShetiPhianCore [Fabric] (https://minecraft.curseforge.com/projects/536603)
Simple Chunkloader [FABRIC] (https://minecraft.curseforge.com/projects/626846)
Simple Teleporters (Fabric) (https://minecraft.curseforge.com/projects/334011)
skylorlib-1.3.35.jar
Sodium Extra (https://minecraft.curseforge.com/projects/447673)
Sodium (https://modrinth.com/mod/AANobbMI)
spark (https://minecraft.curseforge.com/projects/361579)
Subterrestrial (Fabric) (https://minecraft.curseforge.com/projects/575588)
TerraBlender (Fabric) (https://minecraft.curseforge.com/projects/565956)
The Bumblezone (Quilt/Fabric) (https://minecraft.curseforge.com/projects/363949)
The Extractinator (Fabric) (https://minecraft.curseforge.com/projects/567114)
The Twilight Forest (https://minecraft.curseforge.com/projects/227639)
tokenablefurnaces-1.3.0.jar
Tool Stats (https://minecraft.curseforge.com/projects/377109)
Traveler's Backpack [Fabric] (https://minecraft.curseforge.com/projects/541171)
Trinkets (Fabric) (https://minecraft.curseforge.com/projects/341284)
Universal Ores (Fabric) (https://minecraft.curseforge.com/projects/489884)
Vanilla Hammers (https://minecraft.curseforge.com/projects/317756)
Visuality (https://minecraft.curseforge.com/projects/521126)
Wireless Networks (https://minecraft.curseforge.com/projects/461316)
XL Packets Fabric (https://minecraft.curseforge.com/projects/390168)
YDM's Red Panda (https://minecraft.curseforge.com/projects/623035)
You're in Grave Danger (https://minecraft.curseforge.com/projects/544912)
YUNG's API (Fabric) (https://minecraft.curseforge.com/projects/421649)
YUNG's Better Desert Temples (Fabric) (https://minecraft.curseforge.com/projects/631020)
YUNG's Better Dungeons (Fabric) (https://minecraft.curseforge.com/projects/525586)
YUNG's Better Mineshafts (Fabric) (https://minecraft.curseforge.com/projects/373591)
YUNG's Better Strongholds (Fabric) (https://minecraft.curseforge.com/projects/480684)
YUNG's Better Witch Huts (Fabric) (https://minecraft.curseforge.com/projects/631403)
YUNG's Bridges (Fabric) (https://minecraft.curseforge.com/projects/590988)
YUNG's Extras (Fabric) (https://minecraft.curseforge.com/projects/590993)

### Additional Context

Using the exact same mods on a server, with Create, no crash occurs (may crash when somebody joins, i haven't been able to test that yet)

**Comment by JieningYu** [comment] 2022-07-30 14:11
sus mods: The Extractinator, Dimdoors and Create Fabric

**Comment by TropheusJ** [comment] 2022-07-30 16:27
can you send the crash log? it should have some needed info

**Comment by Shadowevil015** [comment] 2022-07-30 17:09
Sorry, I completely forgot!

https://pastebin.com/Y5nk90Ca

**Comment by TropheusJ** [comment] 2022-07-30 17:11
yep, duplicate of #452

**Closed as completed by TropheusJ** 2022-07-30 17:11 UTC
Labels: type: bug
