### ISSUE TITLE
Game crashing when starting

### ISSUE THREAD

**Issue by eoNaho** [Fabricators-of-Create/Create#177] opened 2022-03-08 11:33 UTC
### Describe the Bug

When starting the game it just doesn't open.

### Reproduction Steps

1.
2.
3.
...

### Expected Result

Not crash.

### Crash Report or Log

https://gist.github.com/Naho-sama/83c0aea1ae18d74f1179570ecd5d7673

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by JieningYu** [comment] 2022-03-08 11:43
Seems dupe of https://github.com/Fabricators-of-Create/Create/issues/173

**Closed as completed** 2022-03-08 11:56 UTC
Labels: type: bug
