### ISSUE TITLE
Game crashes attempting to render create blocks

### ISSUE THREAD

**Issue by cannonball95** [Fabricators-of-Create/Create#539] opened 2022-09-01 15:15 UTC
### Describe the Bug

Checking recipes on REI, I attempted to look at a bulk washing tab and the game crashed. I suspected it could be REI's fault, so I tried just placing the encased fan in the world. Crashes before it even renders, and attempting to load the world leads to another crash. Repeated this with other create items, same result.

### Reproduction Steps

1. Place create item, load world with a create item placed, or check a create recipe on REI.
2. Game crash

### Expected Result

Create items are placed in the world, worlds with create items can be loaded, create recipes can be checked on REI.

### Crash Report or Log

https://paste.ee/p/G1pqk

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

A bunch of them
![imagen](https://user-images.githubusercontent.com/93522885/187945793-397d13f1-43cc-4ef6-a99c-6830c70471c2.png)
![imagen](https://user-images.githubusercontent.com/93522885/187945906-8beecad4-37a1-471c-839d-5bbe08a47220.png)
![imagen](https://user-images.githubusercontent.com/93522885/187945997-b9fac3d3-7549-431b-8cb3-38486b07b858.png)
![imagen](https://user-images.githubusercontent.com/93522885/187946069-d5d213c2-587e-4266-8019-0c8dc4ea1f1f.png)

### Additional Context

Using MultiMC.
At some point before this issue didn't happen, at least as I was setting up the mods. Can't remember if this didn't happen while running the current mod setup, so I can't discard this being an incompatibility between mods.
Distant horizons appears in the mod list but it's disabled.

**Comment by TropheusJ** [comment] 2022-09-01 16:55
Appears to be a duplicate of #461

**Closed as completed by TropheusJ** 2022-09-01 16:55 UTC
Labels: type: bug

**Comment by cannonball95** [comment] 2022-09-01 16:56
Doing some testing, I tried disabling Visual Workbench + Puzzles Lib, given those were not activated when I first tested Create. For now, I can use Create stuff, but I won't close this yet just in case.
So far it seems like there's some incompatibility with Visual workbench, it's a shame cause it looks fancy and all, but not a big deal.
