### ISSUE TITLE
Get unlimited items with “tech reborn” & 

### ISSUE THREAD

**Issue by CvRain** [Fabricators-of-Create/Create#367] opened 2022-06-11 11:48 UTC
### Describe the Bug

**This should be because there is a problem with the linkage of the module. Maybe it is not a bug?**

Using tech rebon's storage unit to connect to the storage desk, unlimited items can be obtained

### Reproduction Steps

- place a create:depot on the ground
- place a Tech: storage block next to it
- enter to storage block and configure automatic pull in

### Expected Result

Whether tech reborn forcibly obtained the item information
I don't even know who to submit this issuse to

### Screenshots and Videos

I simply recorded a video to show the bug
https://www.bilibili.com/video/bv1z94y117ZB

### Operating System

Windows 10 & OpenSuse Linux

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

TechReborn-5.2.0

**Comment by TropheusJ** [comment] 2022-06-15 22:03
Likely a duplicate of #325. Can you test with [a dev build](https://github.com/Fabricators-of-Create/Create/actions/runs/2504256739)?

**Comment by TropheusJ** [comment] 2022-06-16 04:42
[Patch 9](https://modrinth.com/mod/create-fabric/version/mc1.18.2_v0.4.1+628) also works.

**Comment by TropheusJ** [comment] 2022-06-24 05:47
assuming fixed

**Closed as completed by TropheusJ** 2022-06-24 05:47 UTC
Labels: type: bug, status: needs info
