### ISSUE TITLE
Crash when basin transfers items to chute via spout

### ISSUE THREAD

**Issue by spencerfrost** [Fabricators-of-Create/Create#610] opened 2022-11-20 17:51 UTC
### Describe the Bug
Game crashes when a basin transfers an item to a chute via the basin's spout. I've tested the spout with depots and belts as well but they work fine. This happened on my dedicated server with a bunch of mods first and then I managed to predictably replicate it on my PC without any mods.

### Reproduction Steps
- Mix any items in a basin
- Place a chute down 1 and over 1 so that the basin has the little spout above the chute to dump items
- Game crashes

### Expected Result
I would expect the items to transfer without crashing the game

### Screenshots and Videos
![image](https://user-images.githubusercontent.com/34923439/202917214-88994e5b-34bf-4941-8b65-9279c726ef49.png)

### Crash Report or Log
https://pastebin.com/5E6tj4XV

### Operating System
Windows 10 and Linux

### Mod Version
0.5.0f

### Minecraft Version
1.19.2

### Other Mods
These are the usual mods I play with but I disabled them all to test this.

  [❌] architectury-6.3.49-fabric.jar (disabled)
  [❌] audioplayer-1.19.2-1.4.5.jar (disabled)
  [❌] authme-mc1.19.2-4.2.0.jar (disabled)
  [❌] BetterF3-4.0.0-Forge-1.19.2.jar (disabled)
  [❌] bobby-4.0.0.jar (disabled)
  [❌] CITResewn-1.1.2+1.19.2.jar (disabled)
  [❌] cloth-config-8.2.88-fabric.jar (disabled)
  [❌] collective-fabric-1.19.x-4.27.jar (disabled)
  [❌] continuity-2.0.1+1.19.jar (disabled)
  [❌] Controlling-fabric-1.19.2-10.0+7.jar (disabled)
  [✔️] create-fabric-1.19.2-0.5.0f-776
  [❌] EditSign-1.19.2-2.6.0.jar (disabled)
  [❌] emotecraft-for-MC1.19.2-2.2.5-fabric.jar (disabled)
  [✔️] fabric-api-0.66.0+1.19.2
  [❌] fabric-carpet-1.19.2-1.4.84+v221018.jar (disabled)
  [❌] ferritecore-5.0.0-fabric.jar (disabled)
  [❌] indium-1.0.9+mc1.19.2.jar (disabled)
  [❌] inventorysorter-1.19.2-21.0.4.jar (disabled)
  [❌] iris-mc1.19.2-1.4.2.jar (disabled)
  [❌] Jade-1.19.1-fabric-8.2.3.jar (disabled)
  [❌] lambdynamiclights-2.1.2+1.19.jar (disabled)
  [❌] lithium-fabric-mc1.19.2-0.10.2.jar (disabled)
  [❌] logical_zoom-0.0.17.jar (disabled)
  [❌] modmenu-4.1.0.jar (disabled)
  [❌] MouseTweaks-fabric-mc1.19-2.22.jar (disabled)
  [❌] polaroidcamera-1.4.0.jar (disabled)
  [❌] reeses_sodium_options-1.4.7+mc1.19.2-build.59.jar (disabled)
  [❌] RoughlyEnoughItems-9.1.572.jar (disabled)
  [❌] shulkerboxtooltip-forge-3.2.2+1.19.2.jar (disabled)
  [❌] sodium-extra-0.4.13+mc1.19.2-build.76.jar (disabled)
  [❌] sodium-fabric-mc1.19.2-0.4.4+build.18.jar (disabled)
  [❌] starlight-1.1.1+fabric.ae22326.jar (disabled)
  [❌] textile_backup-2.4.0-1.19.1.jar (disabled)
  [❌] voicechat-fabric-1.19.2-2.3.15.jar (disabled)
  [❌] Xaeros_Minimap_22.16.2_Fabric_1.19.1.jar (disabled)
  [❌] XaerosWorldMap_1.28.3_Fabric_1.19.1.jar (disabled)

**Comment by CzechHek** [comment] 2022-11-20 18:18
Duplicate of #599

**Closed as completed** 2022-11-20 22:59 UTC
