### ISSUE TITLE
crash on startup 1.18.2 fabric

### ISSUE THREAD

**Issue by N1kx0** [Fabricators-of-Create/Create#758] opened 2023-01-18 20:52 UTC
### Describe the Bug

crashes after finishing the standard mojang loading screen

### Reproduction Steps

recreate my mod folder and start the game should crash when finished loading.

### Expected Result

not crashing after finished loading

### Crash Report or Log

https://pastebin.com/j1Qc4YFD

### Operating System

windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

ad_astra: Ad Astra! 1.0.5
			team_reborn_energy: Energy 2.2.0
		adorn: Adorn 3.5.0+1.18.2
		advancednetherite: Advanced Netherite 1.5.1-1.18.2
		advancementinfo: AdvancementInfo 1.18.2-fabric0.47.10-1.3.1
		advancementplaques: Advancement Plaques 1.4.6
		advdebug: Advancements Debug 2.3.0
		animatica: Animatica 0.5+1.18.2
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.10.88
		automobility: Automobility 0.3+1.18.2
			jsonem: JsonEM 0.1.2
			myron: Myron 1.6.3+1.18.1
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 3.1.0+0
		basicshields: Basic Shields [Fabric] 1.3.1-1.18.2
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		bclib: BCLib 1.4.7
		beaconoverhaul: Beacon Overhaul 1.6.0+1.18.2
			reach-entity-attributes: Reach Entity Attributes 2.1.1
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		betterend: Better End 1.1.1
		betterf3: BetterF3 3.0.0
		betterfpsdist: Better FPS distance Mod 1.18-1.8
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.1.3
		bettermounthud: Better Mount HUD 1.1.4
		betternether: Better Nether 6.1.2
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		betterthirdperson: Better Third Person 1.7.3
		blockrunner: Block Runner 3.0.2
		boatcontainer: BoatContainer 1.1.0
		boathud: BoatHud 1.1.0
		bookshelf: Bookshelf 13.0.13
		borderlessmining: Borderless Mining 1.1.2+1.18.2
		byg: Oh The Biomes You'll Go 1.4
		cem: Custom Entity Models 0.7.1
			completeconfig: CompleteConfig 1.0.0
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmonium: Charmonium 4.1.0
		chas: Craftable Horse Armour & Saddle 1.18-1.8-Fabric
		chesttracker: Chest Tracker 1.1.16
			whereisit: Where Is It 1.14.10
		citresewn: CIT Resewn 1.1.1+1.18.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.18.2
		cleancut: CleanCut 1.18.2-5.0-fabric
		clickthrough: ClickThrough 1.18.2-fabric0.47.10-0.4
			gbfabrictools: GBfabrictools 1.3.4+1.18.2
		cloth-api: Cloth API 3.2.64
			cloth-client-events-v0: Cloth Client Events v0 3.2.64
			cloth-common-events-v1: Cloth Common Events v1 3.2.64
			cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
			cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
			cloth-utils-v1: Cloth Utils v1 3.2.64
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 5.45
			fiber: fiber 0.23.0-2
		colormeoutlines: Color Me Outlines 1.1.0
		computercraft: CC: Restitched 1.100.8
		connectiblechains: Connectible Chains 2.1.4+1.18.2
		continuity: Continuity 2.0.1+1.18.2
		controlling: Controlling For Fabric 9.0+19
		copperhopper: Copper Hopper 0.0.8+1.18.2
		coralreef: Coral Reef 1.18.2-1.0.2
		couplings: Couplings 1.8.0+1.18.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		create: Create 0.5.0g-792+1.18.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 0.6.8-32
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			noindium: No Indium? 1.0.1+1.18.2
			porting_lib: Porting Lib 1.2.460-beta+1.18.2-dev.cca931b
				serialization_hooks: Serialization Hooks 0.3.23
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.5
		create_crystal_clear: Create: Crystal Clear 0.1e-1.18.2
		croptopia: Croptopia 2.0.5
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		cull-less-leaves: Cull Less Leaves 1.0.1
		dawn: Dawn API 3.3.2
		dcch: DCCH 1.0
		debugify: Debugify 1.11.0
		decorative_blocks: Decorative Blocks 2.1.0
		denseores: Dense Ores: Refabricated 1.2.2+1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
			omega-config-gui: Omega Config GUI 1.2.3-1.18.1
				cloth-config-lite: cloth-config-lite 2.0.6
		disenchanter: Disenchanter 0.1.6+1.18
		display_case: Display Case Mod 1.0.3
		droplight: Droplight 1.0.5
		dungeons_arise: When Dungeons Arise 2.1.50
		durability101: Durability101 0.0.4
		dynamicfps: Dynamic FPS 2.1.0
		easiervillagertrading: EasierVillagerTrading 1.18.2-fabric0.47.10-1.5.4
		easymagic: Easy Magic 3.3.0
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		ecologics: Ecologics 1.7.11
		effortless: Effortless Fabric 1.3.0
		eldritch_mobs: Eldritch Mobs 1.11.0
		enchantmentsplus: Enchantments Plus 1.0.10+1.18.2
		enchdesc: EnchantmentDescriptions 10.0.3
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.18.2
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		entity_texture_features: Entity Texture Features 4.3.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.5.1
		exlinefurniture: Exline's Furniture 2.3.0
		experiencebottler: Experience Bottler 1.18.2+build.1
		explorerscompass: Explorer's Compass 1.18.2-2.1.0-fabric
		fabric-api: Fabric API 0.67.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.2+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.20+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.0+d8cf4e5a60
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.11+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.15+ee3621fc60
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.5+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.8+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.3+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.12
		fabricshieldlib: Fabric Shield Lib 1.5.3-1.18
			mm: Manningham Mills 2.3
		fabricskyboxes: FabricSkyBoxes 0.5.5
		fabrishot: Fabrishot ${version}
		fallingleaves: Falling Leaves 1.11.1+1.18.2
		fallingtree: FallingTree 3.5.1
		ferritecore: FerriteCore 4.2.1
		floralench: Floral Enchantment Fabric-1.18.2-1.1.1
		floristmod: Florist's Mod fabric-1.18.2-v-2.0.1
		forgeconfigapiport: Forge Config API Port 3.2.0
		furnitureexpanded: Furniture Expanded [FABRIC] 1.0.2-1.18.2
		gammautils: Gamma Utils 1.5.7
		geckolib3: Geckolib 3.0.80
			com_eliotlash_mclib_mclib: mclib 20
		iceberg: Iceberg 1.0.38
		identity: Identity 2.3.0-1.18.2
		illuminations: Illuminations 1.10.4
		immersive_paintings: Immersive Paintings 0.4.2+1.18.2
		indium: Indium 1.0.7+mc1.18.2
		infinitetrading-fabric: Infinite Trading (Fabric) 2.1
		infusion_table: Infusion Table 1.1.0
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.9.0
		iris: Iris 1.5.0
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		ironchests: Iron Chests 1.6.1
			libgui: LibGui 5.4.1+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
				libninepatch: LibNinePatch 1.1.0
		isxander-main-menu-credits: Main Menu Credits 1.1.1
		itemmodelfix: Item Model Fix 1.0.3+1.18
		itemscroller: Item Scroller 0.16.0
		java: OpenJDK 64-Bit Server VM 17
		labels: labels 1.18.2-1.0
		languagereload: Language Reload 1.2.1
		legendarytooltips: Legendary Tooltips 1.2.4
		libipn: libIPN 2.0.0
		linearxp: Linear XP 1.0.1
		lithium: Lithium 0.7.10
		malilib: MaLiLib 0.12.1
		mambience: MAmbience 5.0.0+1.18.2
		mavm: More Axolotl Variants Mod 1.0.8a
		mca: Minecraft Comes Alive 7.4.0+1.18.2
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.4
		mcwlights: Macaw's Lights and Lamps 1.0.3
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwpaths: Macaw's Paths and Pavings 1.0.2
		mcwroofs: Macaw's Roofs 2.1.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.5
		megane: megane 7.9.1
			megane-api: megane-api 7.9.1
			megane-create: megane-create 7.9.1
			megane-fabric-transfer: megane-fabric-transfer 7.9.1
			megane-reborn-energy: megane-reborn-energy 7.9.1
			megane-runtime: megane-runtime 7.9.1
			megane-vanilla: megane-vanilla 7.9.1
		memoryleakfix: Memory Leak Fix 1.18.2-0.7.0
		minecraft: Minecraft 1.18.2
		mixintrace: MixinTrace 1.1.1+1.17
		mob_catcher: Mob Catcher 1.1.30
		mobscarecrow: Mob Scarecrow 2.1.1
		modmenu: Mod Menu 3.2.3
		more_babies: More Babies 1.0.0
		morebannerfeatures: More Banner Features 1.1.3
		morevillagers-fabric: MoreVillagersFabric 3.2.0-SNAPSHOT
		mostructures: Mo' Structures 1.4.2+1.18.2
		mousetweaks: Mouse Tweaks 2.22
		nametagtweaks-fabric: Name Tag Tweaks (Fabric) 2.3
		naturalist: Naturalist 1.1.1
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		nofade: No Fade 1.18-2.0.1
		notenoughanimations: NotEnoughAnimations 1.6.0
		omnihopper: Omni-Hopper 1.1.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.7
			cooldown-coordinator: Cooldown Coordinator 0.3.0
		optigui: OptiGUI 1.1.0
			org_apache_commons_commons-text: commons-text 1.9
		ottercraft: Ottercraft 1.1.13
		patchouli: Patchouli 1.18.2-71-FABRIC
		pfm: Paladin's Furniture 1.1.1
		presencefootsteps: Presence Footsteps 1.5.0
			kirin: Kirin UI 1.10.0
		prism: Prism 1.0.3
		promenade: Promenade 2.6.3
			terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		puzzle: Puzzle 1.4.1-1.18
			midnightlib: MidnightLib 0.4.4
			puzzle-base: Puzzle Base 1.4.1-1.18
			puzzle-gui: Puzzle GUI 1.4.1-1.18
			puzzle-models: Puzzle Models 1.4.1-1.18
			puzzle-splashscreen: Puzzle Splash Screen 1.4.1-1.18
		puzzleslib: Puzzles Lib 3.3.1
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.18.2-build.58
		respawnablepets: Respawnable Pets 1.18-4
		roughly_enough_trades: Roughly Enough Trades (RET) 1.1.1
		roughlyenoughitems: Roughly Enough Items 8.3.583
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.0.2
		shulkerboxtooltip: Shulker Box Tooltip 3.0.7+1.18.2
		silkspawners: SilkSpawners 1.1.1
		skinlayers: 3d Skin Layers 1.4.4-mc1.18.2
		smallships: Small Ships 2.0.0a1.1.1
		smoothboot: Smooth Boot 1.18.2-1.7.0
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.10+mc1.18.2-build.63
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.6
		stacker: Stacker 3.0.2-1.18.2
			stacc: Stacc 1.3.2
		starlight: Starlight 1.0.2+fabric.89b8d9f
		structory: Structory 1.0.0
		t_and_t: Towns and Towers 1.10.0.1
			blue_endless_jankson: jankson 1.2.1
		taxfreelevels: Tax Free Levels 1.3
		terrablender: TerraBlender 1.1.0.102
		toolleveling: ToolLeveling+ 1.18.2-1.4.4
		tooltipfix: ToolTip Fix 1.0.4-1.18
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		transportables: Transportables 1.2
		trashslot: TrashSlot 11.0.2
		travelersbackpack: Traveler's Backpack 1.18.2-7.1.0
		trinkets: Trinkets 3.3.1
		tweakeroo: Tweakeroo 0.13.3
		veinmining: Vein Mining 0.0.12-1.18.2
		villagernames: Villager Names 4.0.4
			cardinal-components-level: Cardinal Components API (world saves) 4.0.1
		vinery: Vinery 1.0.1
			terraform-wood-api-v1: Terraform Wood API (v1) 3.1.0
		visuality: Visuality 0.4.3
			goosik-config: goosik-config 0.2.0
		visualworkbench: Visual Workbench 3.3.0
		waystones: Waystones 10.1.0
		wildlife: Wildlife 1.18.2-2.2
		witchmobility: Witch Mobility Mod 1.2.0-1.18.2
		wolveswitharmor: Wolves With Armor 1.7.1-1.18.2
			maybe-data: Maybe data 1.2.1-1.18.2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		woof: Woof 3.0.0-1.18
			com_github_llamalad7_mixinextras: MixinExtras 0.0.12
		worldedit: WorldEdit 7.2.10+1742f98
		wthit: wthit 4.13.5
		xaerominimap: Xaero's Minimap 22.9.3
		xaeroworldmap: Xaero's World Map 1.28.4
		yigd: You're in Grave Danger 1.3.6
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0

**Comment by TropheusJ** [comment] 2023-01-18 20:53
duplicate of #452, Myron is included by Automobility

**Closed as completed by TropheusJ** 2023-01-18 20:53 UTC
Labels: type: bug
