### ISSUE TITLE
Crash when placing Deployer (Fabric)

### ISSUE THREAD

**Issue by RyanTheTechMan** [Fabricators-of-Create/Create#365] opened 2022-06-11 05:13 UTC
### Describe the Bug

When a player on the server placed the Deployer, the server crashed.  When the chunk was loaded in after the restart (player logged back in), the server crashed. I was able to reproduce this on single player.

### Reproduction Steps

1. Place the Deployer
2. Crashed

### Expected Result

Server does not crash

### Crash Report or Log

https://pastebin.com/Swt1jSHS

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

I was able to fix the world with Amulet and remove the placed block and drag the updated region file into the world.

**Comment by TropheusJ** [comment] 2022-06-15 22:00
duplicate of #117

**Closed as completed by TropheusJ** 2022-06-15 22:00 UTC
Labels: type: bug
