### ISSUE TITLE
Horizontal Gantry Shafts get broken by water

### ISSUE THREAD

**Issue by goodasde** [Fabricators-of-Create/Create#1262] opened 2024-01-05 12:46 UTC
### Describe the Bug

Horizontal Gantry Shafts get broken by water, vertical Gantry Shafts are completely unaffected. 

### Reproduction Steps

1. Place Water 
2. Horizontal Gantry Shafts in flowing water

### Expected Result

I tested this on a clean install of create forge where both orientations of Gantry Shafts were not being destroyed by water and im asuming thats the way its supposed to work.

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

No other mods

**Comment by TropheusJ** [comment] 2024-02-22 20:54
can't reproduce, maybe fixed in patch F
![image](https://github.com/Fabricators-of-Create/Create/assets/60247969/dca7b803-785a-414b-ab0e-d9f12bb49484)

**Closed as completed by TropheusJ** 2024-02-22 20:54 UTC
Labels: type: bug
