### ISSUE TITLE
Dropz doesnt work with create

### ISSUE THREAD

**Issue by Mrgaton** [Fabricators-of-Create/Create#926] opened 2023-05-15 18:32 UTC
### Describe the Bug

I believe dropz uses custom entity for drops, would be great to support it!

https://github.com/LazuriteMC/Dropz/issues/25

See dropz issue, i don't think they can do it on their end.

Additional Context
Dropz uses the rayon physics api.

### Reproduction Steps

throwing items to basin doest work

### Expected Result

Items interact with mod

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment] 2023-05-15 18:43
Duplicate of #595

**Closed as completed by TropheusJ** 2023-05-15 18:43 UTC
Labels: type: bug
