### ISSUE TITLE
Block Dupe glitch with rotating Deployer

### ISSUE THREAD

**Issue by CookieGD** [Fabricators-of-Create/Create#876] opened 2023-04-05 00:31 UTC
### Describe the Bug

When I built my tree farm today I noticed that the Deployers don't pull out the saplings from the chest, but just dupe them in. I then tested how exactly it worked and what blocks are affected and found out that my setup could dupe any place-able block.

### Reproduction Steps

1. Place a Water Wheel flat on the floor to supply the power.
2. Place a Mechanical Bearing on the Water Wheel and add 3 building blocks (like dirt or cobble) on top.
3. Place a Deployer facing downwards next to the top building block.
4. Add a chest anywhere on the contraption and glue everything together.
5. Give the Deployer a single place-able block of any kind (e.g. Cobble, Saplings, Diamond Block, etc.)
6. Start the contraption and see the Deployer duping the item.

### Expected Result

I expected the Deployer to use the items in the chest to feed its supply.

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

I played the "FTB Legend Of The Eyes" modpack.

### Additional Context

In the other 1.19.2 fabric modpack that I played this didn't happen for some reason. Probably because it didn't have the latest version of Create.

**Comment by TropheusJ** [comment] 2023-04-05 01:54
Happens when a Deployer places blocks in an FTB Chunks claim

**Comment by TropheusJ** [comment] 2023-04-05 02:11
This seems to be caused by Architectury API. FTB Chunks cancels the placement via BlockEvent.PLACE, so Create does not consume the item. However, that event is fired after the block has been placed.

**Comment by TropheusJ** [comment] 2023-04-05 22:19
should be fixed if you update architectury

**Closed as completed by TropheusJ** 2023-04-05 22:19 UTC
Labels: type: bug, area: compatibility
