### ISSUE TITLE
[1.20] Killing a blaze with a empty deploy crash the game/server

### ISSUE THREAD

**Issue by Niron68** [Fabricators-of-Create/Create#1125] opened 2023-09-24 14:27 UTC
### Describe the Bug

When you use a empty deployer to kill a blaze, it crash the game or the server

### Reproduction Steps

1. Put a deployer without equiping it an item
2. Put a blaze under the deployer
3. Let the deployer kill the blaze

### Expected Result

The game shouldn't crash

### Crash Report or Log

https://pastebin.com/PpT542Xd

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment] 2023-09-27 17:40
duplicate of #1096

**Closed as completed by TropheusJ** 2023-09-27 17:40 UTC
Labels: type: bug
