### ISSUE TITLE
[crash at launch] Tested it in my modpack for the hell of it! Maybe it'll help with compatibility?

### ISSUE THREAD

**Issue by netcore10** [Fabricators-of-Create/Create#261] opened 2022-04-27 21:42 UTC
### Describe the Bug

Crash at launch.

### Reproduction Steps

No idea.

### Expected Result

It should atleast launch.

### Crash Report or Log

https://hastebin.skyra.pw/rimixugeda.nestedtext

### Operating System

windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[DragonLoot (by pois1xlive)](https://www.curseforge.com/minecraft/mc-mods/dragonloot)
[WMITAF (by ShaksterNano)](https://www.curseforge.com/minecraft/mc-mods/wmitaf)
[Dynamic Sound Filters (by andre111_)](https://www.curseforge.com/minecraft/mc-mods/dynamic-sound-filters)
[AdventureZ (by Globox_Z)](https://www.curseforge.com/minecraft/mc-mods/adventurez)
[Creatures From The Snow! [Fabric] (by YoWabbit)](https://www.curseforge.com/minecraft/mc-mods/creatures-from-the-snow-fabric)
[Llamarama (by 0xJoeMama)](https://www.curseforge.com/minecraft/mc-mods/llamarama)
[Faux Custom Entity Data (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/faux-custom-entity-data)
[Patchouli (Fabric) (by williewillus)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
[Food+ [Fabric] (by theone_ss)](https://www.curseforge.com/minecraft/mc-mods/food-pluss)
[Meal API (by FoundationGames)](https://www.curseforge.com/minecraft/mc-mods/meal-api)
[slotlink (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/slotlink)
[Nears [Fabric] (by DigitalPear_11)](https://www.curseforge.com/minecraft/mc-mods/nears)
[Archon (by safrodev)](https://www.curseforge.com/minecraft/mc-mods/archon)
[PlutosCoffeeMod (by Pluto7073)](https://www.curseforge.com/minecraft/mc-mods/plutoscoffeemod)
[NinjaPhenix's Container Library (by NinjaPhenix)](https://www.curseforge.com/minecraft/mc-mods/ninjaphenixs-container-library)
[Balm (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm-fabric)
[Tech Reborn (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/techreborn)
[Iconic Wands (by SkylorBeck)](https://www.curseforge.com/minecraft/mc-mods/iconic-wands)
[Effective 💦 (by doctor4t)](https://www.curseforge.com/minecraft/mc-mods/effective)
[LazyDFU (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/lazydfu)
[Lovely Snails (by LambdAurora)](https://www.curseforge.com/minecraft/mc-mods/lovely-snails)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Animal Feeding Trough [Fabric | Forge] (by Slexom)](https://www.curseforge.com/minecraft/mc-mods/animal-feeding-trough)
[CraftTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[Phosphor (Fabric) (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/phosphor)
[Sodium (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/sodium)
[Auto Config Updated API (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/auto-config-updated-api)
[Mythic Metals (by Noaaan)](https://www.curseforge.com/minecraft/mc-mods/mythicmetals)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Observable (by tasgon)](https://www.curseforge.com/minecraft/mc-mods/observable)
[Advanced Reborn (by pitan76)](https://www.curseforge.com/minecraft/mc-mods/advancedreborn)
[Pick Your Poison 🐸 (by doctor4t)](https://www.curseforge.com/minecraft/mc-mods/pick-your-poison)
[Artifacts (Fabric) (by florensie)](https://www.curseforge.com/minecraft/mc-mods/artifacts-fabric)
[Smooth Boot (Fabric) (by UltimateBoomer)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot)
[Akashic Tome of Tools Fabric (by vlad2305m)](https://www.curseforge.com/minecraft/mc-mods/akashic-tome-of-tools-fabric)
[Fabric Enchantments (by safrodev)](https://www.curseforge.com/minecraft/mc-mods/fabric-enchantments)
[Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[BetterEnd (by paulevs)](https://www.curseforge.com/minecraft/mc-mods/betterend)
[Entity Culling Fabric/Forge (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[The Graveyard Biomes (FABRIC) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-biomes-fabric)
[Additional Additions | Fabric (by dqu1jjj)](https://www.curseforge.com/minecraft/mc-mods/additional-additions)
[Ingredient Extension API (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/ingredient-extension-api)
[Fixed Waterlogging (by KxmischesDomi)](https://www.curseforge.com/minecraft/mc-mods/fixed-waterlogging)
[BCLib (by paulevs)](https://www.curseforge.com/minecraft/mc-mods/bclib)
[Eden Ring (by paulevs)](https://www.curseforge.com/minecraft/mc-mods/eden-ring)
[Villainous Fish AI (by CartoonishVillain)](https://www.curseforge.com/minecraft/mc-mods/villainous-fish-ai)
[Dynamic FPS (by juliand665)](https://www.curseforge.com/minecraft/mc-mods/dynamic-fps)
[Applied Energistics 2 (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[Variant Barrels [Fabric] (by XanthianZ)](https://www.curseforge.com/minecraft/mc-mods/variant-barrels-fabric)
[SkyLib (by SkylorBeck)](https://www.curseforge.com/minecraft/mc-mods/skylib)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
[Mod Menu (by ProspectorDev)](https://www.curseforge.com/minecraft/mc-mods/modmenu)
[Reinforced Barrels (by atonkish)](https://www.curseforge.com/minecraft/mc-mods/reinforced-barrels)
[Oh The Biomes You'll Go Refabricated (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric)
[Inventory Profiles Next (by mirinimi)](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next)
[Spellbound Enchantments (by TigerOfTroy)](https://www.curseforge.com/minecraft/mc-mods/spellbound-enchantments)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Simply Runes (by Aelpecyem)](https://www.curseforge.com/minecraft/mc-mods/simply-runes)
[Customizable Player Models (Fabric) (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/custom-player-models-fabric)
[Extra Alchemy (by zabi94)](https://www.curseforge.com/minecraft/mc-mods/extra-alchemy)
[Lush Forests (by albertsmods)](https://www.curseforge.com/minecraft/mc-mods/lush-forests)
[Large Fluid Tank for Fabric (by Kotori316)](https://www.curseforge.com/minecraft/mc-mods/largefluidtank-fabric)
[Dawn API (by Hugman_76)](https://www.curseforge.com/minecraft/mc-mods/dawn)
[A Cute Little Crock Pot (by nosrick_the_elder)](https://www.curseforge.com/minecraft/mc-mods/a-cute-little-crock-pot)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Farming for Blockheads (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/farming-for-blockheads-fabric)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Jamtastic (by jamalam360)](https://www.curseforge.com/minecraft/mc-mods/jam-fabric)
[The Veggie Way [FABRIC] (by kwpugh)](https://www.curseforge.com/minecraft/mc-mods/veggieway-fabric)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Roughly Enough Resources (by theorbagain)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-resources)
[Capybara [Fabric] (by ZestyBlaze)](https://www.curseforge.com/minecraft/mc-mods/capybara-fabric)
[Elemental Creepers: Refabricated (by Luligabi12)](https://www.curseforge.com/minecraft/mc-mods/elemental-creepers-refabricated)
[Endless Ocean: Aquatic Adventures (by theNyfaria)](https://www.curseforge.com/minecraft/mc-mods/endless-ocean-aquatic-adventures)
[DefaultSettings Fabric (by PT400C)](https://www.curseforge.com/minecraft/mc-mods/defaultsettings-fabric)
[Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric)
[Bewitchment (by MoriyaShiine)](https://www.curseforge.com/minecraft/mc-mods/bewitchment)
[More Axolotl Variants Mod (by Akashii_Kun_)](https://www.curseforge.com/minecraft/mc-mods/mavm)
[[Fabric] Expanded Storage (by NinjaPhenix)](https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric)
[MC Dungeons Armors (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcda)
[Vanilla Degus (by minet6759_)](https://www.curseforge.com/minecraft/mc-mods/vanilla-degus)
[BetterF3 (by cominixo)](https://www.curseforge.com/minecraft/mc-mods/betterf3)
[The Graveyard (FABRIC) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-fabric)
[Dimension Data Fix (by qouteall)](https://www.curseforge.com/minecraft/mc-mods/dimension-data-fix)
[Sprout (by ToadstoolStudios)](https://www.curseforge.com/minecraft/mc-mods/sprout)
[Mini Miner (by SkylorBeck)](https://www.curseforge.com/minecraft/mc-mods/mini-miner)
[Arcanus (by Camellias_)](https://www.curseforge.com/minecraft/mc-mods/arcanus)
[Bushy Business (by KaloyanKYS)](https://www.curseforge.com/minecraft/mc-mods/bushy-business)
[Friends&Foes (Fabric) (by faboslav)](https://www.curseforge.com/minecraft/mc-mods/friends-and-foes)
[Equipment Compare [Fabric] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/equipment-compare-fabric)
[Crawl (Fabric) (by fewizz_)](https://www.curseforge.com/minecraft/mc-mods/crawl)
[Roughly Enough Items Fabric/Forge (REI) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
[Cursery[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cursery)
[Feature NBT Deadlock Be Gone (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/feature-nbt-deadlock-be-gone)
[MC Dungeons Weapons (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcdw)
[AmbientSounds 5 (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)
[Botania (Fabric) (by williewillus)](https://www.curseforge.com/minecraft/mc-mods/botania-fabric)
[Exline's Sandwich Mod (by exlinegames)](https://www.curseforge.com/minecraft/mc-mods/exlines-sandwich-mod)
[Very Many Players (Fabric) (by ishlandmc)](https://www.curseforge.com/minecraft/mc-mods/vmp-fabric)
[Vein Mining (Fabric) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/vein-mining-fabric)
[Styled Chat (by Patbox)](https://www.curseforge.com/minecraft/mc-mods/styled-chat)
[TerraBlender (Fabric) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric)
[World of Food (by DerpyNinjaFrog)](https://www.curseforge.com/minecraft/mc-mods/world-of-food)
[Cammie's Wearable Backpacks (by Camellias_)](https://www.curseforge.com/minecraft/mc-mods/cammies-wearable-backpacks)
[Lithium (Fabric) (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/lithium)
[Lib Block Attributes (by AlexIIL)](https://www.curseforge.com/minecraft/mc-mods/libblockattributes)
[Impaled 🔱 (by doctor4t)](https://www.curseforge.com/minecraft/mc-mods/impaled)
[Duckling (by ToadstoolStudios)](https://www.curseforge.com/minecraft/mc-mods/duckling)
[Overweight Farming (by agentmhkskg)](https://www.curseforge.com/minecraft/mc-mods/overweight-farming)
[Gear Reborn (by loleq21)](https://www.curseforge.com/minecraft/mc-mods/gearreborn)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Waystones (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones-fabric)
[Structures' Compass (by Samarium_150)](https://www.curseforge.com/minecraft/mc-mods/structures-compass)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[Quality of Life (QoL) Fixes (by spoorn)](https://www.curseforge.com/minecraft/mc-mods/quality-of-life-qol-fixes)
[Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
[MegaParrot (by SkylorBeck)](https://www.curseforge.com/minecraft/mc-mods/megaparrot)
[Freecam (Fabric) (by hashalites)](https://www.curseforge.com/minecraft/mc-mods/free-cam)
[Exline's Sushi Mod (by exlinegames)](https://www.curseforge.com/minecraft/mc-mods/exlines-sushi-mod)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Architectury API (Fabric) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric)
[AE2 Things (by ProjectET)](https://www.curseforge.com/minecraft/mc-mods/ae2things)
[Applied Energistics 2 Wireless Terminals (by Mari_023)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals)
[Culinaire (by Hugman_76)](https://www.curseforge.com/minecraft/mc-mods/culinaire)
[Better Animals Plus (by cybercat5555)](https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus)
[BetterNether (by paulevs)](https://www.curseforge.com/minecraft/mc-mods/betternether)
[Alloy Forgery (by LordDeatHunter)](https://www.curseforge.com/minecraft/mc-mods/alloy-forgery)
[WTHIT (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit)
[Sit (Fabric) (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/sit-fabric)
[Iris Shaders (by coderbot)](https://www.curseforge.com/minecraft/mc-mods/irisshaders)
[Chunky Pregenerator (Fabric) (by pop4959)](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator)
[Detail Armor Bar [Fabric] (by 빨간라)](https://www.curseforge.com/minecraft/mc-mods/detail-armor-bar)
[Polymorph (Fabric) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Gate of Babylon (by Draylar1)](https://www.curseforge.com/minecraft/mc-mods/gate-of-babylon)
[Space Dimensions (Fabric) (by captaintenneal81)](https://www.curseforge.com/minecraft/mc-mods/moon-and-space-dimensions-fabric)
[Not Enough Crashes (Fabric) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes)
[oωo (owo-lib) (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
[The Bumblezone (Fabric) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-fabric)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[You're in Grave Danger (by b1n_ry)](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)
[Fish of Thieves (by SteveKunG)](https://www.curseforge.com/minecraft/mc-mods/fish-of-thieves)
[Cooldown Coordinator (by gniftygnomecraft)](https://www.curseforge.com/minecraft/mc-mods/cooldown-coordinator)
[MC Dungeons Artifacts (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcdar)
[Convenient mobGriefing (by Neecko5b84)](https://www.curseforge.com/minecraft/mc-mods/convenient-mobgriefing)
[Fabric Language Scala (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-scala)
[Iceberg [Fabric] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg-fabric)
[Origins (Fabric) (by Apace100)](https://www.curseforge.com/minecraft/mc-mods/origins)
[Ductwork (by gniftygnomecraft)](https://www.curseforge.com/minecraft/mc-mods/ductwork)
[ServerCore (by Wesley8081)](https://www.curseforge.com/minecraft/mc-mods/servercore)
[Stendhal (by NebSpacefarer)](https://www.curseforge.com/minecraft/mc-mods/stendhal)
[Chirpy's Wildlife (by chirpycricket__)](https://www.curseforge.com/minecraft/mc-mods/chirpys-wildlife)
[Cosmetic Armor [FABRIC] (by Apace100)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric)
[Croptopia [FABRIC/FORGE] (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric)
[Dimension Fix (Some Forge Patches Ported) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/dimension-fix-some-forge-patches-ported)
[Grizzly bear Mod (by AqUpd)](https://www.curseforge.com/minecraft/mc-mods/grizzly-bear)
[VoidZ (by Globox_Z)](https://www.curseforge.com/minecraft/mc-mods/voidz)
[Leaves Us In Peace (by supersaiyansubtlety)](https://www.curseforge.com/minecraft/mc-mods/leaves-us-in-peace)
[Go Fish (by Draylar1)](https://www.curseforge.com/minecraft/mc-mods/go-fish)
[Reborn Core (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/reborncore)
[Harvest with ease [FABRIC] (by Crystal_Spider_)](https://www.curseforge.com/minecraft/mc-mods/harvest-with-ease-fabric)
[Blossom (by yurisuika)](https://www.curseforge.com/minecraft/mc-mods/blossom)

### Additional Context

I was trying for the hell of it, i posted this to help with mod compatibility.

**Comment by AlphaMode** [comment] 2022-04-27 21:55
Duplicate of #258

**Closed as completed by AlphaMode** 2022-04-27 21:55 UTC
Labels: type: bug
