### ISSUE TITLE
Crash on Ponder a fluid tank

### ISSUE THREAD

**Issue by MimiVRC** [Fabricators-of-Create/Create#306] opened 2022-05-21 20:25 UTC
### Describe the Bug

https://crashy.net/5zGl9J6GMVwvLxKkwkkC

### Reproduction Steps

1. hold W on a fluid tank, the ponder display shows up but before the animation lays it crashes 

### Expected Result

the animation starts to playthe 

### Crash Report or Log

https://crashy.net/5zGl9J6GMVwvLxKkwkkC

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment] 2022-05-21 20:37
try removing colormatic

**Comment by MimiVRC** [comment] 2022-05-22 10:42
this is stop it from crashing, thank you!

**Comment by TropheusJ** [comment] 2022-05-22 17:07
duplicate of #255

**Closed as completed by TropheusJ** 2022-05-22 17:07 UTC
Labels: type: bug
