### ISSUE TITLE
Crash when joining a server with create

### ISSUE THREAD

**Issue by ItzEnderArkail** [Fabricators-of-Create/Create#560] opened 2022-09-21 04:54 UTC
### Describe the Bug

for some reason when joining a server with create installed, it crashes

### Reproduction Steps

1. join a server with create installed and some artifacts already built
2. boom, crash

### Expected Result

idk if this happends with only create installed or with other mods

### Crash Report or Log

https://pastebin.pl/view/raw/596ae9e2

### Operating System

Windows 10

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

### Other Mods

the mods should be shown by the crash log

**Comment by JieningYu** [comment] 2022-09-21 04:57
dupe of https://github.com/Fabricators-of-Create/Create/issues/461

**Comment by TropheusJ** [comment] 2022-09-21 13:29
Correct

**Closed as completed by TropheusJ** 2022-09-21 13:29 UTC
Labels: type: bug
