### ISSUE TITLE
Pipes have gaps with sodium+indium

### ISSUE THREAD

**Issue by Alakqualyn** [Fabricators-of-Create/Create#521] opened 2022-08-20 16:23 UTC
### Describe the Bug

Pipes have gaps at some angles when sodium and indium are used. The screenshots show the difference. No other mods were active when they were taken.

The problem does not seem to occur when pipes attach to tanks at an angle.

### Reproduction Steps

1. Curseforge
2. Create (fabric)
3. Sodium + Indium

### Expected Result

Correctly rendered pipes.

### Screenshots and Videos

![2022-08-20_12 10 12](https://user-images.githubusercontent.com/68087456/185756666-5a8aa596-ae09-42da-b189-13cacb56f6fd.png)
![2022-08-20_12 12 17](https://user-images.githubusercontent.com/68087456/185756668-9316956c-8389-4c67-9ed9-cbf6e8c53016.png)

### Operating System

macOS Monterey

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

Sodium and Indium

**Comment by TropheusJ** [comment] 2022-08-20 16:38
duplicate of #453

**Closed as completed by TropheusJ** 2022-08-20 16:38 UTC
Labels: type: bug
