### ISSUE TITLE
1.19.2 (fabric) Mechanical arm dont save commands

### ISSUE THREAD

**Issue by Megovid** [Fabricators-of-Create/Create#737] opened 2023-01-04 06:49 UTC
### Describe the Bug

all time, then I use mech arm it just tell me "no targets" BUT I BINDED TARGETS

### Reproduction Steps

1.
2.
3.
...

### Expected Result

Arm, please use coal on my blaze burners

### Screenshots and Videos

![Снимок экрана (2158)](https://user-images.githubusercontent.com/121926098/210499031-d8a78ee3-925d-4055-9a00-e876ba203000.png)
![Снимок экрана (2159)](https://user-images.githubusercontent.com/121926098/210499056-32035daf-b3be-4ab6-8d8a-024c0dbc5f9b.png)

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Modpack "Vanilla Create Exploration" on fabric

**Comment by TropheusJ** [comment] 2023-01-04 07:09
Duplicate of #731, see comments for a workaround 
Fixed in next update

**Closed as completed by TropheusJ** 2023-01-04 07:09 UTC
Labels: type: bug
