### ISSUE TITLE
Flywheel Issues

### ISSUE THREAD

**Issue by Vonskin** [Fabricators-of-Create/Create#556] opened 2022-09-12 22:18 UTC
### Describe the Bug

I'm playing on a modpack and when I connect to a server/world, I get a crash stating "flywheel:model not recognized." It's a render issue, and at first I had to remove sodium because sodium was causing flywheel to not render correctly and crash. After I removed sodium, I was able to load into a world, but when I tried to reconnect later I got the same crash. 

### Reproduction Steps

1. Have 1.18.2 fabric and create mod
2. Successfully connect to a server
3. Disconnect and relaunch minecraft
.4. Attempt to reconnect, but get the error.

### Expected Result

A crash.

### Crash Report or Log

https://pastebin.com/qW3Qj4kr

### Operating System

Windows 10

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

### Other Mods

The crash report shows the other mods.

**Comment by TropheusJ** [comment] 2022-09-12 22:19
seems to be a duplicate of #461

**Closed as completed by TropheusJ** 2022-09-12 22:19 UTC
Labels: type: bug
