### ISSUE TITLE
Deployer set to attack mode crashes game, ticking block entity error. 

### ISSUE THREAD

**Issue by BedrockBurger** [Fabricators-of-Create/Create#1238] opened 2023-12-23 21:55 UTC
### Describe the Bug

Making a contraption designed to farm infinite exp through punching silverfish after creating then haunting stone. Inspired by one made by RagePlaysGames. Game crashes due to ticking block entity error when deployer set to attack mode kills the silverfish to collect the exp nuggets. When logging back on, game picks off right where it crashed. Have picked up and moved deployer, have moved it and the silverfish drop chamber into the same chunk, have added more RAM allocation to Minecraft. None have worked

Making the contraption on a Creative superflat world to then remake in a server.

### Reproduction Steps

1. Deployer set to attack mode 
2. Silverfish with very little health drops in front of it
3. Deployer punches and kills silverfish with goal to collect silverfish exp as nuggets
4. Game crashes

Crash Log below for your convenience

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-12-23 16:07:09
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "capturedDrops" is null
	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activateInner(DeployerHandler.java:207)
	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activate(DeployerHandler.java:134)
	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.activate(DeployerBlockEntity.java:358)
	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.tick(DeployerBlockEntity.java:244)
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activateInner(DeployerHandler.java:207)
	at com.simibubi.create.content.kinetics.deployer.DeployerHandler.activate(DeployerHandler.java:134)
	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.activate(DeployerBlockEntity.java:358)
	at com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity.tick(DeployerBlockEntity.java:244)
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)

-- Block entity being ticked --
Details:
	Name: create:deployer // com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity
	Block: Block{create:deployer}[axis_along_first=false,facing=east]
	Block location: World: (-87,-62,176), Section: (at 9,2,0 in -6,-4,11; chunk contains blocks -96,-64,176 to -81,1023,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,1023,511)
	Block: Block{create:deployer}[axis_along_first=false,facing=east]
	Block location: World: (-87,-62,176), Section: (at 9,2,0 in -6,-4,11; chunk contains blocks -96,-64,176 to -81,1023,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,1023,511)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['BladeBurger'/75, l='ServerLevel[Create Build World]', x=-87.04, y=-58.26, z=179.05]]
	Chunk stats: 4761
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,1023,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,1023,511)
	Level time: 2132540 game time, 78583 day time
	Level name: Create Build World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 970788952 bytes (925 MiB) / 3523215360 bytes (3360 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4601
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30669.36
	Virtual memory used (MB): 25096.69
	Swap memory total (MB): 14336.00
	Swap memory used (MB): 842.44
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ad_astra: Ad Astra 1.15.3
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		azurelibarmor: AzureLib Armor 1.0.3
		botarium: Botarium 2.2.0
			team_reborn_energy: Energy 3.0.0
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		chunkloaders: Chunk Loaders 1.2.8+a
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		create: Create 0.5.1-d-build.1161+mc1.20.1
			com_electronwill_night-config_core: core 3.6.3
			com_electronwill_night-config_toml: toml 3.6.3
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.9-1
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
			porting_lib_base: Porting Lib Base 2.1.1127+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
				porting_lib_common: Porting Lib Common 2.1.1127+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
			porting_lib_models: Porting Lib Models 2.1.1127+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create_enchantment_industry: Create Enchantment Industry 1.2.10
			create_dragon_lib: Create Dragon Lib 1.4.1
		createbigcannons: Create Big Cannons 0.5.2.a-nightly-3b4e734
		delightfulcreators: Delightful Creators 1.1.8
		expandeddelight: Expanded Delight 0.3.0.2
		fabric-api: Fabric API 0.90.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.2+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.6+d7b148e077
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.23
		farmersdelight: Farmer's Delight 1.20.1-1.4.2
		farmersrespite: Farmer's Respite 2.3.4
		forgeconfigapiport: Forge Config API Port 8.0.0
		fusion: Fusion 1.0.6
		fwaystones: Fabric Waystones 3.1.3+mc1.20
		immersive_aircraft: Immersive Aircraft 0.6.2+1.20.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.27
		litematica: Litematica 0.15.3
		malilib: MaLiLib 0.16.2
		mcwbridges: Macaw's Bridges 2.1.0
		minecraft: Minecraft 1.20.1
		mousetweaks: Mouse Tweaks 2.25
		nethersdelight: Nether's Delight 1.0.0
			disable_custom_worlds_advice: Disable Custom Worlds Advice 4.1
		owo: oωo 0.11.0+1.20
			blue_endless_jankson: jankson 1.2.2
		patchouli: Patchouli 1.20.1-81-FABRIC
			fiber: fiber 0.23.0-2
		player-animator: Player Animator 1.0.2-rc1+1.20
		railways: Create: Steam 'n' Rails 1.5.1+fabric-mc1.20.1
			mm: Manningham Mills 2.3
		rechiseled: Rechiseled 1.1.5+a
		replaymod: Replay Mod 1.20.1-2.6.13
		resourcefulconfig: Resourcefulconfig 2.1.0
		resourcefullib: Resourceful Lib 2.1.11
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		respitecreators: Respite Creators 1.2.0
		runes: Runes 0.9.10+1.20.1
		spell_engine: Spell Engine 0.11.0+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		spell_power: Spell Power Attribute 0.9.18+1.20.1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.15
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.6
		trinkets: Trinkets 3.7.1
		valkyrienskies: Valkyrien Skies 2 2.3.0-beta.4
			fabric-language-kotlin: Fabric Language Kotlin 1.8.5+kotlin.1.7.20
				org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
				org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
				org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
				org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
				org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.4
				org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
				org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
				org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
				org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
				org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
				org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		vs_eureka: VS Eureka Mod 1.3.0-beta.2
		wizards: Wizards 1.0.1+1.20.1
		xaeroworldmap: Xaero's World Map 1.34.1
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 1 / 8; [class_3222['BladeBurger'/75, l='ServerLevel[Create Build World]', x=-87.04, y=-58.26, z=179.05]]
	Data Packs: vanilla, fabric, file/skyhigh 1.20.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.23-1.20.1

### Expected Result

I would hope not to crash and make an exp farm for my server.

### Operating System

Windows 10 with Fabric Minecraft

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Ad Astra
Azurelibarmor
Botarium
Cardinal Componets
Chunkloaders
Cloth config
Create Enchantment Industry
Create Big Cannons
Create Fabric
Delightful Creators
Eureka
Expanded Delight
Fabric API
Farmers Delight Fabric
Farmers Respite
ForgeConfigAPIPort
Fusion
Immersive Aircraft
JEI
Litematica
Malilib
Macaws Bridges
MouseTweaks
Nethers Delight
OwO Lib
Patchouli
player animator library fabric
Rechiseled
Replay Mod
Resourcefulconfig
Respite Creators
Runes Fabric
Spell Engine
Spell Power
Create Steam n Rails
supermartjin642configlib
supermartjin642corelib
Travelers Backpack
Trinkets
Valkyrien Skies
Wizards RPG Series
Waystones for Fabric
Xaeros World Map

**Comment by TropheusJ** [comment] 2023-12-23 22:26
duplicate of #1096

**Closed as completed by TropheusJ** 2023-12-23 22:26 UTC
Labels: type: bug
