### ISSUE TITLE
Game crash occurs when a minecart structure with a chest is materialized (can be reliably reproduced)

### ISSUE THREAD

**Issue by eyja42** [Fabricators-of-Create/Create#1102] opened 2023-09-09 14:53 UTC
### Describe the Bug

(This is my very first time to open an issue, so make me noticed if there's anything I didn't explain clearly.)
I was playing on minecraft 1.20, with fabric 0.14.21, fabric api-0.86.1 and create-0.5.1d(which is the only mod loaded, as shown in the mc crash report below), and discovered a way to get game crashed.
The crash-report, minecart mashine blueprint and a world save are attached.

### Reproduction Steps

1. build the machine, either by placing blocks on your own or directly print it in creative mode.
2. right click the clockwork bearing, so the shaft on it becomes an entity.
3. turn on the lever, the minecart machine becomes an entity.
4. fill the chest on the machine with the item specified by the brass funnel(I used cogwheel in the blueprint).
5. close the chest, and turn down the lever. The whole machine turns into blocks again.
6. turn on the lever again, and take items out of the chest(either only take a few or clear the chest is OK).
7. finally, turn down the lever - boom!

### Expected Result

The game shouldn't crash. I guess the new feature allowing chests on moving structure being opened should be blamed...

### Crash Report or Log

https://github.com/eyja42/create_crash_report_2023_9

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

no other mods

**Comment by FelixBrakel** [comment] 2023-09-10 09:56
I am experiencing the same crash it seems:

[crash-2023-09-09_21.17.49-server.txt](https://github.com/Fabricators-of-Create/Create/files/12567951/crash-2023-09-09_21.17.49-server.txt)

**Comment by TropheusJ** [comment] 2023-12-18 02:19
duplicate of #1080

**Closed as completed by TropheusJ** 2023-12-18 02:19 UTC
Labels: type: bug
